### ISSUE TITLE
Issue warning that setting seed limits parallelism

### ISSUE THREAD

**Issue by crypdick** [lmcinnes/umap#1001]
It took me a while to diagnose why UMAP was only using 1 core (despite setting `num_jobs=-1`): UMAP limits to 1 core if you set the `random_state`. I would consider that non-obvious behavior and think that a warning should be issued if `random_state` is set and `num_jobs != 1`.

**Comment by lmcinnes** [comment]
I agree that a warning for that kind of case makes some sense. Do you have time to make a PR?
