### ISSUE TITLE
numba error when running compute_visualization() with method=umap

### ISSUE THREAD

**Issue by NevilleMthw** [lmcinnes/umap#1006]
Hi,

I am facing an issue with this library when trying to create some visualizations. This is in regards to an application called FiftyOne which uses umap. Apparently the owner of the FiftyOne repo seems to think it is a library issue with umap. The issue is located here with the stack trace log. 

Issue: voxel51/fiftyone#2955

Hope it is a valid issue. Thanks.

**Comment by lmcinnes** [comment]
Thanks, I think I can fix this at this end.

**Comment by NevilleMthw** [comment]
Hi, should I just install normally through pip to check if it works?

**Comment by lmcinnes** [comment]
Unfortunately since this is a minor patch it is not pushed to pip yet; you
would need to clone the repository and install from there. Alternatively
you could install via pip with

pip install git+https://github.com/lmcinnes/umap.git

**Comment by NevilleMthw** [comment]
Sorry for the late reply, I have downloaded through pip as you suggested and the visualization gets displayed now. Thanks a lot. Just a small question, if I need to download it for another time, can I just use normal pip install or through pip install git+https://github.com/lmcinnes/umap.git?

**Comment by lmcinnes** [comment]
It will work once a new release is made; I'm not sure when that will be -- I try to aggregate a bunch of minor fixes like this together before making a release. In the meantime you'll need the pip install git+https://github.com/lmcinnes/umap.git . Sorry about that.

**Comment by NevilleMthw** [comment]
No issues. Thanks a lot for your quick help. Appreciate it.
