### ISSUE TITLE
Using UMAP for positive correlation

### ISSUE THREAD

**Issue by Rridley7** [lmcinnes/umap#1009]
Hello,
Thanks for developing this tool. I'm looking to use umap for dimensionality reduction before clustering gene data where I'm specifically looking for non-linear positive correlation. I believe this is something like a modified spearman correlation distance, where correlation below 0 is set to 0 , eg 1 - r if r >=0. Would it be expected that this is feasible, and the same assumptions necessary for umap (ie triangle inequality) would hold?

**Comment by lmcinnes** [comment]
I believe you can make this work; The main things are managing to write a distance function that can be compiled with numba (it only supports a subset of python and numpy operations), and checking [potential issues with bounded distances in pynndescent](https://pynndescent.readthedocs.io/en/latest/pynndescent_metrics.html#Beware-of-bounded-distances) and workarounds thereto.

**Comment by Rridley7** [comment]
Got it, thank you!

**Comment by Rridley7** [comment]
Actually, looking at pynndescent it already includes spearman, is there a reason this is not included in umap?
