### ISSUE TITLE
sklearn compatibility when n_samples == 1

### ISSUE THREAD

**Issue by johannfaouzi** [lmcinnes/umap#102]
Hi,

Sorry if my question is a bit out of scope (which is a bit more related to scikit-learn compatibitlity), but I've looked at the code and found this, which intrigued me.

https://github.com/lmcinnes/umap/blob/bf77f919533c9fc33fbcc9f488d48eeb1ac34810/umap/umap_.py#L1336-L1338

I've been looking at scikit-learn source code for some time and I wonder where this restriction comes from. Usually `fit` methods return `self` and this little piece of code prevents your `fit` method from returning `self` every time. In comparison, scikit-learn's implementation of TSNE raises an error in that scenario (not directly, but when calling the neighbor algorithm, because the number of neighbors is equal to zero). Could you explain me why you decided to handle this 'irrelevant' scenario this way?

Moreover, if you stick with this choice, shouldn't it return an array of zeros whose length depends on `n_components` (i.e. `np.zeros(self.n_components)`)?

Obviously it's not very important, but it just intrigued me, so if you have the time to answer, it would be really appreciated.

**Comment by lmcinnes** [comment]
That's a bug -- I believe I was thinking of ``fit_transform`` not ``fit``.
I will get that fixed. Good catch! thanks.

**Comment by johannfaouzi** [comment]
https://github.com/lmcinnes/umap/blob/23e6af696ef715c21655faa7cdefb7d44a5f9d0c/umap/umap_.py#L1336-L1339

With the current code, the docstring for the `fit_transform` method is not compatible with the way you deal with the "one sample" scenario. The `fit_transform` method should return a numpy.array with shape `(n_samples, n_components)`, but it will return `np.array([0.0, 0.0])`. You may want to replace `np.array([0.0, 0.0])` with `np.zeros((1, self.n_components))`. I didn't run the code with the latest version on GitHub so I don't know if it would handle the `transform` method.

You could also update the docstring of the `fit` method to say that it returns self.

**Comment by lmcinnes** [comment]
Good point, thanks. I hate corner cases (as you have probably noticed) and
don't always spend enough time on them. I definitely appreciate your
corrections!

**Comment by lmcinnes** [comment]
I feel like I have a reasonable approach -- it isn't expensive to use
``np.zeros((1, self.n_components))``, and that is good enough in this odd
circumstance.

**Comment by johannfaouzi** [comment]
It's not enough because the `transform` method returns an error if you fit with one sample:

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-8-b21dd561e9fc> in <module>()
----> 1 embedding.transform(np.random.randn(40, 20))

c:\users\johann\src\umap\umap\umap_.py in transform(self, X)
   1541         X = check_array(X, dtype=np.float32, accept_sparse="csr")
   1542         x_hash = joblib.hash(X)
-> 1543         if x_hash == self._input_hash:
   1544             return self.embedding_
   1545 

AttributeError: 'UMAP' object has no attribute '_input_hash'
```

When you return `np.zeros((1, self.n_components))` early in `fit,` none of the code below is run. Maybe you could add something like `self._fit_with_one_sample = True` if it happens, otherwise `self._fit_with_one_sample = False`.

Then, early in `transform`, you could add something like:
```python
if self._fit_with_one_sample:
    return np.zeros(X.shape)
```
