### ISSUE TITLE
Numba.jit and numpy dependency problems

### ISSUE THREAD

**Issue by ekwan** [lmcinnes/umap#1048]
Hi, I'm getting this warning with umap 0.5.3:

```
  @numba.jit()
/Users/kwaneu/sw/miniconda/miniconda3/envs/python/lib/python3.11/site-packages/umap/umap_.py:660: NumbaDeprecationWarning: The 'nopython' keyword argument was not supplied to the 'numba.jit' decorator. The implicit default value for this argument is currently False, but it will be changed to True in Numba 0.59.0. See https://numba.readthedocs.io/en/stable/reference/deprecation.html#deprecation-of-object-mode-fall-back-behaviour-when-using-jit for details.
```

I'm also seeing umap complain it only supports up to numpy 1.24.0.

**Comment by mbelak-dtml** [comment]
This is already fixed on main by https://github.com/lmcinnes/umap/commit/8a9418266d9e7825bfe974cf2d52fbafca32e1f1.
However, this is not released yet.

@lmcinnes Any plans for releasing?

**Comment by lmcinnes** [comment]
There should be a new release out now, and hopefully this is now resolved.

**Comment by mbelak-dtml** [comment]
@ekwan The issue is resolved in the latest release. Can we close this?

**Comment by ekwan** [comment]
Checked and this has fixed the problem!  Thank you!
