### ISSUE TITLE
[Request] Implement localization

### ISSUE THREAD

**Issue by Dece** [lmcinnes/umap#105]
Hi, we would be very interested to see in uMap the ability to have localized maps, that is a single map with the same data and points but with possibly different titles and descriptions in other languages. For example the map could have a language button to switch between French, English, Arabic, whatever that would just load another load of text data. The map could be filled in French first, and when switching to another language, have either blank fields or default automatically translated texts.

To illustrate this request, we have a [map with points for refugees](https://umap.openstreetmap.fr/fr/map/lieux-utiles-pour-les-refugies-sur-lyon_203147) that we would like to translate in several languages. The only option right now is to duplicate the map data to another map and replace all text fields, which leads to data dups and thus unsynchronized changes.

Let me know if you want more input!

Cheers.

**Comment by lmcinnes** [comment]
I think you are looking for [umap-project/umap](
https://github.com/umap-project/umap); this is a machine learning library.

**Comment by Dece** [comment]
Damn, this is embarrassing... Moving the issue there, sorry!
