### ISSUE TITLE
self._raw_data and self._sparse_data in fit method of UMAP class

### ISSUE THREAD

**Issue by johannfaouzi** [lmcinnes/umap#107]
### Raw data

I observed that `self._raw_data` is defined two times in the `fit` method of the UMAP class:

https://github.com/lmcinnes/umap/blob/23e6af696ef715c21655faa7cdefb7d44a5f9d0c/umap/umap_.py#L1334

https://github.com/lmcinnes/umap/blob/23e6af696ef715c21655faa7cdefb7d44a5f9d0c/umap/umap_.py#L1404

I was wondering whether it is intended or not. The first time is always run, but the second time is only run `if not X.shape[0] < 4096:`.

### Sparse data

https://github.com/lmcinnes/umap/blob/23e6af696ef715c21655faa7cdefb7d44a5f9d0c/umap/umap_.py#L1349-L1353

`if scipy.sparse.isspmatrix_csr(X) and X.has_sorted_indices:` will give `self._sparse_data = False`. I am not sure that it is intended since `X.sort_indices()` will sort the indices of X in place and then you will have `self._sparse_data = True`. I'm not very familiar with sparse matrices though, I may have missed something.

Best regards

**Comment by lmcinnes** [comment]
These seem like errors. I'll try to clean things up soon (or you are
welcome to submit a PR if you wish).

**Comment by lmcinnes** [comment]
Merged, thanks.
