### ISSUE TITLE
warning in spectral_layout

### ISSUE THREAD

**Issue by johannfaouzi** [lmcinnes/umap#108]
https://github.com/lmcinnes/umap/blob/23e6af696ef715c21655faa7cdefb7d44a5f9d0c/umap/spectral.py#L226-L231

Looking at what's in format (`n_components`), I think that you probably wanted to write `Embedding connected {} components`.

**Comment by lmcinnes** [comment]
I believe this is correct -- it is giving the number of connected
components in the graph which is given by the value of ``n_components``.

**Comment by lmcinnes** [comment]
I think I will try to clean up the wording so it is more clear; the current
message is correct, but it obviously is not clear enough to avoid confusion.

**Comment by sleighsoft** [comment]
Looks like @lmcinnes resolved this. Reopen if necessary.
