### ISSUE TITLE
Speed inquries

### ISSUE THREAD

**Issue by rangehow** [lmcinnes/umap#1093]
When I reduce 10,000 vectors of 768 dimensions to 16 dimensions using the following command, it takes about 4 minutes. Is this normal? It seems a bit slow. If there are any suggestions for speeding up or any mistakes in my code, I would appreciate some help. Thank you all.

```python
clusterable_embedding = umap.UMAP(
                    n_neighbors=n_neighbors,
                    min_dist=0.0,
                    n_components=n_dim,
                    # random_state=42,
                    n_jobs=-1
                ).fit_transform(X)
```

**Comment by lmcinnes** [comment]
That does seem rather slow; I can't say why it is taking that long though. Perhaps turn ``verbose=True`` on and see if there are steps that are taking a particularly long time.
