### ISSUE TITLE
0.5.6 is not available for macos

### ISSUE THREAD

**Issue by marvin-min** [lmcinnes/umap#1144]
Currently, the latest available version for MacOS is 0.5.5. Is there any plan to make the 0.5.6 work on MacOS？
Thanks

**Comment by lmcinnes** [comment]
I generally rely on conda-forge to take care of those kinds of things. I'm
not quite sure what the blocker is -- it may be in the dependency
requirements. Hopefully it will resolve itself with time or in a newer
release?

**Comment by jakirkham** [comment]
Likely this was issue: https://github.com/conda-forge/umap-learn-feedstock/issues/44

That issue was fixed by PR: https://github.com/conda-forge/umap-learn-feedstock/pull/45

So think most likely this has been resolved
