### ISSUE TITLE
n_neighbors and self.n_neighbors both used in UMAP class

### ISSUE THREAD

**Issue by johannfaouzi** [lmcinnes/umap#117]
Hi,

At the very beginning of the `fit` method of UMAP class, `n_neighbors` is defined:
https://github.com/lmcinnes/umap/blob/02afd05e862b60e0b336167a02957241a3a73107/umap/umap_.py#L1335-L1346

Then, in the same method, both variables are used:
https://github.com/lmcinnes/umap/blob/02afd05e862b60e0b336167a02957241a3a73107/umap/umap_.py#L1366
https://github.com/lmcinnes/umap/blob/02afd05e862b60e0b336167a02957241a3a73107/umap/umap_.py#L1392
https://github.com/lmcinnes/umap/blob/02afd05e862b60e0b336167a02957241a3a73107/umap/umap_.py#L1446
I'm wondering whether or not it is intended.

Moreover, in the `transform` method, only `self.n_neighbors` is used (which is "normal" since `n_neighbors` is local variable for the `fit` method). I'm wondering whether or not it is also intended.

I would have expected the truncation to be used everywhere, i.e. define `self._n_neighbors` instead of `n_neighbors` in `fit` and then use `self._n_neighbors` everywhere.

**Comment by lmcinnes** [comment]
The truncation depends on the data passed; but indeed should be used
everywhere once it has been defined. The ``self._n_neighbors`` is the right
approach. If you want to put in a PR it would be appreciated.
