### ISSUE TITLE
Sparse matrix support

### ISSUE THREAD

**Issue by lmcinnes** [lmcinnes/umap#12]
In principle a distance function could take sparse vectors and thus allow UMAP to take sparse matrices as input. This would allow for much higher dimensional data (NLP related data for example) to be handled by UMAP.

**Comment by infalco** [comment]
This would be an amazing feature!

**Comment by lmcinnes** [comment]
It should now be working. Some distance measures won't work for sparse data (Haversine and Yule are the major ones). You will also need to write different custom metrics for the sparse case, and I haven't enabled that as an option just yet (although it should be an easy change -- I just want to be able to verify the function is valid, and I need to know how to get that info out of numba).
