### ISSUE TITLE
Pre-requisite python 64

### ISSUE THREAD

**Issue by ongch** [lmcinnes/umap#121]
Hi, really keen on trying this version of UMAP (particularly with the Shiny integration).  I've complied with the following:
- python's packages & version
- R package reticulate 

However, always ended with the following:
Thanks in advance,
Chris

* installing *source* package 'umapr' ...
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'umapr'
    finding HTML links ... done
    make_umap_object                        html  
    run_umap_shiny                          html  
    umap                                    html  
** building package indices
** testing if installed package can be loaded
*** arch - i386
Error: package or namespace load failed for 'umapr':
 .onLoad failed in loadNamespace() for 'umapr', details:
  call: initialize_python(required_module, use_environment)
  error: Your current architecture is 32bit however this version of Python is compiled for 64bit.
Error: loading failed
Execution halted
*** arch - x64
ERROR: loading failed for 'i386'
* removing 'C:/R/library/umapr'
In R CMD INSTALL
Installation failed: Command failed (1)

**Comment by lmcinnes** [comment]
So the bad news is that this version of umap doesn't play well with 32bit
windows (due to issues with numba on that platform). You may want to try
looking at the UWOT package by James Melville which doesn't have shiny
integration, but has a better chance of working with R on your platform.

**Comment by ongch** [comment]
Thanks for the response & suggestion Leland.
