### ISSUE TITLE
What does smooth_knn_dist do?

### ISSUE THREAD

**Issue by WaasTop** [lmcinnes/umap#141]
I'm trying to understand a mathematical justification for what is happening in the function "smooth_knn_dist" right now. If I understand what you state in the paper and in your commentary correctly, this function is supposed to output the distance to the nearest neighbor, as well as some normalizing factor, that should at least approximately agree with the distance to the k-th nearest neighbor.

If I understand the iteration in there correctly you should end up with a value m that approximately fulfills:
 Sum exp(-d_i/m) ~ log_2 (k)
I fail to see how this would make m close to the value of the distance to the k-th nearest neighbor.

What am I missing here?

**Comment by lmcinnes** [comment]
The goal is to have the cardinality of the fuzzy set of a 1-simplices
associated to the point be fixed. Some of the choices here are a little
arbitrary (the log_2 in particular). But the goal is to be softer in the
selection of a k-neighbor distance; you can think of it as akin to a
weighted average style of thing if that helps.
