### ISSUE TITLE
Color map of UCI shuttle dataset visualization in README

### ISSUE THREAD

**Issue by zbarry** [lmcinnes/umap#144]
Hi all,

I think one might consider changing the color map used for the shuttle example. It is different from the Fashion / standard MNISTs and largely obscures the different classes.

The shuttle dataset visualization:

![](https://github.com/lmcinnes/umap/raw/master/images/umap_example_shuttle.png)

It's nearly impossible to evaluate the performance of UMAP on this dataset based on the map chosen. Could be worth changing to be consistent with the other two examples.

**Comment by lmcinnes** [comment]
Oddly enough no colormaps looks particularly good due to very unbalanced
classes. This was the best I found after trying several. I agree it is not
great, but it remains better than the alternatives.

**Comment by zbarry** [comment]
Ahh, got it. Didn't actually know that about the dataset. Thanks!
