### ISSUE TITLE
using umap as a preprocessing step

### ISSUE THREAD

**Issue by atarashansky** [lmcinnes/umap#147]
umap-learn is truly groundbreaking. It has completely replaced t-SNE when I generate all my embeddings.

I'm also curious about using umap as a preprocessing step (the possibility of which was noted in the README) in lieu of PCA. Apologies if this has been answered elsewhere, but does anyone have any intuition for how many components one should keep when applying umap? In PCA, one can roughly glean that kind of information by looking at the variance captured by each principal component. Is there something analogous for umap?

Thanks,

**Comment by josephcourtney** [comment]
[Here](https://github.com/lmcinnes/umap/blob/master/examples/plot_feature_extraction_classification.py) is an example of using UMAP for feature extraction before SVM classification. The best number of embedding dimensions depends on the intrinsic dimensionality of the data manifold and how good UMAP is at untangling it. It is best determined empirically using something like [GridSearchCV](http://scikit-learn.org/stable/modules/generated/sklearn.model_selection.GridSearchCV.html) in [sklearn](http://scikit-learn.org).

**Comment by jay-reynolds** [comment]
I'm currently looking at using this method as a starting point for determining intrinsic dimension: 

"Maximum Likelihood Estimation of Intrinsic Dimension"
https://www.stat.berkeley.edu/~bickel/mldim.pdf  (there's a python implementation available on github)

... and that is to say it works, but I have not yet wedged around the estimate of intrinsic dimension to see if I can get better results.

**Comment by lmcinnes** [comment]
Looks promising. Thanks for the link!

**Comment by EricThomson** [comment]
For folks curious, this repo lets you use multiple different strategies to estimate the intrinsic dimensionality of your data: 
https://scikit-dimension.readthedocs.io/en/latest/index.html

I haven't used it yet, but it looks very good on first glance.
