### ISSUE TITLE
Fails on Google Colab :(

### ISSUE THREAD

**Issue by sokrypton** [lmcinnes/umap#150]
It worked a few weeks ago. So I suspect it has something to do with Google Colab library update. But I cannot figure out what. Any help would be great! I was hoping to demonstrate umap in a workshop next week.

https://colab.research.google.com/drive/15vgtSCbW4XzWb_qwe32Iq_xHteC6--QA

Has anyone seen this error before:
Inconsistency detected by ld.so: dl-version.c: 224: _dl_check_map_versions: Assertion `needed != NULL' failed!

**Comment by sokrypton** [comment]
installing an older version of numba "fixed" the issue! thanks.
```
!pip install umap-learn
!pip install 'numba=0.3.1'
```

**Comment by yinleon** [comment]
Hey @lmcinnes what version of `numba` and `umap-learn` should we be using? I am running into numba-related errors similar to this issue and a few more. I can create a new issue if that helps.

**Comment by lmcinnes** [comment]
numba 0.43.1 certainly works, but most things newer than 0.38 should be fine. The catch is more in the ungrading./re-installing step -- sometimes things go astray. Unfortunately this is rather more of a devops issue than I am qualified to handle, so I can't say much useful.

**Comment by sleighsoft** [comment]
Hey @sokrypton did you get it running on Colab? If yes, can you please close the issue.
