### ISSUE TITLE
Is there a way to save, and restore a particular umap embedding? 

### ISSUE THREAD

**Issue by greyowl** [lmcinnes/umap#152]
I'm trying to train a umap embedding and use it as a preprocessing step for a classification. Is there a way to save and restore a trained umap embedding?

**Comment by lmcinnes** [comment]
The models should be pickleable, just like scikit-learn objects. Note that
if you are still on python 2.7 you may have to take some care to ensure you
use the right pickle protocol, but for python3 it should "just work".

**Comment by greyowl** [comment]
Thanks for the reply it worked!

**Comment by oiao** [comment]
@lmcinnes, sorry to dig this issue out, but is there a way to store the UMAP parameters directly, rather than pickling the complete class instance? The latter is not really robust to changes in the referenced Python object.

**Comment by kobiche** [comment]
I can relate. I dump the pickle using python3.8 and cannot load it using python3.11. Please help!
