### ISSUE TITLE
Reducing to n-dims with n=/=2

### ISSUE THREAD

**Issue by fistR** [lmcinnes/umap#159]
Hey,

UMAP works extremely well for reducing to two dimensions. 
Would it be a big change to make it reduce to any number of dimensions, or at least 3?

Unless this is already implemented and I'm missing how to do it.

**Comment by lmcinnes** [comment]
It is indeed already implemented. The parameter you want is
``n_components``, so named to be compatible with sklearn's naming
convention for such things. UMAP scales well with embedding dimension, so
you can go as high as you like -- although in practice embedding to
dimensions larger than what you set ``n_neighbors`` to will produce
significantly diminishing returns.

**Comment by fistR** [comment]
Well that's embarrassing. Has that always been there? I swear when I checked half a year ago I couldn't find it. 

This is great, sorry for the useless issue!
