### ISSUE TITLE
Wrapping my head around semi-supervised/supervised UMAP

### ISSUE THREAD

**Issue by biobenkj** [lmcinnes/umap#160]
Hi Leland,

UMAP is incredible. Thank you! After going through the documentation, some code, your PyData talk in Ann Arbor, MI, I can't quite wrap my head around the (semi-)supervised UMAP. My current understanding from https://github.com/lmcinnes/umap/issues/135 is that you construct two separate fuzzy simplicial sets - one for the data following manifold embedding; and one for the labeled data with arbitrary distances (0-points in the same group; 1-points in opposite groups; and 0.5 for unknowns). Is the latter fuzzy simplicial set also constructed following manifold embedding or just so as to be the "target" behavior for the data with which we can intersect both sets, reconciling the two?

I'm not sure if I've articulated this well...

Thanks for your time!

**Comment by biobenkj** [comment]
I think so... Just to clarify, you basically take the fuzzy simplicial set for the target data (which are effectively edge weights for labels if comparing the sparse graphs) and scale the original data distances to reflect these weights (multiply by the categorical edge weights, whatever those are). Following this, we need to reset the local connectivity (e.g. Definition 9 in the manuscript?) to reflect the new distances and finally take the union of the fuzzy set. Then we can find a low dim representation of the union'd fuzzy set. Is this correct from a methodological standpoint? Again, my apologies if this is naive and thank you for your time!

**Comment by lmcinnes** [comment]
That's all correct except for the order -- we union the local reps first (for the data and target fuzzy simplcial sets), and then do the intersection and resetting local connectivity.,

**Comment by biobenkj** [comment]
Brilliant. I think I've got a better understanding of this! Thank you again!
