### ISSUE TITLE
Transform doesn't work in supervised mode

### ISSUE THREAD

**Issue by bakirillov** [lmcinnes/umap#161]
Hello!
When I try to use transform() method of umap model trained in supervised mode on continuous data, I get the following error:
IndexError: Failed at nopython (convert to parfors)
list index out of range
The embeddings_ of the model are constructed without error during training and are not nan.
Could you please look into it?

**Comment by lmcinnes** [comment]
Generally speaking this has worked just fine on the examples I have; are you able to share your data so I can attempt to reproduce the problem (I understand if this is not the case)?

**Comment by bakirillov** [comment]
Got the data that reproduce error and which I can share.
The code to reproduce is:
`
X = np.load("X.reproduces.umap.error.npy")
Y = np.load("Y.reproduces.umap.error.npy")
trans = umap.UMAP(
    n_components=2, random_state=42, min_dist=0.0, 
    local_connectivity=1, target_weight=0.5, metric="euclidean"
)
trans.fit(
    X, y=Y.round(2)
)
coords = trans.transform(X[0:1000])
`

**Comment by lmcinnes** [comment]
Thanks for the data, it certainly helps. Unfortunately on my current test machine it seems to be working just fine:
![image](https://user-images.githubusercontent.com/11962885/49109983-31b93580-f25a-11e8-94ae-3eb1388ab229.png)
![image](https://user-images.githubusercontent.com/11962885/49109990-367de980-f25a-11e8-9911-f228c4fe855d.png)

For reference I am running a fairly recent version of numba (v0.40.0), but if you are at the current requirements you should be fine. It may be worth upgrading your numba installation in case that can resolve the issue.

**Comment by bakirillov** [comment]
Updating to 0.41 numba solved my problem. Thank you!
