### ISSUE TITLE
Odd results on some datasets

### ISSUE THREAD

**Issue by claresloggett** [lmcinnes/umap#170]
I've been trying UMAP out and I have one real dataset in particular where it does not seem to recover "obvious" structure. I thought it might be worth reporting in case it is a pathological case - or in case I am doing something wrong!

In this dataset there are two distinct groups.  I've tried a few dimensionality reduction methods: PCA, metric MDS and tSNE all split the data into these two expected groups (albeit with different layout details). UMAP puts all the points onto a roughly one-dimensional diagonal line with no real separation between groups, as shown below:

![pathological_plot](https://user-images.githubusercontent.com/1815107/49064524-4b18ac80-f26f-11e8-8fbe-687377cb7799.png)

This sort of pattern seems to happen for various settings of `n_neighbors` (I tried turning it right down) and `min_dist`. I also tried `init='random'`, which didn't change anything. Should I try anything else?

There are quite a lot of zeroes in the data (which could be a cause of the odd behaviour?). Here's a small slice of the data which doesn't include all the points in the plot but does seem to show similar behaviour:

```
0.0	0.0	0.0	85.0	1.0	5.0	4092.0	5427.0	3.0
19.0	0.0	0.0	978.0	1.0	1.0	8739.0	16150.0	1.0
13.0	3.0	1.0	643.0	0.0	0.0	6669.0	11310.0	1.0
0.0	0.0	0.0	7107.0	3.0	11.0	6128.0	2054.0	0.0
0.0	0.0	0.0	5297.0	1.0	14.0	4769.0	1450.0	0.0
19220.0	2614.0	1666.0	12030.0	4700.0	1.0	0.0	0.0	0.0
9805.0	1548.0	1001.0	5820.0	2261.0	0.0	0.0	0.0	0.0
8859.0	1444.0	643.0	6157.0	2061.0	1.0	0.0	0.0	0.0
10740.0	1458.0	837.0	7858.0	2998.0	1.0	1.0	0.0	0.0
12030.0	1634.0	988.0	8304.0	3080.0	0.0	0.0	0.0	0.0
```

Each row here is a sample; it's probably obvious to the eye that the first five of these rows are from one experimental group, and the second five are from the other. 

@lmcinnes I'd be happy to send you the full dataset over a less public channel if that would help!

For contrast here is a tSNE plot for the same data:

![tsne_comparison](https://user-images.githubusercontent.com/1815107/49064712-e6118680-f26f-11e8-8947-f80dbde6d077.png)

PCA also creates a 2D layout and separates the blue and orange points (they are separated along the first principal component).

Is this behaviour expected or pathological? In particular the fact that the points all lie roughly along a diagonal line for the UMAP embedding seems odd.

**Comment by lmcinnes** [comment]
Thanks for the report, and especially the detail. There are definitely some (known) issues with UMAP on small datasets. The implementation was very much coded with large datasets in mind and takes some shortcuts that are acceptable for large data, but can be troublesome for small datasets. Making a different code path that can handle small datasets well (since we don't *need* shortcuts for small data) is on my TODO list, but I haven't gotten there yet. As far as I know the [smallvis](https://github.com/jlmelville/smallvis) is the only implementation of UMAP for small data right now, and is in R, so may not be suitable for your current work. Sorry :-(

**Comment by jlmelville** [comment]
FWIW I ran the UMAP implementation in [uwot](https://github.com/jlmelville/uwot) with `n_neighbors = 3` for the provided data and it did separate the data into two clusters, rather than a line. Does the problem manifest with the sample data?

**Comment by lmcinnes** [comment]
It's likely a bug somewhere in my implementation then. I'll have to see if I can track it down.

**Comment by lmcinnes** [comment]
Okay, well that was stupid on my part -- I had been correcting some issues with really large datasets (where distinct points can end up at distance 0 in the embedding during optimization), but I broke the really small data case (where you might sample yourself as a negative sample --- and shouldn't). It should be fixed now. If you have the time to check out the latest master and verify it on your full dataset I would appreciate it.

**Comment by claresloggett** [comment]
That seems to have fixed it! Thank @lmcinnes, that was fast!

![newplot](https://user-images.githubusercontent.com/1815107/49117262-37fbf000-f2f4-11e8-9ebf-84f1778eeca7.png)

**Comment by lmcinnes** [comment]
Great! Thanks @claresloggett for making it easy, and thanks @jlmelville for letting me know that it was a problem in my version.
