### ISSUE TITLE
Segfault in libffi.so when using dask processes

### ISSUE THREAD

**Issue by goraj** [lmcinnes/umap#172]
I have already posted this to the dask github, however I am not sure if this is related to dask or umap.

The following script segfaults on an updated  Cent OS 7 machine in libffi.so
https://gist.github.com/goraj/ed099c80cd8233e9e8463b37384b2470

The crash triggers depending on what arguments I pass. Importing umap-learn is mandatory to reproduce however.
To reproduce uncomment line 31 and comment 34.

python version: 3.7.1.
dask version: 1.0.0
umap version: 0.3.7

It would be great if someone here can test to reproduce this issue.

**Comment by goraj** [comment]
@lmcinnes thank you.


To reproduce this issue:

./Miniconda3-latest-Linux-x86_64.sh -b -p ~/m3_centos7
source ~/m3_centos7/bin/activate;conda create -n projectname python=3.6
conda activate projectname
conda install dask distributed
pip install umap-learn
python ~/reproduce.py

output can be seen here: https://gist.github.com/goraj/4f38a803e4d9a02ba54e8b61183a81ea

**Comment by sleighsoft** [comment]
@goraj Is this still a problem? If yes, does dask provide any more output than "Got killed" ?

**Comment by goraj** [comment]
@sleighsoft, I think this can be closed. I was unable to reproduce this issue on other machines.

**Comment by sleighsoft** [comment]
Thank you for your timely reply. Great to hear :)
