### ISSUE TITLE
AttributeError: module 'umap' has no attribute 'distances'

### ISSUE THREAD

**Issue by iggisv9t** [lmcinnes/umap#173]
When trying to import umap:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-176-93137e0fcb10> in <module>
----> 1 import umap

~/py36venv/lib/python3.6/site-packages/umap/__init__.py in <module>
----> 1 from .umap_ import UMAP
      2 
      3 # Workaround: https://github.com/numba/numba/issues/3341
      4 import numba
      5 numba.config.THREADING_LAYER = 'workqueue'

~/py36venv/lib/python3.6/site-packages/umap/umap_.py in <module>
     19 import numba
     20 
---> 21 import umap.distances as dist
     22 
     23 import umap.sparse as sparse

AttributeError: module 'umap' has no attribute 'distances'
```

I have read all relevant issues, deleted umap* from site-packages, updated all dependencies, reinstalled umap as `pip install -U umap-learn`, package `umap` was never been installed before, I've checked it by trying to uninstall it. Nothing helps.

**Comment by lmcinnes** [comment]
Thanks for trying to resolve this yourself -- I'm afraid I can't offer too much more help, because I've never seen anything like this before. you can check whether

``~/py36venv/lib/python3.6/site-packages/umap/distances.py``

exists, and if not try downloading the tarball from PyPI and check whether it is in there, because it should exist and for some reason appears not the be in your install.

**Comment by iggisv9t** [comment]
distances.py is present. I've just found that it is not umap issue, because I'm getting completely different error when trying to import umap from command line. Numba fails to import 'cmath'. Updating python from 3.6.5 to 3.6.7 resolves the issue.

**Comment by lmcinnes** [comment]
Glad you found a resolution in the end.

**Comment by mariolovric** [comment]
Dear all,

I have the same error. 
I have saved a UMAP transformer to .sav and tried to load it here.
Python version is 3.6.10.
It is the same environment where it was created and already used from memory instead of a loaded transformer.

```
Traceback (most recent call last):
  File "/path/model.py", line 49, in <module>
    umapped = umap_transformer(fppath='../data/20200229_fp_r3_v5120.csv', filename='../notebooks/umap_fp.sav')
  File "/path/model.py", line 34, in umap_transformer
    transformed_tc = pd.DataFrame(clf.transform(ftc), index=ftc.index, columns=['umap1', 'umap2', 'umap3'])
  File "/home/xxx/anaconda3/envs/envphd/lib/python3.6/site-packages/umap/umap_.py", line 2115, in transform
    self._input_distance_func,
AttributeError: 'UMAP' object has no attribute '_input_distance_func'

```
Any ideas?
