### ISSUE TITLE
Does UMAP can be used inside a **High-Frequency** Time Series Forecasting problem?

### ISSUE THREAD

**Issue by JeremieGauthier** [lmcinnes/umap#175]
Does UMAP can be used inside a **High-Frequency** Time Series Forecasting problem?

UMAP is just awesome as an analysis tool, but what about in real-time? I use LSTM to work inside a High-Frequency Time Series Forecasting Problem. I would like to use UMAP for real-time dimensionality reduction. 

Suppose the unity are the seconds. At each second I have a signal, i.e. -1, 0 or 1, and a set of features. It might have several advantages to use dimensionality reduction in real-time. 

Suppose I have n features each second that we are able to reduce to 3. So for times t_{-n}, t_{n-1}, ..., t_{-1} the n dimensions are reduced to 3 dimensions. When we arrived at time t_0, it should also be quite useful to reduce the dimensions from n to 3 before the training keep moving forward. 

It is easier to train a time-series model with as few dimension as possible.

**Comment by lmcinnes** [comment]
UMAP is largely a transductive technique, which means it isn't really well suited to hard real-time streaming environments unfortunately. Sorry.

**Comment by JeremieGauthier** [comment]
According to your experience, is it possible to tweak the code a bit so that we can convert as an inductive instead of transductive? In other word, is it a hard task to make it usable inside a time-series forecasting model?

**Comment by lmcinnes** [comment]
Not very easily no -- that simply isn't how things are structured. Even theoretically it is hard to learn structure in data inductively like that.
