### ISSUE TITLE
*** numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)

### ISSUE THREAD

**Issue by JeremieGauthier** [lmcinnes/umap#179]
I am having a problem with `UMAP(...).transform()`. I loaded the model with `trans = pickle.load()`.

    ipdb> trans                                                                                                                                 
    UMAP(a=None, angular_rp_forest=False, b=None, init='spectral',
       learning_rate=1.0, local_connectivity=1.0, metric='correlation',
       metric_kwds=None, min_dist=0.5, n_components=3, n_epochs=None,
       n_neighbors=3, negative_sample_rate=5, random_state=None,
       repulsion_strength=1.0, set_op_mix_ratio=1.0, spread=1.0,
       target_metric='categorical', target_metric_kwds=None,
       target_n_neighbors=-1, target_weight=0.5, transform_queue_size=4.0,
       transform_seed=42, verbose=False)

As UMAP uses `numba` package, I got a problem with resolving types. Here is the error shown. 

    ipdb> trans.transform(X_test.reshape(X_test.shape[0], -1))                                                                                  
    *** numba.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
    Invalid use of type(CPUDispatcher(<function rdist at 0x7f36c7ce4e18>)) with parameters (array(float32, 1d, C), array(float64, 1d, C))
    Known signatures:
     * (array(float32, 1d, A), array(float32, 1d, A)) -> float32
     * parameterized
    [1] During: resolving callee type: type(CPUDispatcher(<function rdist at 0x7f36c7ce4e18>))
    [2] During: typing of call at /home/infinity/anaconda3/envs/HFT/lib/python3.6/site-packages/umap/umap_.py (776)
    
    
    File "../../../anaconda3/envs/HFT/lib/python3.6/site-packages/umap/umap_.py", line 776:
    def optimize_layout(
        <source elided>
    
                    dist_squared = rdist(current, other)
                    ^
    
    This is not usually a problem with Numba itself but instead often caused by
    the use of unsupported features or an issue in resolving types.
    
    To see Python/NumPy features supported by the latest release of Numba visit:
    http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
    and
    http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html
    
    For more information about typing errors and how to debug them visit:
    http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile
    
    If you think your code should work with Numba, please report the error message
    and traceback, along with a minimal reproducer at:
    https://github.com/numba/numba/issues/new

Here is a `X_test` sample :

    array([[[-7.84867750e-05, -3.92410776e-05, -1.17713994e-04, ...,
              0.00000000e+00,  0.00000000e+00, -5.88910810e-05],
            [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
              3.22361913e+01,  3.36224857e+01,  0.00000000e+00],
            [-1.17741714e-04, -1.56979711e-04,  0.00000000e+00, ...,
             -3.22361913e+01, -3.36224857e+01, -2.35599012e-04],
            ...,
            [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
              0.00000000e+00,  0.00000000e+00,  3.92395378e-05],
            [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
              0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
            [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
              0.00000000e+00,  0.00000000e+00,  0.00000000e+00]],
    
           [[ 0.00000000e+00,  0.00000000e+00,  7.98615775e-04, ...,
              0.00000000e+00,  0.00000000e+00, -2.66778461e-04],
            [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, ...,
              0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
            [ 1.10377388e-03,  1.86421709e-03,  3.04066897e-04, ...,
              0.00000000e+00,  0.00000000e+00,  5.52533571e-04],
            ...,
            [ 0.00000000e+00,  1.14074947e-04,  3.80220908e-05, ...,
              0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
            [-1.36996749e-03, -4.18338442e-04, -4.18322533e-04, ...,
              0.00000000e+00,  0.00000000e+00, -1.21918711e-03],
            [-3.80814562e-05, -1.10373187e-03, -3.80380000e-05, ...,
              0.00000000e+00,  0.00000000e+00, -1.90615976e-05]]])

X.shape is `(5839, 45, 41)`

How can I solve that type error?

**Comment by lmcinnes** [comment]
Something seems to have gone astray with the picklign and unpickling making
a mess of the dtype of the trained embedding.

On your restored model try something like:

```python
model.embedding_ = model.embedding_.astype(np.int64, order='C')
```

after which hopefully this will work better. I'm a little unclear as to how
we ended up with the wrong dtype in the first place, but that is harder to
diagnose.

**Comment by JeremieGauthier** [comment]
I did not get a success with that method.

**Comment by JeremieGauthier** [comment]
Here is the full code

```
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from MulticoreTSNE import MulticoreTSNE as TSNE
from mpl_toolkits.mplot3d import Axes3D
from datetime import datetime
from datetime import date

import matplotlib.pyplot as plt
import plotly.offline as py_offline
import plotly.graph_objs as go
import pandas as pd
import numpy as np
import argparse
import pickle
import umap
import time
import os


def umap_plot(trans, label, transform=False):

    fig = plt.figure(figsize = (8,8))
    ax = fig.add_subplot(1, 1, 1, projection='3d')

    ax.set_title('UMAP - 3D representation', fontsize = 20)

    targets = [1, -1]
    colors = ['g', 'r']

    for target, color in zip(targets, colors):
        
        indicesToKeep = np.array([i==target for i in label])

        if target == 1 and transform == True:
            trans.embedding_[indicesToKeep] += 20

        ax.scatter(trans.embedding_[indicesToKeep][:, 0],
                   trans.embedding_[indicesToKeep][:, 1],
                   trans.embedding_[indicesToKeep][:, 2],
                   c = color,
                   s = 20)

    ax.legend(targets)
    ax.grid()

    plt.show()


def get_transform(X, transform="log-full"):
    """
    Transform prices depending on the transform string
    """

    X += 1e-12
    min_x = np.min(X[:, 0, :], axis=0)
    max_x = np.max(X[:, 0, :], axis=0)
    if transform == "log-price":
        X[:, :, -1] = np.log(X[:, :, -1])
        X[1:,:,-1] = X[1:, :, -1] - X[:-1, :, -1]
        X[:, :, :-1] = (X[:,:,:-1] - np.min(X[:,:,:-1],axis=0)) / ( np.max(X[:,:,:-1],axis=0) -  np.min(X[:,:,:-1],axis=0))
        X = X[1:]
    elif transform == "log-full":
        X = np.log(X)
        X = X[1:, :, :] - X[:-1, :, :]

    else:
        X[:, :, -1] = (X[:, :, -1] - min_x[-1]) / (max_x[-1] - min_x[-1])
        X = X[1:, :, :] - X[:-1, :, :]

    return X


def get_params():
    parser = argparse.ArgumentParser()
    parser.add_argument("--data", default=None, type=str, help="Load the data")
    parser.add_argument("--label", default=None, type=str, help="Load the labels")

    return parser

args = get_params().parse_args()

X, _ = pickle.load(open(args.data, "rb"))
_, label = pickle.load(open(args.label, "rb"))

X = get_transform(X)
label = label[1:]

assert(len(X)==len(label))

X_train, X_test, y_train, y_test = train_test_split(X, label)

#X_train, X_test = X_train.astype(np.float32, order='C'), X_test.astype(np.int32, order='C')


## TRAIN PART ##
start_time = time.time()
trans = umap.UMAP(n_components=3,
                      n_neighbors=3,
                      min_dist=0.5,
                      metric="correlation").fit(X_train.reshape(X_train.shape[0], -1), y=y_train)    
print("--- %s seconds ---" % (time.time() - start_time))

umap_plot(trans, y_train)
umap_plot(trans, y_train, transform=True)

listing = list(zip(trans.embedding_.tolist(), y_train))
from random import shuffle
shuffle(listing)
trans.embedding_, y_train = list(zip(*listing))
trans.embedding_, y_train = np.array(trans.embedding_), np.array(y_train)

umap_plot(trans, y_train)

## TEST PART ##

import joblib

with open('trans.pkl', 'wb') as f:
    #pickle.dump(trans, f, pickle.HIGHEST_PROTOCOL)
    #pickle.dump(trans, f)
    joblib.dump(trans, f)

with open('trans.pkl', 'rb') as f:
    trans = joblib.load(f)

start_time = time.time()
test_embedding = trans.transform(X_test.reshape(X_test.shape[0], -1))
print("--- %s seconds ---" % (time.time() - start_time))
```

The problem is on the last line.

**Comment by lmcinnes** [comment]
I'm afraid I don't have the time to dig into this in the depth required
right now -- it may be a little time before I can offer much in the way of
a fix. Sorry.

**Comment by JeremieGauthier** [comment]
I found the solution. 

`model.embedding_ = model.embedding_.astype(np.float32, order='A')`

I had to place the above code just after `pickle.load(open("model.pkl", 'rb'))`, because you defined rdist() with `f4(f4[], f4[])`.

**Comment by mfansler** [comment]
Shouldn't [this line](https://github.com/lmcinnes/umap/blob/41205248fb48391d1f6e4effcb974307b7c229ce/umap/umap_.py#L1059) also be changed to ensure that the `init_pos` is a float32?

For instance, I'm still seeing an error when [the scanpy tool](https://github.com/theislab/scanpy/issues/948) passes in a `numpy.float64` object as `init_pos`.

**Comment by ivirshup** [comment]
That had been my original idea (https://github.com/lmcinnes/umap/pull/262), but I recall having the impression it was preferred we fixed this on the scanpy side.

It would make it easier on the scanpy side if this function enforced the use of 32 bit floats, though I recognize it's an internal function. Do maintainers here have any opinion on me reopening https://github.com/lmcinnes/umap/pull/262?

**Comment by AlouiAmine** [comment]
I have the same issue with umap, but when i load it using joblib.load. anyone has an idea how to solve the issue!!? 

  File "competitors_inference_script.py", line 71, in <module>
    umap_model = joblib.load("competitors_analysis_model/umap_model.jb")

  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 585, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 504, in _unpickle
    obj = unpickler.load()
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/pickle.py", line 1085, in load
    dispatch[key[0]](self)
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/joblib/numpy_pickle.py", line 329, in load_build
    Unpickler.load_build(self)
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/pickle.py", line 1549, in load_build
    setstate(state)
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/pynndescent/pynndescent_.py", line 1028, in __setstate__
    self._rp_forest = tuple([renumbaify_tree(tree) for tree in d["_rp_forest"]])
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/pynndescent/pynndescent_.py", line 1028, in <listcomp>
    self._rp_forest = tuple([renumbaify_tree(tree) for tree in d["_rp_forest"]])
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/pynndescent/rp_trees.py", line 1178, in renumbaify_tree
    hyperplanes.extend(tree.hyperplanes)
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/numba/typed/typedlist.py", line 366, in extend
    return _extend(self, iterable)
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/numba/core/dispatcher.py", line 415, in _compile_for_args
    error_rewrite(e, 'typing')
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/numba/core/dispatcher.py", line 358, in error_rewrite
    reraise(type(e), e, None)
  File "/azureml-envs/azureml_60f3017dd63e10f820ba175f00b1e121/lib/python3.7/site-packages/numba/core/utils.py", line 80, in reraise
    raise value.with_traceback(tb)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
- Resolution failure for literal arguments:
No implementation of function Function(<function impl_extend at 0x7fbe848f8598>) found for signature:
