### ISSUE TITLE
UMAP numba import error with py2app freeze

### ISSUE THREAD

**Issue by nsalomonis** [lmcinnes/umap#180]
Greetings,

UMAP is working great in my local version of python however, when creating a frozen binary with py2app, UMAP fails due to a llvmlite error which I posted here:

https://stackoverflow.com/questions/53699054/umap-fails-upon-py2app-build-due-to-libllvmlite-dylib-error

I wasn't sure the best place to ask this question, but here seems appropriate. I have replicated this error on two different Mac's, both with py2app version 0.10 (other versions of py2app produced compilation errors). Everything else seems to be bundling properly.

Thanks,
Nathan

**Comment by lmcinnes** [comment]
I'm afraid I have no experience with py2app. This looks like it is
something to do with the interaction of py2app and llvmlite, which is
definitely something I would struggle to have much sensible to say about
I'm afraid. You may wish to try upstream with the numba folks to see if
they have any thoughts. Sorry I can't be more help.

**Comment by nsalomonis** [comment]
We were able to fix it with an ugly hack that may provide insight in the future.
https://stackoverflow.com/a/53733533/1436086

I did notice however, that version 3.7 of umap doesn't appear to have an __init__ file whereas 3.6 does. I would welcome a clearer solution if any users or developers encounter the same problem (freezing your code is very useful and very problematic with umap).

**Comment by lmcinnes** [comment]
It is very odd that 0.3.7 should lack an init file -- nothing related to
that changed in the update, and as far as I can see it is still there in
the repository. I'll have to look into this further when I get a chance.
Thanks for the report, and the (at least partial) workaround, that I'm sure
others will find useful.

**Comment by sleighsoft** [comment]
@nsalomonis Can this issue be closed?

**Comment by nsalomonis** [comment]
Yes

Best,
Nathan
