### ISSUE TITLE
Using an alternative approximate KNN algorithm

### ISSUE THREAD

**Issue by GWW** [lmcinnes/umap#189]
Hi,

I was wondering if it would be difficult to use an alternative KNN algorithm with UMAP.  I have found that UMAP has issues with a particular set of samples from one of my datasets:

```
python3.6/site-packages/umap/rp_tree.py:712: UserWarning: Random Projection forest initialisation failed due to recursionlimit being reached. Something is a little strange with your data, and this may take longer than normal to compute.
  "Random Projection forest initialisation failed due to recursion"
```

From reading previous issues with similar errors I suspect it has something to do with the these datasets being highly asymmetric, ie. 90% of the 250,000 data points are derived from a single cluster.  From a cursory examination of the UMAP source code it seems that I would only need to change the `nearest_neighbors` function to accomplish this but I wanted to make sure I am not missing something important.

Thanks

**Comment by lmcinnes** [comment]
It is correct that you essentially just need to change the nearest neighbors algorithm. An alternative algorithm would probably not support sparse matrix input however. Ideally the user could pass a ``nn_algorithm`` option to UMAP which would be the relevant (approximate) nearest neighbor function call (with a given fixed API). I don't have time to implement that right now, but would happily accept a pull request. In the meantime if you just want to swap out the ``nearest_neighbors`` function for your own as a hack for your particular case I do believe that should work.

**Comment by GWW** [comment]
Thanks for the quick reply.  I will certainly try a few algorithms and see if they work on these datasets.  I may try to implement your suggestion about the nn_algorithm parameter.  I think it would be a great addition to prevent some redundancy in my work flows where I am using pynndescent to build a KNN graph and then running UMAP on the same data set to embed it.
