### ISSUE TITLE
UMAP - how to link embedding to input data?

### ISSUE THREAD

**Issue by seaspray09** [lmcinnes/umap#195]
How would one track mapping of clusters produced by UMAP to the original input data?
This is different from the issue raised in #169.  Thank you.

**Comment by lmcinnes** [comment]
Everything should be in the same index order, so you should be able to simply match things up by ordering.

**Comment by Pierretherenard** [comment]
This is what I did and it works:
Here the titl list is the input data

hov_txt = list(labels)

        hover_text = []
        i = 0
        for f_t in hov_txt:
            if f_t >= 0:
                hover_text.append(titl[i])
            i += 1
