### ISSUE TITLE
x and y in fit() are not required to be the same length

### ISSUE THREAD

**Issue by kylemcdonald** [lmcinnes/umap#198]
I just ran some code that basically boils down to:

```python
x = np.random.uniform(0, 1, (256, 10))
y = np.random.randint(10, size=(257, 1))
out = umap.UMAP().fit_transform(x, y)
```

And it took me a while to realize I made a bit mistake (the x and y weren't matched with each other) because the output still looked sort of plausible. It could be really good to add a `if y is not None and len(x) == len(y)` exception to the `fit()` and `fit_transform()` functions, just to help out other folks making similar dumb mistakes.

**Comment by lmcinnes** [comment]
@fiza1160: I would be very happy if you want to fix this -- pull requests more than welcome! Thank you.
