### ISSUE TITLE
Default parameters and choice of distance metric

### ISSUE THREAD

**Issue by atarashansky** [lmcinnes/umap#204]
I was wondering if the default choice of hyperparameters (such as local_connectivity, min_dist, spread, etc) were chosen / optimized with respect to a particular distance metric (i.e. Euclidean distance).

In your experience, have you found that the default values typically work "well" (whether aesthetically for visualization or quantitatively for classification tasks) for other distance metrics like correlation, or should I be fiddling with the hyperparameters when I change distance metrics?

Thanks!

**Comment by lmcinnes** [comment]
Relatively speaking I think the other parameters work pretty well regardless of metric, but obviously some of the more different metrics can have a significant impact and may requires some further tuning.

**Comment by BensonRen** [comment]
Can we use the customized distance metric? Seems that it rejected my attempt of doing so.

Thank you so much for your great help!

**Comment by lmcinnes** [comment]
You can, but it needs to be a function that looks like

```python
@numba.njit()
def custom_distance(x, y):
    ...
    return result
```

where result is a postive floating point value. The key is that it has to be numba jittable, so you potentially can't use other libraries and need to write the metric yourself.
