### ISSUE TITLE
An error with numba0.43

### ISSUE THREAD

**Issue by sheetsvicky** [lmcinnes/umap#210]
Hi @lmcinnes. I am new to Python and running UMAP-learn via an interface from R package Seurat. It gives the following error related to Numba, any suggestion? Thank you!

macOS10.12.6; python 2.7; numba 0.43.0

`Error in py_call_impl(callable, dots$args, dots$keywords) 
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Unknown attribute 'shape' of type none`

`File "../../../../../../Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/umap/umap_.py", line 88: `
`def smooth_knn_dist(distances, k, n_iter=64, local_connectivity=1.0, bandwidth=1.0):`
`    <source elided>`
`    target = np.log2(k) * bandwidth`
`    rho = np.zeros(distances.shape[0])`
     ` ^`

`[1] During: typing of get attribute at /Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/umap/umap_.py (88)
`

```
File "../../../../../../Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/umap/umap_.py", line 88:
def smooth_knn_dist(distances, k, n_iter=64, local_connectivity=1.0, bandwidth=1.0):
<source elided>
    target = np.log2(k) * bandwidth
    rho = np.zeros(distances.shape[0])
     ^
```
    

`This is not usually a problem with Numba itself but instead often caused by`
`the use of unsupported features or an i`

**Comment by lmcinnes** [comment]
This seems to be specific to numba 0.43, and is potentially an issue with numba itself. The only solution may be to roll back to an earlier version of numba for now.

**Comment by aradley** [comment]
![UMAP_Error](https://user-images.githubusercontent.com/17301771/59048489-d8bc0100-887d-11e9-8fc1-61cf4089e985.png)

Similar problem that I just wanted to bring to your attention. I switched from python 2.7 to python 3, and have started getting the error in the attached image. I am still able to get coordinates and plot them, so it technically still works. But it's still disconcerting....

**Comment by lmcinnes** [comment]
I suspect the error is fine, it means it failed to manage to parallelise that function, but it still computed everything just fine.
