### ISSUE TITLE
UMAP on Windows

### ISSUE THREAD

**Issue by hlmeng** [lmcinnes/umap#225]
I installed UMAP on a 64-bit Window's machine with python 3.7.3 using "pip install umap-learn" and the installation seems good. But when I call UMAP in R, I got "Cannot find UMAP, please install through pip (e.g. pip install umap-learn)." If I run "import umap" in python, I got following error:
"numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Operands must be the same type, got (i32, i64)

File "AppData\Local\Programs\Python\Python37-32\lib\site-packages\umap\utils.py", line 129:
def make_heap(n_points, size):
    <source elided>
    """
    result = np.zeros((3, int(n_points), int(size)), dtype=np.float64)"

Thank you for the help!

**Comment by lmcinnes** [comment]
I have never seen anything quite like that before -- what version of numba are you running?

**Comment by hlmeng** [comment]
Thanks. The version of numba I am running is 0.43.1

**Comment by lmcinnes** [comment]
That is certainly recent enough. I admit to being somewhat completely baffled by this. It seems to be something in how the integer handling is working at the interface between windows, numba and numpy -- I think (but can't be sure) that the 3 is getting cast to an int32 for some reason, while ``int(n_points)`` and ``int(size)`` are getting cast to an int64. Are you comfortable doing a little light surgery on your installation of umap? Specifically opening the file ``AppData\Local\Programs\Python\Python37-32\lib\site-packages\umap\utils.py`` and making some minor edits to it? If so I can make some suggestions for things to try.

**Comment by hlmeng** [comment]
Sure. I would like to and will appreciate for any suggestion.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by lmcinnes** [comment]
Thanks for being willing to try a few things -- since I can't reproduce the issue it helps a lot! I think the easiest thing to try right now is to strip out the numba typing and see if that can work around the problem for you.

in line 109 of utils.py you should see something like:

```python
@numba.njit("f8[:, :, :](i8,i8)")
def make_heap(n_points, size):
```

you can change that to:

```python
@numba.njit()
def make_heap(n_points, size):
```

and see if that resolves the problem. If it does great -- we can potentially try to figure out the underlying issue, but at the very least that might get things working for you.

**Comment by hlmeng** [comment]
Thank you, Leland! It solved my previous problem and I have no trouble when I run "import umap" in python. But when I run umap in RStudio, I got a new problem:

> immune.combined <- RunUMAP(object = immune.combined, reduction = "pca", dims = 1:20)
Error in RunUMAP.default(object = data.use, assay = assay, n.neighbors = n.neighbors,  : 
  Cannot find UMAP, please install through pip (e.g. pip install umap-learn).

I'm pretty sure umap is installed and restarting my computer does not help. 

Any suggestion? Thank you!

**Comment by lmcinnes** [comment]
I'm afraid this one is a little bit beyond my expertise -- I am really not much of an R user. It looks like the python R is accessing is not the python that has umap installed; that could be path related, or is might be related to how R calls python. You may have to reach out the Seurat or R people for help on this bit I'm afraid.

**Comment by hlmeng** [comment]
Thanks, Leland!

**Comment by hlmeng** [comment]
The issue is solved. The problem is that I downloaded a weird version of python which caused all the problems. Using a new version of python, everything is fine and I can run UMAP from RStudio.

**Comment by lmcinnes** [comment]
Excellent, I'm glad things got worked out in the end.

**Comment by KOLANICH** [comment]
The second error is just a check in numba. They don't suppkrt 32-bit stuff. I have just removed that check and the stuff worked, though not fine:
1. utilising 1 core of CPU
2. imho the stuff should be rewritten to OpenCL because it is damn slow.

**Comment by adamgayoso** [comment]
I'm currently having this issue on Ubuntu. Numba version 0.47.0 seems to fix it, but somehow this issue came out of nowhere.

**Comment by 117999** [comment]
the very same problem came to me as well, now I have redownloaded another version of python (the latest), but it doesn't work, I cannot use UMAP on R and it still apppeared 
`Cannot find UMAP, please install through pip (e.g. pip install umap-learn)`

**Comment by lmcinnes** [comment]
I think there are potentially issues about which python R is looking at. I am not that familiar with R/Python interactions though, so I can't really help much with this one. Sorry.
