### ISSUE TITLE
FAQ slightly out of date

### ISSUE THREAD

**Issue by vicramr** [lmcinnes/umap#227]
The section of the FAQ which discusses R implementations ([here](https://umap-learn.readthedocs.io/en/latest/faq.html#is-the-support-for-the-r-language)) appears to be slightly out of date. Specifically, it implies that [umapr](https://github.com/ropenscilabs/umapr) is the preferred R wrapper for this library. But in many of the closed issues in the umapr github ([example](https://github.com/ropenscilabs/umapr/issues/23#issuecomment-402317489)), the devs point users towards [umap](https://github.com/tkonopka/umap) and [uwot](https://github.com/jlmelville/uwot) instead. The FAQ should probably be updated to address this.

I'd open a pull request myself but I'm not sure how the Read the Docs site is generated. Would I just be able to modify `doc/faq.rst`? If so I'll go ahead and create the PR.

**Comment by lmcinnes** [comment]
Yes, you just edit the rst file. Please feel free to update. I would recommend uwot as the preferred R solution at this time.

**Comment by vicramr** [comment]
Closing issue because the PR was merged.

@lmcinnes Thanks for all your great work on this project! I'll see if I can help out with any other beginner-friendly fixes.

**Comment by lmcinnes** [comment]
Thank you! I'm always happy to accept PRs if possible, and can work with people to make it easier if I can.I look forward to any other contributions you want to make.
