### ISSUE TITLE
Distributed memory umap

### ISSUE THREAD

**Issue by ghost** [lmcinnes/umap#235]
I'm looking to implement umap on an array with n = 500k and feature dimension of 80mil. This obviously implies that I would need to implement a distributed memory version of this. 

Is the memory bottleneck the nearest neighbor search?

**Comment by lmcinnes** [comment]
The nearest neighbor search is certainly the most pressing difficulty in making a distributed memory version -- I'm not sure others wouldn't rear their head once that was taken care of mind you. Is there any chance you can represent it as a sparse matrix? Are the number of non-zeros low enough that it might fit in memory?

**Comment by jrvanalstine** [comment]
There's a lot of zeros, but there's still about 400 billion nonzero entries =[

**Comment by lmcinnes** [comment]
That's certainly too large; sorry. I don't think I have any good solutions in that situation -- a distributed version of UMAP is still a fairly non-trivial series of steps away, and I don't see it in the near to medium term. Eventually such a thing is theoretically on the roadmap, but it is a long way off.

**Comment by jrvanalstine** [comment]
I think I can implement a distributed memory nearest neighbor search. Like you say though, other issues will probably rear their head.

**Comment by lmcinnes** [comment]
If you believe you can do that ... then ideally you can pass the knn_indices and knn_dists arrays into some of the internal functions, and on reflection I don't actually see why that wouldn't work -- in that it no longer needs to be distributed; you only need the 500k x ``n_neighbors`` sized pieces to fit in memory, which is likely doable (on a large memory box). If you can get the nearest neighbor search to work I can help step you through the rest of it.

**Comment by jrvanalstine** [comment]
Ya I have done this type of thing for media search engines. I agree it seems doable. 

I just need to do a bit of data infrastructure and to move a giant matrix. I think next week I can start implementing this.

**Comment by lmcinnes** [comment]
Excellent. Let me know when you reach a stage where you want help getting those results into UMAP and we can go from there.

**Comment by jrvanalstine** [comment]
Actually, I don’t think I can do this. 

The method I typically use for doing nearest neighbor on a very large media (like photos) datasets won’t work for such high dimensional features. I am not sure if there’s a known method for horizontally scaling nearest neighbor search with extremely high dimensional features. Hopefully I’m wrong. The ANN method you use mentions a mapreduce version in the paper. Do you know if this method would scale to d=80mil? Cutting planes just don’t work in such high dimensions

**Comment by lmcinnes** [comment]
It scales in data sample, bot their dimensionality, so I suspect you would have a similar issue. Sorry.

**Comment by cuccatodavide** [comment]
Hello, 
Firstly, I want to acknowledge to Leland McInnes the great contribution UMAP gives to the field of dimensionality reduction and feature extraction.

I just read about this discussion and wanted to highlight the following papers:

https://doi.org/10.1016/j.cageo.2019.02.009: They discuss different parallelization strategies for Knn with geospatial weights.

https://doi.org/10.1016/j.jpdc.2019.04.008: They propose a GPU parallel implementation of tSNE, maybe some ideas can be used

https://arxiv.org/abs/1907.03736: Another work on parallelization of queries on spatial data.

I apologize in advance if the papers are out of the scope, @ghost if you provide more details about how is your problem different from those in the papers, I can try to narrow my future researches for a solution

**Comment by jlopezpena** [comment]
This is probably not very helpful; depending on *why* you want to use umap in your dataset. If your purpose is dimensionality reduction, I don't believe any KNN method will scale well to those sizes (distributed or not).

Since you have two orders of magnitude more features than datapoints, I think it's clear you have too many of them anyway, so I would start by attempting to reduce the number of those using simpler methods, such as some linear decompositions, or at least something that can work on batches of a few datapoints at a time. I think an auto-encoder network should be able to handle those sizes.

Barring that, you might have to resort to sampling subsets of the features, with 500K datapoints is not reasonable to try and find embeddings in millions of dimensions, so you might as well pick some subsets of (say) 10k or 20K features at a time and finding embedding for those.
