### ISSUE TITLE
Random state parameter is ignored

### ISSUE THREAD

**Issue by candalfigomoro** [lmcinnes/umap#238]
Hi,

in this line:

https://github.com/lmcinnes/umap/blob/7041502068e7bc3aa28fc00a12fffa66435410dd/umap/umap_.py#L981

shouldn't it be `random_state.normal`  instead of `np.random.normal`? The random_state parameter is ignored when init is not random/spectral string.

**Comment by lmcinnes** [comment]
Yes, yes it should. Thank you!
