### ISSUE TITLE
Construct fuzzy simplicial set abort without raising exception 

### ISSUE THREAD

**Issue by artiom-zayats** [lmcinnes/umap#243]
I am running umap fit and my python program just fails without raising any exception. 
This only happens on one machine out of 3.

With exactly the same code:

This is the verbosity. 

Construct fuzzy simplicial set
0 / 11
1 / 11
2 / 11

Thank you,

**Comment by artiom-zayats** [comment]
I have digger around and found that numba is failing but for some reason, i cannot understand (i have zero knowledge in numba) 

`kernel_sig =  (array(uint64, 1d, C), array(float64, 2d, C), array(float64, 1d, C)) -> none
func_args =  ['sched', 'distances', 'val.158_arr']
num_inputs =  2
parfor_outputs =  []
parfor_redvars =  ['val.158']
num_reductions =  1
_create_shape_signature 2 1 ['sched', 'distances', 'val.158_arr'] {'val.158_arr': 1}
argument distances <class 'str'> (193, 201)
argument val.158_arr <class 'str'> (-1,)
args ['sched', 'distances', 'val.158_arr']
classes [(202,), (193, 201), (-1,)]
gu_signature =  ([('b',), ('a', 'c'), ()], [])
loop_nests =  [LoopNest(index_variable = parfor_index.378, range = (0, distances_size0.329, 1)), LoopNest(index_variable = parfor_index.379, range = (0, distances_size1.330, 1))]
loop_ranges =  [(0, Var(distances_size0.329, C:\Program Files\Python36\lib\site-packages\umap\umap_.py (87)), 1), (0, Var(distances_size1.330, C:\Program Files\Python36\lib\site-packages\umap\umap_.py (87)), 1)]
make_parallel_loop
args =  ['sched', 'distances', 'val.158_arr']
outer_sig =  (array(uint64, 1d, C), array(float64, 2d, C), array(float64, 1d, C)) none None None
loop_ranges =  [(0, Var(distances_size0.329, C:\Program Files\Python36\lib\site-packages\umap\umap_.py (87)), 1), (0, Var(distances_size1.330, C:\Program Files\Python36\lib\site-packages\umap\umap_.py (87)), 1)]
expr_args ['sched', 'distances', 'val.158_arr']
expr_arg_types [array(float64, 2d, C), array(float64, 1d, C)]
gu_signature ([('b',), ('a', 'c'), ()], [])
parallel function =  .kernel.2144049127424 CompileResult(typing_context=<numba.typing.context.Context object at 0x000001F3312F6048>, target_context=<numba.targets.cpu.CPUContext object at 0x000001F339A1F048>, entry_point=<built-in method __numba_parfor_gufunc__0x7fffffe0cc751f23 of _dynfunc._Closure object at 0x000001F338D02320>, typing_error=None, type_annotation=<numba.annotations.type_annotations.TypeAnnotation object at 0x000001F339A1F198>, signature=(array(uint64, 1d, C), array(float64, 2d, C), array(float64, 1d, C)) -> none, objectmode=False, lifted=(), fndesc=<function descriptor '__numba_parfor_gufunc__0x7fffffe0cc751f23$39'>, interpmode=False, library=<Library '__numba_parfor_gufunc__0x7fffffe0cc751f23' at 0x1f339a0eac8>, call_helper=None, environment=<numba.lowering.Environment object at 0x000001F339A69AF8>, metadata={'parfor_diagnostics': ParforDiagnostics})
call_parallel_gufunc loop_ranges[0] =  i64 0 %".13925" = load i64, i64* %"distances_size0.329" i64 1
call_parallel_gufunc loop_ranges[1] =  i64 0 %".13928" = load i64, i64* %"distances_size1.330" i64 1
Parfor has potentially negative start False
var = distances gu_sig = ('a', 'c') type = array(float64, 2d, C) i = 0
var =  distances  type =  array(float64, 2d, C)
dim_sym =  a , i =  0
var =  distances  type =  array(float64, 2d, C)
dim_sym =  c , i =  1
var = val.158_arr gu_sig = () type = array(float64, 1d, C) i = 1`


I have recivedthis output if I do : 

`numba.config.DEBUG_ARRAY_OPT = 1`

**Comment by lmcinnes** [comment]
That is disconcerting, but I am honestly not sure what the issue could possibly be, especially if it is restricted to a particular machine. I wish I could be more help, but I don't have any insight into this.

**Comment by mikeriedel** [comment]
Hi, I'm the person who experienced the issue that Artiom raised. I have been unable to isolate what on my machine is different. I have found some information you may be able to make better use of.

I was able to trace the crash to `smooth_knn_dist`, and the use of numba with fastmath=true

The exception I had was : 
`Windows fatal exception: access violation`

My test case is : 
`import numpy as np`
`import umap`
`np_features = np.random.rand(100, 100)`
`sigmas, rhos = umap.umap_.smooth_knn_dist(np_features, 20)`

I tried turning off fastmath (line 47 of umap_.py) and the problem went away.
`@numba.njit(parallel=True, fastmath=False)`

**Comment by mikeriedel** [comment]
Ok I've tracked down the problem to line 98 in umap_.py.
`non_zero_dists = ith_distances**[ith_distances > 0.0]**`

I'm not a python programmer, but that looks questionable. Commenting out the array index causes the crash to go away.
`non_zero_dists = ith_distances`

Are you trying to create an array of only the values that are non zero?

**Comment by lmcinnes** [comment]
Yes, and that is the valid numpy code to do it, so I'm not quite sure why this is an issue (and it doesn't seem to cause issues for others, so there must be more at work here). Is there somethign specific about your machine or software configuration that might cause such irregular behaviour?

**Comment by artiom-zayats** [comment]
Closing an issue due, to fact that numba update to 44.0 solved the issue temporary on python 3.6.5

Thank you,
