### ISSUE TITLE
word embedding aggregation through UMAP?

### ISSUE THREAD

**Issue by alonsopg** [lmcinnes/umap#264]
Is it possible to aggregate, merge or fuse two different word embedding representations with umap? For instance, consider:
```
word_embedding_1 \ ______  |UMAP|________ then concat or apply any other operation?
word_embedding_2 /
```

As far as I understand this is not possible out of the box, you should need to project the two different spaces into a similar space. For example by using PCA in theory you could learn a projection from k dimensions to k ′ dimensions that removes the redundancy that comes from concatenating multiple sources of embedding. Is it possible to do this with umap?, then how can I do it properly

**Comment by lmcinnes** [comment]
I'm not exactly clear on what you want as the outcome of this. Are these word vectors over different vocabularies? Or are they different sets of word vectors over the same vocabulary?
