### ISSUE TITLE
UMAP codes and scripts

### ISSUE THREAD

**Issue by NDUFB11** [lmcinnes/umap#271]
Hello everyone, 

I am new to coding and scripting with python and I am looking for a guide to make UMAP graph.
I know there is lots of staff online but  I wish to find a tutorial that contains examples file
with step by step codes for making the graph. 
Or, do you have any suggestions about where/how to start? 

Thank you

**Comment by lmcinnes** [comment]
I would recommend looking at the [documentation](https://umap-learn.readthedocs.io/en/latest/), and alternatively at the [code in the examples directory](https://github.com/lmcinnes/umap/tree/master/examples).
