### ISSUE TITLE
in concatenated files, how to see that each data set is separated or overlapping

### ISSUE THREAD

**Issue by hihyein99** [lmcinnes/umap#274]
hi, I am doing my clustering with 4 concatenated hdf5 files. I am doing the scanpy.pl.umap for the concatenated data and color the each genes that I want to see. Is there any way that I can use scanpy.pl.umap function to see each file's ID?
Thank you!

what I did so far:
filenames = ['filename1.h5','filename2.h5','filename3.h5','filename4.h5']
adatas = [sc.read_10x_h5(filename, gex_only = True) for filename in filenames]
adata = adatas[0].concatenate(adatas[1:])
.......
(did basic filtering, logarithmizing,..., until sc.tl.umap(adata))
.......
sc.pl.umap(adata, color=['Cd4','Foxp3','Cd19'])

and now I want to see the filename1.h5's sc.pl.umap(adata, color=['Cd4','Foxp3','Cd19']), not adata which is concatenated

**Comment by adelejackson** [comment]
I suspect you have the wrong package. This is umap-learn, a package for dimension reduction, installed using PIP by ```pip install umap-learn```. I think you should move this issue to the [scanpy repository](https://github.com/theislab/scanpy).

**Comment by sleighsoft** [comment]
I don't see what this has to do with this project.
