### ISSUE TITLE
fuzzy_simplical_set has more than n_neighbors

### ISSUE THREAD

**Issue by sleighsoft** [lmcinnes/umap#275]
In the below example setting `n_neighbors=3` on a `[5,2]` dataset will yield a fuzzy simplical set where some points have only 2 neighbors and others have 4. Am I interpreting the data structure incorrectly or is this a bug?

```python
import warnings
warnings.filterwarnings("ignore")

import umap
import numpy as np
from sklearn.metrics import pairwise_distances

n_neighbors = 3
random_state = np.random.seed()
metric = 'euclidean'

def fuzzy(data):
    d_mat = pairwise_distances(data, metric=metric)

    print(d_mat)

    fuzzy_set = umap.umap_.fuzzy_simplicial_set(
        d_mat,
        n_neighbors,
        random_state,
        'precomputed',
        metric_kwds={},
        knn_indices=None,
        knn_dists=None,
        angular=False,
        set_op_mix_ratio=1.0,
        local_connectivity=1.0,
        verbose=False,
    )

    print(fuzzy_set)
    return fuzzy_set

data = np.array([
    [1., 0.],
    [2., 0.],
    [4., 0.],
    [8., 0.],
    [13., 0.],
])

print('Data:', data)
data_fuzzy = fuzzy(data)
```
This will print
```
  (0, 1)        1.0
  (0, 2)        0.827749554284373
  (1, 0)        1.0
  (1, 2)        1.0
  (2, 0)        0.827749554284373
  (2, 1)        1.0
  (2, 3)        1.0
  (2, 4)        0.5849693436435967
  (3, 2)        1.0
  (3, 4)        1.0
  (4, 2)        0.5849693436435967
  (4, 3)        1.0
```

Now `Point 2` has 3 neighbors but it should have only 2. The additional neighbor is introduced here:
https://github.com/lmcinnes/umap/blob/74a7b3e75362fa6eb3318a292e5364c12c43df62/umap/umap_.py#L490

If you don't mind could you explain what the code at 490 does?

**Edit:**
Ah, that is probably the union of the edges `a + b - a * b`.
But that is also the code part that introduces the additional edges.

**Another issue:**
https://github.com/lmcinnes/umap/blob/74a7b3e75362fa6eb3318a292e5364c12c43df62/umap/umap_.py#L340

If I understand it correctly this is meant to do the following (taken from umap readthedocs):
```
For the practical problem we are working with, where we only have a finite approximation of the 
manifold, this means that no point should be completely isolated – it should connect to at least one 
other point. In terms of fuzzy open sets what this amounts to is that we should have complete 
confidence that the open set extends as far as the closest neighbor of each point.
```
However, in the case above where the distances for the first two points are
```
distances = 
[[ 0.  1.  3.  7. 12.]
 [ 1.  0.  2.  6. 11.]
```
`distances[1,0] == distances[1,2] == distances[0,1]` even though `[1,2]` is not the closest neighbor of `[1]`.

**Comment by leminhhiep20691** [comment]
File: System/data/app/com.duy.c.cpp.compiler-PwBeGx6b4K3LiQfaBi5HeQ==/lib/arm/libnative-loader.so
MD5: 4d:f7:5f:1b:30:81:29:5c:0e:6e:a2:29:04:7a:65:96
SHA1: 17:6f:d3:6c:b0:f5:85:03:ae:08:16:c3:a3:83:9b:b5:45:08:d4:32
SHA256: 87:7b:b7:07:52:b5:fb:e7:14:de:03:90:11:6a:76:b7:2b:10:43:e2:8b:52:1e:3d:cd:ac:fe:be:22:58:ca:04

**Comment by sleighsoft** [comment]
@leminhhiep20691 Would you mind remove your "strange" comments?

**Comment by lmcinnes** [comment]
The fuzzy simplicial set is not the KNN graph; that's part of the point of the operations involved. Instead it unions together all the local KNN graphs. This means that in the fuzzy simplciial set you can end up with more neighbors and different membership strengths than you would get from a pure KNN graph.

**Comment by sleighsoft** [comment]
Thanks, that clarifies things alot :)

**Comment by sleighsoft** [comment]
@lmcinnes I know I already closed this but I have a question regarding the output of `fuzzy_simplical_set`.

Given a number of points, e.g. `[1,1], [1,2], [2,1]` and `n_neighbors`. We can compute the `fuzzy_simplical_set` for these points.
I am now wondering if I add another point, let's say `[3,3]`, to my inital set of points and recompute the `fuzzy_simplical_set` is there some way to quantify the difference between the two obtained `fuzzy_simplical_sets`? Specifially does it make a difference if I add a point that is closer to one or more initial points vs. a point that is an outlier, like `[10, 10]`.

I would really appreciate your thoughts on this :)
