### ISSUE TITLE
Error in py_call_impl(callable, dots$args, dots$keywords) :   AttributeError: eliminate_zeros not found

### ISSUE THREAD

**Issue by lay-lei** [lmcinnes/umap#277]
hello, I use pip3 install umap-learn and want to use it in R, but I get error when it running:
left_lung <- RunUMAP(left_lung, dims = 1:15)
UMAP(a=None, angular_rp_forest=False, b=None, init='spectral',
   learning_rate=1.0, local_connectivity=1, metric='correlation',
   metric_kwds=None, min_dist=0.3, n_components=2, n_epochs=None,
   n_neighbors=30, negative_sample_rate=5, random_state=None,
   repulsion_strength=1.0, set_op_mix_ratio=1.0, spread=1.0,
   target_metric='categorical', target_metric_kwds=None,
   target_n_neighbors=-1, target_weight=0.5, transform_queue_size=4.0,
   transform_seed=42, verbose=True)
Construct fuzzy simplicial set
         0  /  13
         1  /  13
         2  /  13
Error in py_call_impl(callable, dots$args, dots$keywords) :
  AttributeError: eliminate_zeros not found

Detailed traceback:
  File "/usr/local/lib/python2.7/dist-packages/umap/umap_.py", line 1564, in fit_transform
    self.fit(X, y)
  File "/usr/local/lib/python2.7/dist-packages/umap/umap_.py", line 1422, in fit
    self.verbose,
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/base.py", line 525, in __getattr__
    raise AttributeError(attr + " not found")

I want to know how to deal with this problem,thank you!

**Comment by lmcinnes** [comment]
I believe you need a newer version of scipy -- I'm not sure why that didn't get installed/updated when you installed umap.

**Comment by sleighsoft** [comment]
This definitely works
```
conda create -n umap python=3.7.3
conda activate umap
pip install umap-learn 
```
