### ISSUE TITLE
Typing Error, on Jupyter, Anaconda, Windows 10, Python 3

### ISSUE THREAD

**Issue by MekeSakensky** [lmcinnes/umap#290]
Hi,
tried on MNIST
and tried all versions of installation,
Anaconda constantly throws following error

![image](https://user-images.githubusercontent.com/48585802/64311199-058acc00-cfc5-11e9-9748-a621ceafaafb.png)

**Comment by MekeSakensky** [comment]
would really appreciate if someone could help, trying to apply this library for ongoing project.

**Comment by jlmelville** [comment]
Did you definitely install `umap-learn`? There's a `umap` package, which is not what you want.

**Comment by MekeSakensky** [comment]
Hi, I used "conda install -c conda-forge umap-learn" command to install umap-learn on Anaconda Prompt, Windows 8, Python 3, this is the output:
![image](https://user-images.githubusercontent.com/48585802/64349072-13b60800-d018-11e9-91ee-4dca38d0a2db.png)

**Comment by MekeSakensky** [comment]
there is actually no problem when I start working on Jupyter, namely,
when I write:
![image](https://user-images.githubusercontent.com/48585802/64349216-5ed01b00-d018-11e9-90e5-9b4e35d27de4.png)

**Comment by MekeSakensky** [comment]
interestingly, after I wrote following
![image](https://user-images.githubusercontent.com/48585802/64350246-2d584f00-d01a-11e9-934e-d4c7e052b74e.png)

**Comment by MekeSakensky** [comment]
it started throwing following error:
![image](https://user-images.githubusercontent.com/48585802/64350398-65f82880-d01a-11e9-98ad-1f4e0f924368.png)

**Comment by MekeSakensky** [comment]
continuation:
![image](https://user-images.githubusercontent.com/48585802/64350500-9049e600-d01a-11e9-812f-a25389354a8e.png)
![image](https://user-images.githubusercontent.com/48585802/64350531-9f309880-d01a-11e9-8caf-3563acbfa777.png)

**Comment by MekeSakensky** [comment]
it started throwing following error:

---------------------------------------------------------------------------
TypingError                               Traceback (most recent call last)
<ipython-input-19-ad285241c8e0> in <module>()
----> 1 embedding = reducer.fit_transform(digits.data)

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in fit_transform(self, X, y)
   1823             Embedding of the training data in low-dimensional space.
   1824         """
-> 1825         self.fit(X, y)
   1826         return self.embedding_
   1827 

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in fit(self, X, y)
   1623                 self.set_op_mix_ratio,
   1624                 self.local_connectivity,
-> 1625                 self.verbose,
   1626             )
   1627         else:

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in fuzzy_simplicial_set(X, n_neighbors, random_state, metric, metric_kwds, knn_indices, knn_dists, angular, set_op_mix_ratio, local_connectivity, verbose)
    557             angular,
    558             random_state,
--> 559             verbose=verbose,
    560         )
    561 

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, random_state, verbose)
    230         # Note that this does not support sparse distance matrices yet ...
    231         # Compute indices of n nearest neighbors
--> 232         knn_indices = fast_knn_indices(X, n_neighbors)
    233         # Compute the nearest neighbor distances
    234         #   (equivalent to np.sort(X)[:,:n_neighbors])

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345         except errors.UnsupportedError as e:
    346             # Something unsupported is present in the user code, add help info

C:\ProgramData\Anaconda3\lib\site-packages\numba\six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed at nopython (Preprocessing for parfors)
Invalid usage of Function(<function argsort at 0x000002C4C48E2A60>) with parameters (array(float32, 1d, C), const('quicksort'))
 * parameterized
In definition 0:
    AssertionError: 
    raised from C:\ProgramData\Anaconda3\lib\site-packages\numba\typing\arraydecl.py:415
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by MekeSakensky** [comment]
newbie in UMAP, where is my Typing Error here?

**Comment by sleighsoft** [comment]
Can you please share you code instead of screenshots

**Comment by MekeSakensky** [comment]
Thank you for your respond here is my code which is now identical with yours:

import umap

from sklearn.datasets import load_digits

digits = load_digits()

reducer = umap.UMAP(n_neighbors=5, min_dist=0.3, metric='cosine')

embedding = reducer.fit_transform(digits.data)

**Comment by MekeSakensky** [comment]
and Jupyter throws following error:

TypingError                               Traceback (most recent call last)
<ipython-input-26-8e7a7502b522> in <module>()
      7 reducer = umap.UMAP(n_neighbors=5, min_dist=0.3, metric='cosine')
      8 
----> 9 embedding = reducer.fit_transform(digits.data)

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in fit_transform(self, X, y)
   1823             Embedding of the training data in low-dimensional space.
   1824         """
-> 1825         self.fit(X, y)
   1826         return self.embedding_
   1827 

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in fit(self, X, y)
   1623                 self.set_op_mix_ratio,
   1624                 self.local_connectivity,
-> 1625                 self.verbose,
   1626             )
   1627         else:

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in fuzzy_simplicial_set(X, n_neighbors, random_state, metric, metric_kwds, knn_indices, knn_dists, angular, set_op_mix_ratio, local_connectivity, verbose)
    557             angular,
    558             random_state,
--> 559             verbose=verbose,
    560         )
    561 

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, random_state, verbose)
    230         # Note that this does not support sparse distance matrices yet ...
    231         # Compute indices of n nearest neighbors
--> 232         knn_indices = fast_knn_indices(X, n_neighbors)
    233         # Compute the nearest neighbor distances
    234         #   (equivalent to np.sort(X)[:,:n_neighbors])

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345         except errors.UnsupportedError as e:
    346             # Something unsupported is present in the user code, add help info

C:\ProgramData\Anaconda3\lib\site-packages\numba\six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed at nopython (Preprocessing for parfors)
Invalid usage of Function(<function argsort at 0x000002C4C48E2A60>) with parameters (array(float32, 1d, C), const('quicksort'))
 * parameterized
In definition 0:
    AssertionError: 
    raised from C:\ProgramData\Anaconda3\lib\site-packages\numba\typing\arraydecl.py:415
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by sleighsoft** [comment]
Then try creating a new conda environment.

```
conda create -n umap python=3.7.3
conda activate umap
pip install umap-learn jupyter
```

And try again

**Comment by sleighsoft** [comment]
@MekeSakensky Does it work?

**Comment by MekeSakensky** [comment]
Thank you very much for your respond,
still installing.

**Comment by MekeSakensky** [comment]
Mean while just curious about how you guys figure out and manage such kind of installation problems? Are there any sources or fundamental studies and books on this subject?

**Comment by MekeSakensky** [comment]
It looks like I got same error for the same code

**Comment by MekeSakensky** [comment]
import umap

from sklearn.datasets import load_digits

digits = load_digits()

reducer = umap.UMAP(n_neighbors=5, min_dist=0.3, metric='cosine')

embedding = reducer.fit_transform(digits.data)

**Comment by MekeSakensky** [comment]
will it make difference if I don't open Anaconda Prompt and Anaconda Navigator as an administrator?

**Comment by MekeSakensky** [comment]
plz, see the error below

**Comment by MekeSakensky** [comment]
TypingError                               Traceback (most recent call last)
<ipython-input-1-8e7a7502b522> in <module>()
      7 reducer = umap.UMAP(n_neighbors=5, min_dist=0.3, metric='cosine')
      8 
----> 9 embedding = reducer.fit_transform(digits.data)

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in fit_transform(self, X, y)
   1823             Embedding of the training data in low-dimensional space.
   1824         """
-> 1825         self.fit(X, y)
   1826         return self.embedding_
   1827 

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in fit(self, X, y)
   1623                 self.set_op_mix_ratio,
   1624                 self.local_connectivity,
-> 1625                 self.verbose,
   1626             )
   1627         else:

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in fuzzy_simplicial_set(X, n_neighbors, random_state, metric, metric_kwds, knn_indices, knn_dists, angular, set_op_mix_ratio, local_connectivity, verbose)
    557             angular,
    558             random_state,
--> 559             verbose=verbose,
    560         )
    561 

~\AppData\Roaming\Python\Python36\site-packages\umap_learn-0.3.10-py3.6.egg\umap\umap_.py in nearest_neighbors(X, n_neighbors, metric, metric_kwds, angular, random_state, verbose)
    230         # Note that this does not support sparse distance matrices yet ...
    231         # Compute indices of n nearest neighbors
--> 232         knn_indices = fast_knn_indices(X, n_neighbors)
    233         # Compute the nearest neighbor distances
    234         #   (equivalent to np.sort(X)[:,:n_neighbors])

C:\ProgramData\Anaconda3\lib\site-packages\numba\dispatcher.py in _compile_for_args(self, *args, **kws)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345         except errors.UnsupportedError as e:
    346             # Something unsupported is present in the user code, add help info

C:\ProgramData\Anaconda3\lib\site-packages\numba\six.py in reraise(tp, value, tb)
    656             value = tp()
    657         if value.__traceback__ is not tb:
--> 658             raise value.with_traceback(tb)
    659         raise value
    660 

TypingError: Failed at nopython (Preprocessing for parfors)
Invalid usage of Function(<function argsort at 0x00000162A5125A60>) with parameters (array(float32, 1d, C), const('quicksort'))
 * parameterized
In definition 0:
    AssertionError: 
    raised from C:\ProgramData\Anaconda3\lib\site-packages\numba\typing\arraydecl.py:415
This is not usually a problem with Numba itself but instead often caused by
the use of unsupported features or an issue in resolving types.

To see Python/NumPy features supported by the latest release of Numba visit:
http://numba.pydata.org/numba-doc/dev/reference/pysupported.html
and
http://numba.pydata.org/numba-doc/dev/reference/numpysupported.html

For more information about typing errors and how to debug them visit:
http://numba.pydata.org/numba-doc/latest/user/troubleshoot.html#my-code-doesn-t-compile

If you think your code should work with Numba, please report the error message
and traceback, along with a minimal reproducer at:
https://github.com/numba/numba/issues/new

**Comment by MekeSakensky** [comment]
Someone help me with this  error

**Comment by MekeSakensky** [comment]
Or can you suggest any  alternative for UMAP library besides t-SNE?

**Comment by lmcinnes** [comment]
It seems like the recently added fast_knn_indices is causing problems here. Oddly this was not an issue in testing, so it seems somewhat unique to your system. I'm honestly not sure what the solution is.

**Comment by sleighsoft** [comment]
I am honestly at a loss. I have tested in on both a recent windows 10 machine as well as a rather old suse linux and it works with conda as described above.

**Comment by sleighsoft** [comment]
Given the paths in the error message I assume @MekeSakensky  did not setup his conda correctly

**Comment by MekeSakensky** [comment]
@sleighsoft how to setup conda correctly? I recently reinstalled Anaconda, could you write here how to fix conda problem step by step if you think it's a case?

**Comment by sleighsoft** [comment]
Please read the conda documentation for this.

I personally use miniconda https://docs.conda.io/en/latest/miniconda.html

And Powershell Core (terminal on windows): https://github.com/PowerShell/PowerShell
You do not need powershell core to make it work.

I will close this as not being related to UMAP in general.

**Comment by lmcinnes** [comment]
There seems to be an issue with python 3.5; if you can upgrade to python 3.6 or newer that would potentially resolve the issue for you.
