### ISSUE TITLE
Sudden outlier

### ISSUE THREAD

**Issue by Yorko** [lmcinnes/umap#3]
I've quickly tested [Multicore-TSNE](https://github.com/DmitryUlyanov/Multicore-TSNE) and umap on the telecom churn dataset. 
Here is the [notebook](http://nbviewer.jupyter.org/github/Yorko/ipython_demonstrations/blob/master/umap_telecom_churn.ipynb). The dataset is available in the very [same repository](https://github.com/Yorko/ipython_demonstrations). 

Looks like umap suffered from a sudden outlier which hadn't affected t-SNE. 

I haven't played with umap hyperparameters but maybe the example will be useful.

**Comment by lmcinnes** [comment]
Thanks. As evidenced by issue #2 the current experimental code is not robust against some corner cases. I working to find and fix those now, and this will certainly be highly beneficial in understanding where and how I can make the code and algorithm more robust.

**Comment by lmcinnes** [comment]
You may also wish to try increasing the ``spread`` parameter to alleviate this. The default is 1.0, values more like 2.0 or higher may help to reduce the effect of such outliers.

**Comment by lmcinnes** [comment]
I just checked in some code that should help with this problem. See if you can pull from the latest master and rebuild and let me know if that helps. Thanks!

**Comment by sleighsoft** [comment]
Did this get resolved? Can the issue be closed?

**Comment by Yorko** [comment]
Yes, thanks!
