### ISSUE TITLE
Does UMAP1 captures more variance than UMAP2?

### ISSUE THREAD

**Issue by danshu** [lmcinnes/umap#301]
Hi,

I'm using UMAP for analyzing some single cell RNA-seq data. In practice, I usually find out that UMAP1 separates cells with more biological distances.  In other words,  if there are two divergent groups of cells, they will usually be separated by UMAP1 instead of UMAP2. However, unlike PCA, UMAP seems doesn't seem to have such a property. Any possible explanations?

Best,
Danshu

**Comment by lmcinnes** [comment]
The axes in UMAP do not have any inherent interpretable meaning, so it is a little surprising if a specific direction in terms of those axes is doing such a thing. It is certainly possible to UMAP to make notable discriminative separations between things, but it is less common that these consistently align with the specific axes.

**Comment by danshu** [comment]
Thanks!
