### ISSUE TITLE
Problem in using umap.plot

### ISSUE THREAD

**Issue by Zafiirah13** [lmcinnes/umap#305]
Hi,

I'm trying to use umap.plot following the instruction from this [umap-plotting](https://umap-learn.readthedocs.io/en/0.4dev/plotting.html) but I am unsuccesful. I am getting this error:

`import umap.plot`

ImportError                               Traceback (most recent call last)
<ipython-input-7-ce12e43d9970> in <module>()
----> 1 import umap.plot

ImportError: No module named 'umap.plot'

I have installed all dependencies mentioned in the link above but I'm still getting the same error.
Any help will be useful, thanks.

**Comment by lmcinnes** [comment]
The ``umap.plot`` package is only available as part of the 0.4dev branch right now. That means the only way to get it is to check out that branch from github and build and install it yourself. If you are installing with pip on conda it will not be available at this time. Hopefully soon 0.4 will actually be released.

**Comment by Zafiirah13** [comment]
Thank you for your prompt reply. Installing the 0.4dev manually solve the issue.

**Comment by qo4on** [comment]
How did you install 0.4dev? I tried this in Colab but still see the message `No module named 'umap.plot'`

```
!git clone -q --single-branch --branch 0.4dev https://github.com/lmcinnes/umap.git > /dev/null
!pip install datashader -q
!pip install "holoviews[recommended]" -q
%cd umap
!python setup.py -q install
%cd ..
import umap.plot
```

**Comment by Schmidtbit** [comment]
I have umap-learn 0.4.0rc3 installed and I still get the same error. 

I  cloned the dev repo
installed the requirements 
and installed the package

I still get `ModuleNotFoundError: No module named 'umap.plot'`

**Comment by lmcinnes** [comment]
There must be some installation issues; old versions can potentially cause conflicts if they are kicking around somewhere. If you are using conda try creating a new clean environment and installing into that perhaps.

**Comment by marcegl** [comment]
Hice una pequeña guía, https://mbojao.wordpress.com/2020/04/03/instalar-umap-en-environment-conda-y-windows-10/.

PD: esta en español.

**Comment by rahulbhadani** [comment]
For me this worked:
```
pip install umap-learn[plot]
```
