### ISSUE TITLE
Setting numba threading layer triggers other numba bug

### ISSUE THREAD

**Issue by ivirshup** [lmcinnes/umap#306]
Setting the default threading layer here:

https://github.com/lmcinnes/umap/blob/c61cdfe124ff570ba69a0bc7cdb024ae941531ee/umap/__init__.py#L3-L6

Causes the workaround of installing `tbb` for this (https://github.com/numba/numba/issues/4484) numba parallelism bug not to work. 

It's a little unclear to me if the original issue is resolved. If so, could these lines just get removed?

**Comment by sleighsoft** [comment]
Good catch! That is something that should be removed from 0.4-dev once tbb is the standard.

**Comment by sleighsoft** [comment]
Will be resolved in 0.4
