### ISSUE TITLE
Dead kernel when fitting UMAP

### ISSUE THREAD

**Issue by ydennisy** [lmcinnes/umap#309]
Hi,

I have installed UMAP, when I try and run it in my notebook I do not get any errors, but rather a dead kernel.

The terminal in which I have started the notebook has the following error:

```
Assertion failed: (PassInf && "Expected all immutable passes to be initialized"), function addImmutablePass, file /Users/buildbot/miniconda3/conda-bld/llvmdev_1556270736866/work/lib/IR/LegacyPassManager.cpp, line 849.
```

Any ideas?

**EDIT**:

So I managed to get it to work by executing each of the following lines separately:
```
import umap
reducer = umap.UMAP()
embedding = reducer.fit_transform(X)
```

However when they are in a single notebook block they kill the kernel... how odd!!!

**Comment by sleighsoft** [comment]
I have done this multiple times and have never encountered this problem. Maybe you could try with a fresh environment.

**Comment by lmcinnes** [comment]
That is very odd -- I've never seen anything quite like this. Unfortunately given that the code executed separately works this means it likely relates to interesting interactions between jupyter, numba, and llvm that go beyond the scope of anything I can address without a consistent reproducer on my end. Hopefully you can work with the workaround you found for now.

**Comment by ydennisy** [comment]
Yeah all good for me.

Feel free to close this if you wish.

**Comment by NimmiW** [comment]
I am still getting this issue. This is is fixed already?

**Comment by lmcinnes** [comment]
Not that I'm aware of -- it is not reproducible for me, so I can't really track it down. If it is consistently reproducible on your setup I would welcome any finer detailed triage you can provide.

**Comment by ciberger** [comment]
@NimmiW, try reinstalling or update to _umap-learn_ version 0.4.2. That fixed it for me.
