### ISSUE TITLE
Warning message: failed creating initial embedding; using random embedding instead

### ISSUE THREAD

**Issue by GMFranceschini** [lmcinnes/umap#320]
Hello, 
I am trying to perform umap on a dataset of ~5000 observations and 20 features (selected with previous PCA), using the R implementation provided by the `umap` package.

When computing UMAP I get this warning message: `Warning message:
failed to create initial embedding; using random embedding insteadx`.
So the spectral initialization is not working.
How should I tackle this sort of instability?

Plots are quite different from each other in different runs, and I would like something reproducible and possibly robust. I imagine this could be due to my data, but I wasn't able to find help about that in the UMAP documentation.

Feel free to close this issue if it's not appropriate for this repo,
Thank you for your kind attention

**Comment by tkonopka** [comment]
Hi,

This issue seems to be connected with another repo, tkonopka/umap, which is based on the work here but may have peculiarities and bugs of its own. 

To use this repo here through the R interface, you can try executing the umap transformation with an additional argument `method="umap-learn"`. It'll be interesting to see if the issue persists. 

To troubleshoot the R-only approach, this discussion should probably move to the other repo. We can investigate together. Can you share the dataset that you are using?

**Comment by lmcinnes** [comment]
Essentially this would mean that the internal topological representation (a graph) does not have a good spectral gap in the Laplacian; or that the spectral embedding/eigenvector solver is not working correctly on your system. In the first case that means that potentially you may want to add a small amount of noise or jitter to your data to hopefully nudge it out of this odd situation. In the second case you probably want to look at how the ARPACK components are installed.

**Comment by GMFranceschini** [comment]
Thank to both of you for your reply.
Unfortunately, I can't share the dataset. 

However, changing UMAP implementation from package `umap` to `uwot::umap` solved the issue. As long as I can tell, I explicitly specified the same parameters that raised the warning previously, so it seems to be implementation-dependent somehow.

Thank you for the theoretical explanation, this was something I wanted to understand even after solving the issue. I'll close the issue.

**Comment by tkonopka** [comment]
I like the approach to experiment with the number of neighbors. Along similar lines, another experiment might be to change the input data... The 20 features in this dataset come from PCA preprocessing. Using a couple more or fewer features from that preprocessing stage should not affect the interpretation of the workflow, but might introduce that "noise or jitter" to avoid numerical problems. Not sure if this would work in practice, but it is quick to test.
