### ISSUE TITLE
AttributeError: module 'umap' has no attribute 'plot'

### ISSUE THREAD

**Issue by ssimontacchi** [lmcinnes/umap#321]
I am having a hard time installing umap.plot. My goal is to make the interactive plot [here](https://umap-learn.readthedocs.io/en/0.4dev/plotting.html). 

I am using iOS Mojave 10.14.5, umap-learn 0.3.10, Python 3.7.4. 

Thanks!

**Comment by sleighsoft** [comment]
You require the 0.4-dev version located here: https://github.com/lmcinnes/umap/tree/0.4dev

Simply clone and install or install with pip from repo: https://stackoverflow.com/questions/20101834/pip-install-from-git-repo-branch

**Comment by ssimontacchi** [comment]
Thank you!!

**Comment by zaloogarcia** [comment]
I installed with pip from the repo You suggested and I still have the same problem.
getting `umap-learn==0.4.0rc1` version

**Comment by hangletn** [comment]
Hello, I tried the way you suggested but received the following error `fatal: repository 'https://github.com/lmcinnes/umap/tree/0.4dev/' not found` Do you have any idea about what might happen? Thanks!

**Comment by lmcinnes** [comment]
No -- that seems very odd. On good news that branch has been merged into master, so you can just clone the repository and install that if you wish.

**Comment by hangletn** [comment]
Oh thank you it works now!

**Comment by jamesruffle** [comment]
Hi all,

I have installed from the latest git release, but get the below error. Would be grateful for clarification.

import umap.plot

 ImportError                               Traceback (most recent call last)
<ipython-input-113-cfb6b819bd27> in <module>
      1 import umap.nndescent
----> 2 import umap.plot

/usr/local/lib/python3.6/dist-packages/umap/plot.py in <module>
     22 from matplotlib.patches import Patch
     23 
---> 24 from umap.nndescent import initialise_search, initialized_nnd_search
     25 from umap.utils import deheap_sort, submatrix
     26 

ImportError: cannot import name 'initialized_nnd_search'

**Comment by FaitAccompli** [comment]
> Oh thank you it works now!


Hi! @hangletn , may I ask how you were able to fix the fatal:repository error? I'm having the same issue even though I'm trying to pip install the master branch already. Thanks!

**Comment by FaitAccompli** [comment]
Hi I was able to successfully build umap-learn from the master branch. However, I am getting this error when importing umap.plot.

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-99-bacc05ba6367> in <module>
     17 
     18 import umap
---> 19 import umap.plot
     20 
     21 # silence NumbaPerformanceWarning

~\Anaconda3\lib\site-packages\umap\plot.py in <module>
     11 import matplotlib.cm
     12 
---> 13 import bokeh.plotting as bpl
     14 import bokeh.transform as btr
     15 import holoviews as hv

~\Anaconda3\lib\site-packages\bokeh\plotting\__init__.py in <module>
     75 from ..models.layouts import Row, Column; Row, Column
     76 
---> 77 from ..io import curdoc; curdoc
     78 from ..io import output_file; output_file
     79 from ..io import output_notebook; output_notebook

~\Anaconda3\lib\site-packages\bokeh\io\__init__.py in <module>
     49 from .doc import curdoc
     50 
---> 51 from .export import export_png
     52 from .export import export_svgs
     53 

~\Anaconda3\lib\site-packages\bokeh\io\export.py in <module>
     32 
     33 # Bokeh imports
---> 34 from ..embed import file_html
     35 from ..resources import INLINE
     36 from ..util.dependencies import import_required

~\Anaconda3\lib\site-packages\bokeh\embed\__init__.py in <module>
     52 #-----------------------------------------------------------------------------
     53 
---> 54 from .server import server_document
     55 from .server import server_session
     56 

~\Anaconda3\lib\site-packages\bokeh\embed\server.py in <module>
     28 # Bokeh imports
     29 from ..core.templates import AUTOLOAD_TAG, FILE
---> 30 from ..resources import DEFAULT_SERVER_HTTP_URL
     31 from ..util.serialization import make_id
     32 from ..util.string import encode_utf8, format_docstring

~\Anaconda3\lib\site-packages\bokeh\resources.py in <module>
    512 #-----------------------------------------------------------------------------
    513 
--> 514 CDN = Resources(mode="cdn")
    515 
    516 INLINE = Resources(mode="inline")

~\Anaconda3\lib\site-packages\bokeh\resources.py in __init__(***failed resolving arguments***)
     81         self.mode = settings.resources(mode);           del mode
     82         self.root_dir = settings.rootdir(root_dir);     del root_dir
---> 83         self.version = settings.version(version);       del version
     84         self.minified = settings.minified(minified);    del minified
     85         self.log_level = settings.log_level(log_level); del log_level

AttributeError: 'Settings' object has no attribute 'version'

**Comment by lmcinnes** [comment]
It seems like bokeh is failing to load; I am not sure why. See in you can do
```python
import bokeh.plotting as bpl
```
alone, and if not then that is defnitely the problem and you may have to check with the bokeh people.

**Comment by FaitAccompli** [comment]
Hi Leland McInnes! Nice to hear from you. I was able to solve the problem
by using a specific version of umap Thank you and cheers!

**Comment by galinaalperovich** [comment]
I spent an hour on this issue. That is what finally helped me: 

1. uninstall all umaps you have (map, umap-learn)
2. update all conda packages `conda update --all`
3. install umap 0.4-dev version located here: https://github.com/lmcinnes/umap/tree/0.4dev
4. use the following import: 
```
import umap.umap_ as umap
import umap.plot
```

**Comment by lmcinnes** [comment]
Sorry for your difficulties @galinaalperovich ; but thanks for providing a workaround that worked for you, and hopefully others. The full release of 0.4 is getting awfully close, so hopefully this will not be an issue in the near future. Thanks again for your patience.

**Comment by galinaalperovich** [comment]
> Sorry for your difficulties @galinaalperovich ; but thanks for providing a workaround that worked for you, and hopefully others. The full release of 0.4 is getting awfully close, so hopefully this will not be an issue in the near future. Thanks again for your patience.

No problem, thank you for preparing a great upcoming release :) I already was able to build a very pretty graph with the new `umap.plot` package. Looking forward to 0.4 release!

**Comment by timothyslau** [comment]
I just ran into this using Sagemaker and UMAP umap.__version__ = version 0.5.2
