### ISSUE TITLE
inverse_transform() is very slow (?) for n_components > 2

### ISSUE THREAD

**Issue by aparrish** [lmcinnes/umap#325]
The `inverse_transform()` function works great with `n_components=2`, but runs very slowly for models with `n_components` greater than 2.

Abridged ipython session:

```
In [1]: import umap
In [2]: import numpy as np
In [5]: from sklearn.datasets import load_digits
In [6]: X = load_digits()['data']
In [7]: %time mapper2 = umap.UMAP(n_components=2).fit(X)
CPU times: user 11.8 s, sys: 107 ms, total: 11.9 s
Wall time: 7.66 s
In [8]: %time mapper8 = umap.UMAP(n_components=8).fit(X)
CPU times: user 8.34 s, sys: 208 ms, total: 8.55 s
Wall time: 5.54 s
In [9]: %time t2 = mapper2.transform(X)
CPU times: user 1.98 ms, sys: 975 µs, total: 2.95 ms
Wall time: 1.97 ms
In [10]: %time t8 = mapper8.transform(X)
CPU times: user 2.09 ms, sys: 938 µs, total: 3.02 ms
Wall time: 1.99 ms
In [11]: %time inv_t2 = mapper2.inverse_transform(t2)
CPU times: user 32.9 s, sys: 108 ms, total: 33 s
Wall time: 32.9 s
In [13]: %time inv_t8 = mapper8.inverse_transform(t8)
```

In several experiments I've never been able to get that last line to even finish, despite waiting hours. The Python process keeps consuming more and more memory while it's working (6GB right now and growing). Experiments with `n_components=3` will finish, but seem to take 2x–10x as long as `n_components=2`. (This is using the `0.4dev_fix#306` branch—happy to try out another!  Python 3.6.8, MacOS 10.14.6, on my aging MacBook Air, which is never going to be a machine learning workhorse but I thought it might at least be a useful data point.)

**Comment by lmcinnes** [comment]
It's to dio with the way things get computed -- there is no explicit transform function, so there is non-trivial computation to be done. It does involve a delaunay triangulation which can potentially be exponential in complexity with respect to dimension and is likely the source of the slow-down here. I don't think there are currently any ways around that without significant changes to how the inverse transform works. I'm afraid I don't have any easy solutions -- sorry.

**Comment by aparrish** [comment]
Thank you for responding! I suspected this might be the case, but wanted to report the issue in the event that there was an easy fix (and to leave a record here for other people who might have the same question in the future).
