### ISSUE TITLE
Import Lowering Error

### ISSUE THREAD

**Issue by adamgayoso** [lmcinnes/umap#334]
Hello,

I'm having the same issue as in #225, except I'm on Ubuntu. This occurred for several numba versions and seems to be fixed in 0.47.0.

Update: the issue may be coming from llvmlite==0.31.0. Downgrading to 0.30.0 fixed the issue.

**Comment by finalspy** [comment]
I can confirm the issue with umap 0.3.10 and numba 0.46 on Ubuntu ... but I used to have docker images build with those 2 libs which have not the issue... so it came from somewhere else as you pointed. 
I can also confirm that with numba 0.47 the issue is gone.

**Comment by sleighsoft** [comment]
See https://github.com/lmcinnes/umap/issues/336
