### ISSUE TITLE
THEORY: is the visualization of the result dependent on the n_components chosen?

### ISSUE THREAD

**Issue by PabloRR100** [lmcinnes/umap#346]
With this question I mean the following.

If you run PCA with 50 components and you then visualize the first 3, the result is equivalent as running PCA with 3 component and visualize them.

However, I have done the same thing with UMAP and it doesn't hold. 
I have run it with 3 components to later on run HDBSCAN on it. Then, visualize my clusters on a 3D scatter plot. This works fine.
I repeat the experiment but projecting the data into 50 components prior to HDBSCAN, and then taken the first 3 columns of the projected data along with the labels_ from HDBSCAN. The results are very different.

Any explanation behind this behaviour?

Thanks!

**Comment by sleighsoft** [comment]
If I am not mistaken, the choice of `n_components` affects the `optimize_layout` function which uses stochastic gradient descent to find a suitable low level representation of your higher dimensional data. As this is only stochastic, the obtained solution may not be the best possible one but instead only a local optimum may be found. This process takes all available components (your choice of `n_components`) into account. So having more components can indeed yield a different result.

Another note: UMAP does not operate the same way that PCA does. The first 3 components of 50 are not the ones sorted by highest variance or another property. Instead you should select `n_components` to be the value you want to use in a down-stream task.

**Comment by PabloRR100** [comment]
Understood! Thank you!

**Comment by sleighsoft** [comment]
Glad I could clarify a little
