### ISSUE TITLE
unexpected keyword argument 'output_metric'

### ISSUE THREAD

**Issue by qo4on** [lmcinnes/umap#349]
https://umap-learn.readthedocs.io/en/latest/embedding_space.html
Error in Colab:
```
sphere_mapper = umap.UMAP(output_metric='haversine', random_state=42).fit(digits.data)

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-25-129b8142117a> in <module>()
----> 1 sphere_mapper = umap.UMAP(output_metric='haversine', random_state=42).fit(digits.data)

TypeError: __init__() got an unexpected keyword argument 'output_metric'
```

**Comment by lmcinnes** [comment]
You will need the 0.4 version of UMAP for that to work, and I don't believe that is on CoLab yet. In fact it isn't officially released yet -- the docs are running a little ahead right now.

**Comment by qo4on** [comment]
Can you tell me what I'm doing wrong installing 0.4 version? I tried this in Colab:
```
!git clone -q --single-branch --branch 0.4dev https://github.com/lmcinnes/umap.git > /dev/null
!pip install datashader -q
!pip install "holoviews[recommended]" -q

import sys
module_path = '/content/umap'
if module_path not in sys.path:
  sys.path.insert(0, module_path)

!python setup.py -q install
import umap
```
After that `umap.__version__` returns `0.3.10`.

**Comment by lmcinnes** [comment]
I'm honestly not sure -- it looks fine to me, but I suspect there are quirks to how environments work on CoLab. You could try contacting the CoLab support to see if they have suggestions.
