### ISSUE TITLE
Preprocessing of the features

### ISSUE THREAD

**Issue by ameliajimenez** [lmcinnes/umap#36]
Hello Leland,

Congrats for the work and thanks for the code and examples. Looking forward for the paper!

If we'd like to use UMAP with the features that output a CNN, for example on MNIST dataset. Do the features need to be zero-centered? Or in some range?

I get the following error when running fit_transform(data): "ZeroDivisionError: division by zero".

Thanks again,
Amelia.

**Comment by 100518832** [comment]
Hi @amejs,

I too had the same error, it has been fixed on the master; however, if you use pip install to download umap, you will still need to find the repo with the setup.py file (generated when you unzip umap-master). Once you are in the directory with setup.py, from command line run the following:

``` python setup.py install ```

This should fix your problem.

Also if you have anymore questions please check the closed issues, as this has already been solved.

I am however still interested in your comment about zero-centred data. I would like to know if UMAP is intended to be used only on data-sets, where the features have been normalised, or zero-centred?  

Cheers,

100518832

**Comment by amejs** [comment]
Hi Ralph,

Perfect, I'll do that, thanks :+1:

**Comment by sleighsoft** [comment]
Please open a new issue if you are still interested. Closing due to being a stale issue.
