### ISSUE TITLE
Can't display umap.plot plots.

### ISSUE THREAD

**Issue by drmathwin** [lmcinnes/umap#368]
The object returned by a call to, for instance, umap.plot.points() cannot be passed to the umap.plot.show() method to be displayed to the user.  As a result, the plot cannot be viewed.

I'm using UMAP to do a dimensionality reduction on a Doc2Vec model generated by gensim.

from gensim.models.doc2vec import Doc2Vec
from sklearn.cluster import KMeans
import umap
import umap.plot

print("Loading Model")
model = Doc2Vec.load("d2v_test.model")

print("Clustering")
kmeans_model = KMeans(n_clusters=16, init='k-means++', max_iter=100)
clustering = kmeans_model.fit(model.docvecs.vectors_docs)

print("Performing UMAP reduction")
mapping = umap.UMAP(n_neighbors=15, min_dist=0.01, n_components=2, metric='cosine')
embedding = mapping.fit(model.docvecs.vectors_docs)

print("Plotting UMAP results")
p = umap.plot.points(embedding)
umap.plot.show(p)

The result of running this code is the following error:
ValueError: "Invalid object to show. The object to passed to show must be one of:

* a LayoutDOM (e.g. a Plot or Widget or Layout)
* a Bokeh Application
* a callable suitable to an application FunctionHandler

**Comment by lmcinnes** [comment]
Mostly this was designed for notebook use, and in a notebook these will display automatically (without any calls to show). The ``show`` function in this case is specific to the interactive plots, which won't (necessarily) automatically display in notebooks.

I believe that if you want to display the plot you can do

```python
p = umap.plot.points(embedding)
umap.plot.plt.show()
```

but I think this is certainly not obvious. I'll try to come up with a suitable API that will make all of this make sense.

**Comment by drmathwin** [comment]
Thanks, that works.

I agree that it's not obvious.  As far as I've been able to find (albeit in only a day of looking) there doesn't appear to be any documentation of how to actually display the plot.

The [page of documentation](https://umap-learn.readthedocs.io/en/latest/plotting.html) on the plotting features in UMAP has only one example which calls umap.plot.show - all of the other examples are simply umap.plot.connectivity(mapper, show_points=True).  There also doesn't appear to be a umap.plot example script on github.

**Comment by lmcinnes** [comment]
Yes -- it's all new, and works fine in notebooks, but I hadn't given much thought to other use cases, so thanks for bringing this to my attention. I have some thoughts and I'll try to provide a generic show method that should work for everything.
