### ISSUE TITLE
out of memory

### ISSUE THREAD

**Issue by LiuChaoXD** [lmcinnes/umap#372]
Here, I have some problems.
I manual install the umap==0.4, and run pip install -r requirements.txt , then  python setup.py install. It's ok, when I transform small data size with size(2000, 32). But if I use it to transform huge data with (30000, 32), it will out of memory. 

But I find, you publish the demo for transform the mnist data set with (70000, 384). I run it, and out of memory .

I don't know how to solve it. So I think maybe I install the wrong version. Then I reinstall the umap==0.3.10. But the error will being....

```
numba.errors.LoweringError: Failed in nopython mode pipeline (step: nopython mode backend)
Type of #4 arg mismatch: i1 != i32

File "../../miniconda3/envs/solo-sc/lib/python3.6/site-packages/umap/utils.py", line 131:
def make_heap(n_points, size):
    <source elided>
    """
    result = np.zeros((3, int(n_points), int(size)), dtype=np.float64)
    ^
```

Please, do you test the newest version (0.4) on mnist data? Does it work?  My python version is 3.6. Should I update it?

**Comment by sleighsoft** [comment]
Can you provide the code that you are running as well as the output of `pip freeze`, please :)

**Comment by paxtonfitzpatrick** [comment]
The problem you're running into with `umap==0.4` sounds like #367.  If you install the most recent version from master (either pull from lmcinnes/master if you have a local copy of the repo, or run `pip install git+git://github.com/lmcinnes/umap.git@ba31421be27a99a897ed8bdb39aa7ecfebd72e40#egg=umap_learn` if you don't), does the problem still happen?

The problem with `umap==0.3.10` sounds like #371, which looks to be more complicated

**Comment by LiuChaoXD** [comment]
> Can you provide the code that you are running as well as the output of `pip freeze`, please :)
> 
> Might also be related to: #363

![Xnip2020-03-06_21-31-20](https://user-images.githubusercontent.com/39954067/76087938-207cde00-5ff2-11ea-89ff-7a99b443628b.jpeg)

Thank you very much. And this is the output of `pip freeze`. 
And I run the demo in the docs page, it's `import umap
from sklearn.datasets import fetch_openml
import matplotlib.pyplot as plt
import seaborn as sns

sns.set(context="paper", style="white")

mnist = fetch_openml("mnist_784", version=1)

reducer = umap.UMAP(random_state=42)
embedding = reducer.fit_transform(mnist.data)

fig, ax = plt.subplots(figsize=(12, 10))
color = mnist.target.astype(int)
plt.scatter(embedding[:, 0], embedding[:, 1], c=color, cmap="Spectral", s=0.1)
plt.setp(ax, xticks=[], yticks=[])
plt.title("MNIST data embedded into two dimensions by UMAP", fontsize=18)

plt.show()`

The ram of my computer is 256GB, I think it's enough for running this demo, but ..... out of memory

**Comment by LiuChaoXD** [comment]
> The problem you're running into with `umap==0.4` sounds like #367 & #363. If you install the most recent version from master (either pull from lmcinnes/master if you have a local copy of the repo, or run `pip install git+git://github.com/lmcinnes/umap.git@ba31421be27a99a897ed8bdb39aa7ecfebd72e40#egg=umap_learn` if you don't), does the problem still happen?
> 
> The problem with `umap==0.3.10` sounds like #371, which looks to be more complicated

yeah, Thank u. The problem has been solved. I run the command `pip install git+git://github.com/lmcinnes/umap.git@ba31421be27a99a897ed8bdb39aa7ecfebd72e40#egg=umap_learn`. 

Thank you very much.
