### ISSUE TITLE
umap-learn[plot] extra not provided

### ISSUE THREAD

**Issue by mdamien** [lmcinnes/umap#387]
When doing `pip install "umap-learn[plot]"`, I get: `WARNING: umap-learn 0.3.10 does not provide the extra 'plot'`.

But when installing the package with `pip install -e .[plot]`, it works.

**Comment by lmcinnes** [comment]
I think you need the new umap 0.4; it is currently in release candidate stage, and hopefully will be on pip as a full release soon.

**Comment by mdamien** [comment]
It's fixed since the release :)
