### ISSUE TITLE
Is seaborn requred?

### ISSUE THREAD

**Issue by anzelpwj** [lmcinnes/umap#390]
https://github.com/lmcinnes/umap/blob/499f8350b3374767f41fcd49eac13b982c9329ac/umap/plot.py#L32

I'm not seeing the explicit import for seaborn. Is this involved in any of the other packages?

**Comment by lmcinnes** [comment]
You are right; it isn't actually required -- for an earlier version of the plotting library I believe it was, but it got factored out. Do you want to make a PR to fix the message?

**Comment by anzelpwj** [comment]
Happy to do so, will put it in tomorrow!

**Comment by lmcinnes** [comment]
Thanks.
