### ISSUE TITLE
Proper value for target_n_neighbors

### ISSUE THREAD

**Issue by jmirats** [lmcinnes/umap#393]
Hi,
I'm not reporting an issue, just asking for advice on a specific parameter.
I'm currently working on trying to fit an Umap model to a quite big data set, let say 300000 points with high dimensionality, say around 4000. I'm providing a target array for supervised dimension reduction, which in fact is just a vector of 0 and 1s representing the membership of a data point to one class or another; there are just 2 classes. I'm able to find good fitings, I mean I find what I expect, 2 classes, by using a number of neighbours between 150 and 200. However, when testing how the fit was for some new data points, the fiting is not good at all, as practically all new points are labelled as one class, while I provide the same number of test points for each of the classes. In this sense I was wondering about how to tune the parameters that directly affect the transform action, concretely 'target_n_neighbors' and 'negative_sample_rate'. I'm just using the default values. Would it make sense to just limit 'target_n_neighbors' to a small number, say 10, and increase 'negative_sample_rate' to a big one, say 100?
Many thanks

**Comment by lmcinnes** [comment]
Given that you are using just 2 classes the target n_neighbors is not going to help much I'm afraid. Given the description I am afraid to say that I think this approach is not going to be quite so useful for your data -- the transform is working off the near neighbors of the new points, and if they are all ending up in the one class it is because the closest points to them are all in the one class. Given the high dimensionality I would recommend considering looking at angular metrics -- cosine, correlation, or hellinger are all decent options. That may help.

**Comment by jmirats** [comment]
Thanks, I was not aware about hellinger distance; cosine and correlation are actually the 2 ones I tested. By your answer it seems that having 2 classes might be a kind of trouble, so one more question that comes to my mind is if it would make sense to lower target_weight to 0.1 for instance, to have more power put at the data, while maintaining a little bit of information from labels.

**Comment by lmcinnes** [comment]
Yes -- although that may mean you don't get the classes separated cleanly ... although that likely represents the reality of the dataset without labels more accurately.

**Comment by jmirats** [comment]
Ok thanks, I'll try.
By the way, trying the 'hellinger' distance I got an error like the one below. Strange, as it seems in the umap source code that 'hellinger' should be accepted

I'm calling the umap method as:
mapper = umap.UMAP(n_neighbors=args.k,
                       metric=args.dist,
                       random_state=69,
                       min_dist=args.md,
                       local_connectivity=args.lc,
                       n_epochs=args.epochs,
                       target_weight=args.tw,
                       target_n_neighbors=args.tk).fit(nzDense_norm,y=labels_train)

where, in this case, args.dist='hellinger'

the error:

File "/home/Trainer/lib/python3.6/site-packages/umap/umap_.py", line 1429, in fit
    self.verbose,
  File "/home/Trainer/lib/python3.6/site-packages/umap/umap_.py", line 215, in nearest_neighbors
    raise ValueError("Metric is neither callable, " + "nor a recognised string")
