### ISSUE TITLE
Hellinger distance not recognized as metric in v0.4.0

### ISSUE THREAD

**Issue by lambertsbennett** [lmcinnes/umap#395]
I installed umap-learn 0.4.0 and would like to try some of its new features, including document embedding with the hellinger distance and embedding on a sphere with the haversine distance. When I try to follow the documentation examples I get the following errors:

1. When trying to use the hellinger distance with metric='hellinger'
 ValueError: Unknown metric hellinger.

2. When following the 'embedding to non-euclidean spaces' tutorial I get the following error:
TypeError: __init__() got an unexpected keyword argument 'output_metric'

It seems like my install does not include any of the new v0.4.0 features for some reason.

**Comment by lambertsbennett** [comment]
I am going to answer my own problem here. Apparently you can overcome this by cloning the repo, entering into it, and 'running pip install .'. These newer changes must not be in the pip distribution.

**Comment by llf-amy** [comment]
I see this is closed, but I'm getting the same error even when installing from the current master branch. 
``
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/umap/umap_.py in fit(self, X, y)
   1696                 _m = self.metric if self._sparse_data else self._input_distance_func
-> 1697                 dmat = pairwise_distances(X[index], metric=_m, **self._metric_kwds)
   1698             except (ValueError, TypeError) as e:

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in pairwise_distances(X, Y, metric, n_jobs, force_all_finite, **kwds)
   1712                          "Valid metrics are %s, or 'precomputed', or a "
-> 1713                          "callable" % (metric, _VALID_METRICS))
   1714 

ValueError: Unknown metric hellinger. Valid metrics are ['euclidean', 'l2', 'l1', 'manhattan', 'cityblock', 'braycurtis', 'canberra', 'chebyshev', 'correlation', 'cosine', 'dice', 'hamming', 'jaccard', 'kulsinski', 'mahalanobis', 'matching', 'minkowski', 'rogerstanimoto', 'russellrao', 'seuclidean', 'sokalmichener', 'sokalsneath', 'sqeuclidean', 'yule', 'wminkowski', 'nan_euclidean', 'haversine'], or 'precomputed', or a callable

During handling of the above exception, another exception occurred:

TypingError                               Traceback (most recent call last)
<timed exec> in <module>

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/umap/umap_.py in fit_transform(self, X, y)
   1958             Embedding of the training data in low-dimensional space.
   1959         """
-> 1960         self.fit(X, y)
   1961         return self.embedding_
   1962 

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/umap/umap_.py in fit(self, X, y)
   1703                         X[index].toarray(),
   1704                         metric=self._input_distance_func,
-> 1705                         kwds=self._metric_kwds,
   1706                     )
   1707                 else:

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/umap/distances.py in pairwise_special_metric(X, Y, metric, kwds)
   1255             return metric(_X, _Y, *kwd_vals)
   1256 
-> 1257         return pairwise_distances(X, Y, metric=_partial_metric)
   1258     else:
   1259         special_metric_func = named_distances[metric]

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in pairwise_distances(X, Y, metric, n_jobs, force_all_finite, **kwds)
   1750         func = partial(distance.cdist, metric=metric, **kwds)
   1751 
-> 1752     return _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1753 
   1754 

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in _parallel_pairwise(X, Y, func, n_jobs, **kwds)
   1346 
   1347     if effective_n_jobs(n_jobs) == 1:
-> 1348         return func(X, Y, **kwds)
   1349 
   1350     # enforce a threading backend to prevent data communication overhead

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/sklearn/metrics/pairwise.py in _pairwise_callable(X, Y, metric, force_all_finite, **kwds)
   1373         iterator = itertools.combinations(range(X.shape[0]), 2)
   1374         for i, j in iterator:
-> 1375             out[i, j] = metric(X[i], Y[j], **kwds)
   1376 
   1377         # Make symmetric

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/numba/dispatcher.py in _compile_for_args(self, *args, **kws)
    399                 e.patch_message(msg)
    400 
--> 401             error_rewrite(e, 'typing')
    402         except errors.UnsupportedError as e:
    403             # Something unsupported is present in the user code, add help info

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/numba/dispatcher.py in error_rewrite(e, issue_type)
    342                 raise e
    343             else:
--> 344                 reraise(type(e), e, None)
    345 
    346         argtypes = []

~/miniconda3/envs/reproallthethings/lib/python3.7/site-packages/numba/six.py in reraise(tp, value, tb)
    666             value = tp()
    667         if value.__traceback__ is not tb:
--> 668             raise value.with_traceback(tb)
    669         raise value
    670 

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at <numba.typeinfer.CallConstraint object at 0x132732250>.
missing a required argument: 'ind2'
[1] During: resolving callee type: type(CPUDispatcher(<function sparse_hellinger at 0x11c10ea70>))
[2] During: typing of call at .../miniconda3/envs/reproallthethings/lib/python3.7/site-packages/umap/distances.py (1255)

Enable logging at debug level for details.

File "../../../miniconda3/envs/reproallthethings/lib/python3.7/site-packages/umap/distances.py", line 1255:
        def _partial_metric(_X, _Y=None):
            return metric(_X, _Y, *kwd_vals)
            ^
``

**Comment by lambertsbennett** [comment]
Did you previously uninstall the package before installing from master?

**Comment by lmcinnes** [comment]
Is this a sparse dataset by any chance?

**Comment by lmcinnes** [comment]
I think there is a tricky combination of sparse data, of a small enough size (small n_samples), that hits a corner case here. I'll see if I can fix it.

**Comment by lmcinnes** [comment]
This patch resolved the issue for me -- does it work for you Amy?

**Comment by llf-amy** [comment]
Yes. Sparse data. ~3000 rows.

**Comment by acwooding** [comment]
Works for me!
