### ISSUE TITLE
Errors with plot.diagnostic

### ISSUE THREAD

**Issue by tpapp157** [lmcinnes/umap#398]
Using the released UMAP 0.4.0

When I try to run a diagnostic plot:
umap.plot.diagnostic(U0, diagnostic_type='local_dim')

I get the following errors:
'UMAP' object has no attribute '_distance_func'
'UMAP' object has no attribute '_dist_args'

Looking at the UMAP code I can define these manually using the 'metric' and 'metric_kwds' attributes. That just leads me to this error:

  File "C:\ProgramData\Anaconda3\lib\site-packages\umap\plot.py", line 176, in _nhood_search
TypeError: initialise_search() takes 6 positional arguments but 7 were given

**Comment by lmcinnes** [comment]
Ah; some things got changed, but apparently the plot code didn't get updated to match. I'll see if I can fix it soon. Thanks for catching this!

**Comment by tpapp157** [comment]
0.4.1 release fixed the issue. Thanks.
