### ISSUE TITLE
FutureWarning raised when constructing lil_matrix

### ISSUE THREAD

**Issue by leriomaggio** [lmcinnes/umap#400]
### Description

Constructing a `scipy.sparse.lil_matrix` in [`UMAP.inverse_transform`](https://github.com/lmcinnes/umap/blob/master/umap/umap_.py#L2207) raises a `FutureWarning` 

### Versions

```
OS: macOS
Python 3.7.7 (default, Mar 26 2020, 10:32:53)
NumPy 1.17.5
SciPy 1.2.1
umap 0.4
```

### Steps/Code to Reproduce

I put the code to reproduce the issue in this [gist](https://gist.github.com/leriomaggio/7d13bd06d370f1801cfa8ce296253394)

### Cause

This issue is caused by a backward incompatibility of `scipy < 1.3` with the latest updates of Numpy (`numpy>=1.17`) APIs for `broadcast_arrays`.

`scipy 1.3.1` fixes this issue: [scipy/scipy#10379](https://github.com/scipy/scipy/pull/10379)

### Proposed solution

Looking at UMAP [`requirements.txt`](https://github.com/lmcinnes/umap/blob/master/requirements.txt) this is a perfectly valid combination of packages versions.

Due to the recent API changes in Numpy I would suggest to updates the requirements with most recent and non-conflicting `numpy` and `scipy` versions:

```
numpy>=1.17
scipy>=1.3.1
```

**Comment by lmcinnes** [comment]
Thanks -- good catch. I am not great at keeping up with the changing requirements.
