### ISSUE TITLE
Print feature importance?

### ISSUE THREAD

**Issue by zapaishchykova** [lmcinnes/umap#402]
Hello! I used umap to reduce dimensionality on my 300+ features. Is there a way to plot which of these features has the biggest impact on the resulting 2D projection?

```
reducer = umap.UMAP(random_state=42)
reducer.fit(X_train)
embedding = reducer.transform(X_train)
    
```

**Comment by lmcinnes** [comment]
Feature importance is really not something that UMAP supports -- the algorithm works in terms of a metric space, and thus loses the vector based feature structure very early in the process. If you really need feature importance type information you need to stick with matrix factorization based methods unfortunately.

**Comment by zapaishchykova** [comment]
Thanks!
