### ISSUE TITLE
why not use curve_fit for the algorithm3 mentioned in paper

### ISSUE THREAD

**Issue by rayeaster** [lmcinnes/umap#404]
looks what need there is a non-linear fit? 
since it is has to be done **element-wise**?

![image](https://user-images.githubusercontent.com/1487283/79541687-d4c35700-80bc-11ea-94cd-ae584f663df6.png)

https://github.com/lmcinnes/umap/blob/master/umap/umap_.py#L164

**Comment by lmcinnes** [comment]
Given that it is a parametrized function and the whole thing is monotonic a simply binary search is actually quite efficient.

**Comment by rayeaster** [comment]
> Given that it is a parametrized function and the whole thing is monotonic a simply binary search is actually quite efficient.

Thanks
