### ISSUE TITLE
I get an error "ValueError: unique is poorly defined on a precomputed metric" when trying to use a precomputed metric

### ISSUE THREAD

**Issue by sg-s** [lmcinnes/umap#409]
My precomputed distance matrix doesn't have any NaNs, or Inf, or anything weird. 

Full error:

```
Traceback (most recent call last):
  File "/Users/srinivas/anaconda3/envs/umap/lib/python3.8/site-packages/umap/umap_.py", line 1968, in fit_transform
    self.fit(X, y)
  File "/Users/srinivas/anaconda3/envs/umap/lib/python3.8/site-packages/umap/umap_.py", line 1625, in fit
    self._validate_parameters()
  File "/Users/srinivas/anaconda3/envs/umap/lib/python3.8/site-packages/umap/umap_.py", line 1501, in _validate_parameters
    raise ValueError("unique is poorly defined on a precomputed metric")
ValueError: unique is poorly defined on a precomputed metric
Error using umap/fit (line 51)
```

**Comment by sg-s** [comment]
I get the same error with a random matrix.

**Comment by sg-s** [comment]
The fix suggested in [This issue](https://github.com/lmcinnes/umap/issues/68), which seems to be similar, does not work (nor does it make sense..shouldn't the distance matrix be square?)

**Comment by sg-s** [comment]
The error is in [this line](https://github.com/lmcinnes/umap/blob/4689c7d18e257554e48d4b000b8d6596d17db1a1/umap/umap_.py#L1501)

and it looks like the `unique` flag is set to False, which automatically throws this error when given a precomputed distance matrix...?

**Comment by sg-s** [comment]
Commenting out that line fixes it, but not sure what I'm doing wrong...since the intention was clearly to throw that error.

**Comment by lmcinnes** [comment]
I think this is an error introduced by a few different sets of patches that interacted in a way such that the result here is flipped. It should be throwing the error if unique is True. I'll fix that now.

**Comment by sg-s** [comment]
Awesome, thanks!
