### ISSUE TITLE
Invalid link to Nerve theorem Wikipedia page in docs

### ISSUE THREAD

**Issue by gibsramen** [lmcinnes/umap#411]
In the documentation ([how_umap_works.rst](https://github.com/lmcinnes/umap/blob/master/doc/how_umap_works.rst)) there is a [link](https://github.com/lmcinnes/umap/blame/master/doc/how_umap_works.rst#L100) to the Nerve theorem Wikipedia page. This page does not exist on Wikipedia as far as I can tell (https://en.wikipedia.org/wiki/Nerve_theorem).

Perhaps it can be replaced with the following link? Happy to submit a PR on it - just want to make sure this link is fine. If you have an alternate suggestion for a paper/resource I can use that instead.

https://en.wikipedia.org/wiki/Nerve_of_a_covering

**Comment by lmcinnes** [comment]
Good catch. A PR would be great -- thanks.
