### ISSUE TITLE
Passing sparse distance matrices or KNNs directly

### ISSUE THREAD

**Issue by Rocketknight1** [lmcinnes/umap#424]
Hey, I'm trying to do clustering on approx 300k samples using the [Word Mover's Distance](http://proceedings.mlr.press/v37/kusnerb15.pdf) as a metric. This means that the input data does not take the form of vectors, and all-pairs distance comparisons are very expensive to compute. However, I can efficiently get all-pairs (approximate) nearest neighbours using methods like the 'centroid distance' from the paper and populate a sparse distance matrix with the distance values from all points to their nearest neighbours.

I'd really like to try passing those sparse distances to UMAP, but I get the following error when I try:

```
TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type pyobject
[1] During: typing of argument at /home/matt/miniconda3/envs/story-clustering/lib/python3.7/site-packages/umap_learn-0.4.2-py3.7.egg/umap/utils.py (29)

File "../../../miniconda3/envs/story-clustering/lib/python3.7/site-packages/umap_learn-0.4.2-py3.7.egg/umap/utils.py", line 29:
def fast_knn_indices(X, n_neighbors):
    <source elided>
    """
    knn_indices = np.empty((X.shape[0], n_neighbors), dtype=np.int32)
    ^

This error may have been caused by the following argument(s):
- argument 0: cannot determine Numba type of <class 'scipy.sparse.csr.csr_matrix'>
```

Is there any way I can get around this? I can compute nearest neighbours for free just by sorting rows of the sparse distance matrix, but I don't understand the UMAP code well enough to hack my precomputed NNs in. The distance matrix is also much too big to convert to dense form - a 300,000 x 300,000 matrix of float32 values would take ~340GB of memory, so I'm kind of stuck!

Here's my very simple code snippet that triggers this error:

```
data = scipy.sparse.load_npz('sparse_distances.npz').tocsr()
fit = umap.UMAP(metric='precomputed')
embedding = fit.fit_transform(data)
```

**Comment by lmcinnes** [comment]
I believe the issue is that precomputed sparse matrices are not currently supported. I'm not sure if there is an easy workaround at this time. In practice you can probably reach into the innards of UMAP and force it to work with what you have, but that's a little non-trivial. If you are interested in this option we can try to work out a reasonable set of changes you could make to make it work.

On a longer term front, pynndescent, which is going to be the engine for nearest neighbor search in umap v0.5 (and was spun out of the original umap code), will have a wasserstein/kantorovich distance in version 0.5. A sparse/online version of that would probably be enough to implement word-mover distance directly in the nearest neighbor search itself. That is still a little way off however.

**Comment by Rocketknight1** [comment]
I'm happy to reach into the innards! Perhaps the easiest approach is for me to compute nearest neighbours and distances directly, and then somehow skip the various calls that UMAP makes to get that?

**Comment by lmcinnes** [comment]
Yes, exactly. If you start [here](https://github.com/lmcinnes/umap/blob/21377499ef262049311b4f5f561c581eed4de9f5/umap/umap_.py#L1748) you can see it getting the nearest neighbors. Specifically you need to produce two arrays of shape ``(n_samples, n_neighbors)``. The first should be the indices of the ``n_neighbors`` nearest points, and the second should be the distances to those points. From there you can start just calling internal functions directly following [this](https://github.com/lmcinnes/umap/blob/21377499ef262049311b4f5f561c581eed4de9f5/umap/umap_.py#L1760) ... there is a bunch of cases that you can probably ignore (you likely have [this](https://github.com/lmcinnes/umap/blob/21377499ef262049311b4f5f561c581eed4de9f5/umap/umap_.py#L1775) and [this](https://github.com/lmcinnes/umap/blob/21377499ef262049311b4f5f561c581eed4de9f5/umap/umap_.py#L1813) as cases you can skip over unless you want to use transform later, or are doing (semi-)supervsied), so there aren't actually all that many calls to make. You just have to get to [here](https://github.com/lmcinnes/umap/blob/21377499ef262049311b4f5f561c581eed4de9f5/umap/umap_.py#L1919) and call that function appropriately and you are pretty much done. The real hard part here is having all the parameters to pass to those functions, but you should be able to cobble most of those together from how parameters in general are handled.

**Comment by Rocketknight1** [comment]
It worked, thank you! (At least I think it did - I haven't plotted the results to sanity check yet)

Do you want me to try to monkey patch a workaround into UMAP.fit() and submit a PR to handle the case where the user inputs sparse precomputed distances, or is that a bit too much of a niche thing that probably wouldn't be useful to anyone else?

**Comment by lmcinnes** [comment]
I think the thing to do is an ``elif`` that covers ``metric == "precomputed"`` and input is sparse and then does essentially what you've done to generate the knn_indices and knn_dists inside the fit function. If you want to submit a PR for that I would definitely appreciate it.

**Comment by Rocketknight1** [comment]
I created PR #425 for this!

**Comment by Rocketknight1** [comment]
Oops, just realized I left this open. Closing since it's all resolved, and thanks for helping with that PR!

**Comment by sgbaird** [comment]
> Hey, I'm trying to do clustering on approx 300k samples using the [Word Mover's Distance](http://proceedings.mlr.press/v37/kusnerb15.pdf) as a metric. This means that the input data does not take the form of vectors, and all-pairs distance comparisons are very expensive to compute. However, I can efficiently get all-pairs (approximate) nearest neighbours using methods like the 'centroid distance' from the paper and populate a sparse distance matrix with the distance values from all points to their nearest neighbours.

@Rocketknight1, Is there a coded implementation of the centroid distance to get the sparse matrix? Is it specific to Word Mover's, or do you know of an implementation that takes numerical vectors?

Related to this I also opened #751.

**Comment by Rocketknight1** [comment]
I used the definition of the centroids from the Word Mover's paper. If your word vectors for a given document are an NxD matrix M (N vectors, D dimensions per vector) and the weights (in my case I used TF-IDF or LLR weights) are an N-dimensional vector W, then the 'centroid' for that document is just `M.T @ W`. Once you compute the centroids you just find nearest neighbours with standard euclidean or cosine distance.

The same technique should work equally well for any case where you have numeric vectors and sample weights. I don't have sample code to hand, but it's only a few lines long anyway.

**Comment by sgbaird** [comment]
@Rocketknight1, any ballparks of how accurately that approach can identify kNNs correctly? I'm wondering if I have an error in my implementation, since I was getting marginally better (20%?) accuracy compared with what I'd expect from randomly guessing, even if I included nearly half the distance matrix as "sparse" distances.

**Comment by Rocketknight1** [comment]
In my testing I found it worked okay - I don't have exact numbers to hand, but I think in a dataset of around 10k samples, about 200 centroid NNs reliably contained most of the 25 true NNs, and almost always more than half of them.

**Comment by sgbaird** [comment]
@Rocketknight1, thank you! Just the kind of ballpark I was hoping for as a spot check.

**Comment by Rocketknight1** [comment]
@sgbaird One thing I should mention, though, is that in our data we used fasttext word vectors (which can generate a vector for any word from subword embeddings, even one not in the training data), and we used LLR weightings. This meant that rare words tended to get quite high weights (and were never dropped for being out-of-vocabulary), and we used those weights for both the centroids and the WMD calculations.

As a result, it's possible that centroids worked better for us than they might in other cases, because they were heavily biased towards the rare 'keywords' that also dominated the WMD calculations.

**Comment by lmcinnes** [comment]
If you want one more thing to play with (definitely experimental mind you), I have an implementation of linear optimal transport (with compression) in the [vectorizers library](https://github.com/TutteInstitute/vectorizers). This allows for something in between centroid based approaches, and a full optimal transport computation, with a linearization of optimal transport. If you have an NxD matrix of word vectors W and a bag-of-words, TF-IDF, or similar MxN sparse matrix of documents X then the relevant code would be along the lines of

```python
lot_vectors = vectorizers.WassersteinVectorizer().fit_transform(X, vectors=W)
```

This will produce an MxD matrix of document vectors such that cosine distances between the vectors should be correlated with word mover distance between the documents. The quality of the correlation depends on a number of things, and there are parameters you can tune, but this would be a start. If your documents are relatively long you can use ``vectorizers.SinkhornVectorizer`` instead, which uses Sinkhorn iterations as an approximation (or entropic regularization) of optimal transport that wqill run a lot faster, especially as document length grows.
