### ISSUE TITLE
Replace Iris references with Penguins in docs

### ISSUE THREAD

**Issue by gibsramen** [lmcinnes/umap#446]
The `basic_usage.rst` documentation still has some references to the Iris dataset that should be updated to the penguins dataset.

https://github.com/lmcinnes/umap/blame/master/doc/basic_usage.rst#L436
https://github.com/lmcinnes/umap/blame/master/doc/basic_usage.rst#L391

Can submit a PR later today.

**Comment by lmcinnes** [comment]
Ah thanks -- I would appreciate the PR.
