### ISSUE TITLE
Does UMAP accept a probability matrix as input?

### ISSUE THREAD

**Issue by wilsonjr** [lmcinnes/umap#449]
Thank you!

**Comment by lmcinnes** [comment]
Not currently -- what sort of probability matrix is it? If you want to shortcut some of UMAPs computations you can just apply the embedding algorithms directly to a similarity matrix. It would involve reaching in to some of the lower level functions and you'll have to find sensible values for some of the parameters, but it can certainly be done.

**Comment by wilsonjr** [comment]
Hello, Mr. McIness.
Thank you for your promptly response!

That's exactly what I am trying to do. I am trying to use UMAP to embed data using my own matrix of transition probability. I'll take a closer look at the code.

Thanks.
