### ISSUE TITLE
Adding performance notebook

### ISSUE THREAD

**Issue by MLWave** [lmcinnes/umap#45]
I created a small notebook for replication of UMAP performance when increasing dataset size and dimensionality.

I can not create a pull request though. Is this something on my end, or do I need a permission for this?

How to proceed?

![increasing dimensionality](https://i.imgur.com/4zT4Rbq.png)

![increasing data](https://i.imgur.com/xCdPeeZ.png)

![notebook](https://i.imgur.com/XatoPmS.png)

**Comment by lmcinnes** [comment]
I am honestly note sure what the issue is. You can post the notebook as a gist and I can add it myself if you feel that would be useful, but pull requests should just work.

**Comment by MLWave** [comment]
It is probably a local issue then. Thanks.

For now, here is the notebook: https://github.com/MLWave/notebooks/blob/master/UMAP%20Performance%20Tests.ipynb . It is a start.

Currently looking into using UMAP embeddings for meta-learning. [t-SNE XGBoost meta-bagging](https://www.kaggle.com/c/otto-group-product-classification-challenge/discussion/14295) style on the [Otto competition](https://www.kaggle.com/c/otto-group-product-classification-challenge/). Seeing some good top 10% results.

- 1: UMAP seems good diverse addition to ensemble (it is doing something new),
- 2: UMAP, like XGB, is fast enough to hypertune and experiment with).

If I get a good binary supervised machine learning example working I'll also create a notebook for this. Comparison between [raw features, embeddings, raw features + embeddings] is a bit difficult, due to requiring different XGB hyperparams for working best. For now, I try to allocate each model+feature_set an equal random grid-search time, but I don't know if that is fair.
