### ISSUE TITLE
Make `umap.__version__` return current version

### ISSUE THREAD

**Issue by MLWave** [lmcinnes/umap#46]
For replication purposes it is useful to print/log the current version of UMAP.

Is there are variable that holds this information?

**Comment by lmcinnes** [comment]
It should now ... Hopefully I can keep this all synced.

**Comment by MLWave** [comment]
Thank you very much!

**Comment by MLWave** [comment]
Sorry, I think:

```
__version__ = 0.2.1
```
should be:
```
__version__ = "0.2.1"
```

**Comment by lmcinnes** [comment]
Good catch. Thanks.
