### ISSUE TITLE
[Use Case] 3D Interactive visualization of UMAP

### ISSUE THREAD

**Issue by stwind** [lmcinnes/umap#498]
Hi @lmcinnes, thanks for creating UMAP. 

I've been experimenting 3D interactive exploration of UMAP ran on Fashion MNIST, and this is the result. It is like Grant Custer's UMAP Explorer, each point is rendered with the the actual image and colored according to the label. Also similar to the Tensorflow Embedding Projector, but designed more specifically for Fashion MNIST, thus more efficient and capable of showing all the 70k images.

[Here](https://observablehq.com/@stwind/exploring-fashion-mnist) is demo, let me know if that would be an appropriate addition to the current examples listed on the documents. I am happy to make a PR to it if so.

Best

**Comment by lmcinnes** [comment]
Hi @stwind . This certainly looks like a great project. You are welcome to add a PR for it and I'll try to get it merged when I get a chance.
