### ISSUE TITLE
Projecting new data into an existing model - Question

### ISSUE THREAD

**Issue by biobenkj** [lmcinnes/umap#506]
I have a very naive question regarding UMAP and projecting new data into an existing UMAP embedding:

Are the new data explicitly constrained to be within the previously embedded data points? My question stems from integrating data from differing platforms or tissues or treatment data. If I have an embedding from measurement platform A (for instance sequencing types like single-cell RNA) and wish to project data from measurement platform B into the previous embedding made with platform A. Will the data points from platform B be constrained to fall within the points from A?

Not sure if I'm asking a coherent question... 

Thanks again @lmcinnes for such an incredible approach!

**Comment by biobenkj** [comment]
As an explicit example if it helps: 
![hgsoc_projection_first_pass_with_fte_umap](https://user-images.githubusercontent.com/10948407/96013745-97dde000-0e13-11eb-8a45-e15ed06677c1.png)

The "normal FTE" was the initial embedding and the "hgsoc_ascites" is the new data. The prior is "normal tissue" and the latter is "cancerous tissue" likely originating from the former. I'm not seeking interpretation of the data/joint embedding, but more about if it's expected that new data projected into the original embedding is constrained to fall within the prior data points.

**Comment by lmcinnes** [comment]
The new data is not constrained to lie within the training data, but the training data is assumed to be a representative sample of the data. Thus new data that is significantly different from the training data will still be assumed to somehow lie on the learned structure, and get pulled in. That is, you should not expect data that is significantly different to form a new cluster or group; it will simply end up near the closest representatives of the training data. I'm not entirely sure if this answers your question, so please feel free to seek further clarification.

**Comment by biobenkj** [comment]
This does indeed answer my question! Thanks so much!
