### ISSUE TITLE
Access to high-dimensional fuzzy simplicial set

### ISSUE THREAD

**Issue by pcamara** [lmcinnes/umap#51]
I find for some applications (e.g. clustering) it is good to have access to the high-dimensional fuzzy simplicial set through the class `UMAP`. This can be easily implemented by storing `graph` as `self.graph` in the method `UMAP.fit()`. If you think this is a useful feature but are too busy with more urgent things, I will be happy to implement it through a pull request. Please let me know.

**Comment by lmcinnes** [comment]
I agree that this would be useful -- I'm busy doing some refactoring in a branch right now, but please feel free to add a pull request if I haven't gotten to this by the time you get some time to look into it. Thanks for the suggestion!
