### ISSUE TITLE
using the densmap

### ISSUE THREAD

**Issue by poloarol** [lmcinnes/umap#518]
Hello,

I've been trying to use the densMAP implementation built in UMAP but keep getting the error below;

`TypeError: __init__() got an unexpected keyword argument 'densmap'`

My code is as follows;

`reducer = umap.UMAP(metric=input_metric, random_state=self.seed, n_neighbors=neighbours, min_dist=min_dist, 
                            n_components=components, output_metric=output_metric, densmap=True)`

Thanks for the help

**Comment by lmcinnes** [comment]
You'll want to check your installed version of umap-learn. To use densmap it needs to be at least version 0.5. You can get that version by checking out the 0.5dev branch of UMAP from here and installing it. It hasn't officially been released to PyPI or conda-forge yet as it is still under development.

**Comment by poloarol** [comment]
Thanks
