### ISSUE TITLE
New point embedding with precomputed distances

### ISSUE THREAD

**Issue by Rocketknight1** [lmcinnes/umap#527]
Hey, this is something I've seen a couple of issues about, but none fit my use case exactly, and I believe it's something I can patch in. I wanted to double-check first, though!

My data is sparse distance matrices, with distances from each point only to its k-NNs. UMAP and HDBSCAN work well on this data now, but I still have some difficulties embedding new points, since the only representation I have for them is  those k-NN distances.

I think it -should- be possible in theory to embed new points with UMAP if I know the distances from the new point to its k-NNs in the original dataset the embedding was trained on - is that something you think I'd be able to monkey-patch in? If so, can you think of any obvious pitfalls, and/or do you want me to write a PR for it if I can manage it?

**Comment by lmcinnes** [comment]
I think it is something you can probably monkey patch in; it should hopefully be obvious in the transform step what is going on, and how to amend it to support your case.

**Comment by Rocketknight1** [comment]
Thanks! I got this working - it's probably too niche to be worth submitting a PR for, though, and it's only a few lines of code anyway. If you'd like one anyway, let me know, but otherwise I'll just close this issue out.
