### ISSUE TITLE
n_neighbors of point i includes i

### ISSUE THREAD

**Issue by jlmelville** [lmcinnes/umap#53]
In `fuzzy_simplicial_set`, in the small data case where X is the full distance matrix, the following code gets run:
```
    if metric == 'precomputed':
        # Note that this does not support sparse distance matrices yet ...
        # Compute indices of n nearest neighbors
        knn_indices = np.argsort(X)[:, :n_neighbors]
        # Compute the nearest neighbor distances
        #   (equivalent to np.sort(X)[:,:n_neighbors])
        knn_dists = X[np.arange(X.shape[0])[:, None], knn_indices].copy()
```

I believe that `knn_indices` and `knn_dists` contain the point itself and not just the k neighbors, i.e. it is always true that `knn_indices[i][0] == i` and `knn_dists[i][0] == 0`. 

This leads to an error in `simplicial_set_embedding` if `umap.UMAP` is run with `n_neighbors = 1` because `graph` just consists of zeros, with the following error (in PyCharm on Windows at any rate):

```
  File "C:\dev\python\umap\umap\umap_.py", line 1152, in simplicial_set_embedding
    graph.data[graph.data < (graph.data.max() / float(n_epochs))] = 0.0
  File "C:\dev\python\py36\lib\site-packages\numpy\core\_methods.py", line 26, in _amax
    return umr_maximum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation maximum which has no identity
```
An additional effect is that you can never use all neighbor distances in `fuzzy_simplicial_set`, because  `n_neighbors` must be smaller than the dataset size. Admittedly this isn't a very useful thing to do practically, but it seems like you ought to be able to do it.

So I think this is a bug. I haven't tried with large data and the `metric_nn_descent` code block.

**Comment by lmcinnes** [comment]
In general I have been working with the (somewhat standard) view than the neighbors of a point includes itself. That does mean, as you correctly point out, that an ``n_neighbors`` value of less than 2 simply does not work. At the other end of the scale I believe using ``n_neighbors`` equal to the dataset size would be ... bad for many reasons. I am certainly happy to update the documentation to reflect the bounds on the values that ``n_neighbors`` can  reasonably take, but I'm not sure I consider it a bug -- although I guess it certainly is if you interpret nearest neighbors to not include the point and get seemingly spurious results.

**Comment by jlmelville** [comment]
Ah, I did wonder if I was just unfamiliar with the definition of neighbors. Perhaps extend the validity check on `n_neighbors` to be between 2 and `X.shape[0] - 1`? No big deal, though. Closing.

**Comment by lmcinnes** [comment]
I'll add a validity check -- I agree that that would be sensible and help alleviate confusion.
