### ISSUE TITLE
TypeError: unsupported operand type(s) for *: 'UMAP' and 'UMAP'

### ISSUE THREAD

**Issue by slowkow** [lmcinnes/umap#530]
I'm trying to test the example in the documentation on combining multiple UMAP models:

https://umap-learn.readthedocs.io/en/latest/composing_models.html

Here's the code I ran:

```python
import sklearn.datasets
import umap

mnist = sklearn.datasets.fetch_openml("mnist_784")

top = mnist.data[:, :28 * 14]
bottom = mnist.data[:, 28 * 14:]

top_mapper = umap.UMAP(random_state=42).fit(top)
bot_mapper = umap.UMAP(random_state=42).fit(bottom)

intersection_mapper = top_mapper * bot_mapper
```

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
---> 25 intersection_mapper = top_mapper * bot_mapper

TypeError: unsupported operand type(s) for *: 'UMAP' and 'UMAP'
```

Here's the version I'm using:

```
umap.__version__
'0.4.6'
```

Am I missing something? Any advice would be appreciated. Thank you!

**Comment by lmcinnes** [comment]
The catch is that this functionality is only present in the 0.5 release.
You can get that using

pip install --pre umap-learn

or by installing from the current master branch on github.

**Comment by slowkow** [comment]
It worked! Thank you for the very fast reply.
