### ISSUE TITLE
Composed UMAP missing `_raw_data`

### ISSUE THREAD

**Issue by pmbaumgartner** [lmcinnes/umap#536]
Hey @lmcinnes! I'm loving the new model composition feature, thank you for including this in v0.5! I have been playing around with the 0.5dev branch recently and trying to develop a workflow with a multi-output classification problem. I thought I could compose 3 supervised UMAPs and then use semi-supervised learning on any new points with the composed UMAP object. However, after doing a model composition (either union or intersection), it looks like the resulting UMAP object is missing the attributes to do that:

Here, `umap_intersection = umap1 * umap2` and I'm trying to transform a new point into that space. Calling `umap_intersection.transform(X)` gives me:

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-55-2c06c39e2862> in <module>
----> 1 umap_intersection.transform(X)

~/anaconda3/envs/env/lib/python3.8/site-packages/umap/umap_.py in transform(self, X)
   2479         """
   2480         # If we fit just a single instance then error
-> 2481         if self._raw_data.shape[0] == 1:
   2482             raise ValueError(
   2483                 "Transform unavailable when model was fit with only a single data sample."

AttributeError: 'UMAP' object has no attribute '_raw_data'
```

I wasn't totally sure if this is intended behavior - to be honest, I couldn't exactly figure out through the docs whether this is something I should be able to do with a composed UMAP, or whether that composed mapping is essentially "frozen" and only for visualization.

**Comment by lmcinnes** [comment]
The error could be clearer, but the short answer is that transform isn't supported for composite models yet. It may be in the future, but it will take a little work to figure out the best way to make it work, so is unavailable right now.

**Comment by pmbaumgartner** [comment]
Got it! Thanks for the info.
