### ISSUE TITLE
Aligned umap plotting doesn't plot

### ISSUE THREAD

**Issue by EricThomson** [lmcinnes/umap#539]
In the _How to use AlignedUMAP_ example (https://umap-learn.readthedocs.io/en/latest/aligned_umap_basic_usage.html) overall it works well. At the end, the plotly plot either doesn't plot, or just hangs on the last cell. When I convert the last line from `fig.show()` to something like `fig.write_html(r"umap_align.html", auto_open=True) ` it works (opening up another tab). I am working in Jupyter in Firefox.

**Comment by lmcinnes** [comment]
This may be down to my lack of expertise with plotly. It is worth noting that the plot is rather large in memory (I am possibly not using plotly efficiently) and can take quite a while to display. I would welcome any other approaches that can display it better.

**Comment by EricThomson** [comment]
That could be it -- in my (limited) experience with plotly it has worked fine in Jupyter with `show()`.  I have started working with a fabricated data set with a _lot_ fewer data points, and will see if that makes a difference and follow up if I get any useful details.

**Comment by lmcinnes** [comment]
Thanks! Any and all feedback is most welcome.

**Comment by EricThomson** [comment]
You were right: the exact same workflow worked fine with a much smaller fabricated data set (600 original data points with only 20 values for interpolation), so I think it was just a matter of scale.
