### ISSUE TITLE
Sigma in the edge weight

### ISSUE THREAD

**Issue by cckao** [lmcinnes/umap#550]
In the UMAP paper, the edge weight is defined as

![image](https://user-images.githubusercontent.com/13618269/104849831-da3d1e80-5926-11eb-99fb-96acd702c4e2.png)

Sigma is set to the value such that 

![image](https://user-images.githubusercontent.com/13618269/104849862-03f64580-5927-11eb-877d-9d9a8480b80d.png)

where k is the number of nearest neighbors.

What is the underlying intuition of formulating k and sigma in this way? Is it related to perplexity?

**Comment by lmcinnes** [comment]
It is a matter of ensuring that the total membership strength of edges associated to a given sample is a fixed constant, and that constant should scale proportional to the number of neighbors. The choice of log_2 here is somewhat arbitrary, but can be taken as an estimate of the entropy if you wish.

**Comment by cckao** [comment]
@lmcinnes,

Thanks a lot.
