### ISSUE TITLE
Tensorflow import warning?

### ISSUE THREAD

**Issue by ivirshup** [lmcinnes/umap#551]
UI question/ request. Could the warning that tensor flow  isn't installed every time umap is imported be removed?

Unless I really want tensorflow, I tend to keep it out of environments since it often has version conflicts. I also tend to keep umap imports inside functions (as opposed to inside modules) since it's a slow import. This adds a lot of boilerplate for watching tensor flow warnings at each point I want to import umap.

**Comment by lmcinnes** [comment]
I certainly understand not wanting tensorflow in environments, and the warning can be annoying. The initial thought was that unexpected errors would be frustrating for users, so providing early feedback would be good. I'll see if I can work out a good option. Suggestions are also welcome.

**Comment by ivirshup** [comment]
Could you do something similar to how the additional dependencies are handled for plotting? E.g. if the user tries to instantiate `ParametricUMAP`, first you do an import check and then throw an equivalent warning/ error message?

**Comment by lmcinnes** [comment]
The catch is that ParametricUMAP is being imported into the overall umap namespace in the package ``__init__.py``. One possibility is to push the warning down to actually instantiating the model, but I'm not sure if that's good practice. What are your feelings on that?

**Comment by ivirshup** [comment]
That's what I was thinking. I think this is pretty common practice. For example, pandas has a number of functions that will error if you're missing an optional dependency ([wherever this function is used](https://github.com/pandas-dev/pandas/blob/46f77b57679a05c473b56d7284715db53480d399/pandas/compat/_optional.py#L60)).

**Comment by lmcinnes** [comment]
It seems that wasn't quite how things work give that it is imported into the ``umap`` namespace, but I think I have a solution that should suffice. While working on that I noted that the warning can be set to be a ``ImportWarning`` category, which is filtered out and not displayed by default. This would allow me to keep the warning in, but default to not showing for default use. Does that work for you?

**Comment by ivirshup** [comment]
Ah, I hadn't realized  the `ParametricUMAP` class couldn't even be imported without tensorflow. Your proposed solution works for me.

I worry that users might assume it's a bug in umap if they got a NameError here. An alternative could be to define a dummy `ParametricUMAP` class that throws an `ImportError` on `__init__`.

**Comment by lmcinnes** [comment]
The latter is, in fact, what I have done. Since this works for you, and seems reasonable to me I'll commit that now.

**Comment by ivirshup** [comment]
Great, thanks for the fix!
