### ISSUE TITLE
import error of umap.aligned_umap

### ISSUE THREAD

**Issue by kwanghoon821** [lmcinnes/umap#558]
>>> import umap.aligned_umap
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'umap.aligned_umap'

umap-learn                0.4.2            py37hc8dfbb8_0    conda-forge

python                    3.7.9           h6c3b2c9_0_cpython    conda-forge

I don't  know why this module cannot be imported...

**Comment by gregsskyles** [comment]
I believe that you have to be on the 0.5 version for that functionality; 
you are showing version 0.4.2.

**Comment by kwanghoon821** [comment]
@gregsskyles Ah Thank you!!
