### ISSUE TITLE
JavaScript implementation?

### ISSUE THREAD

**Issue by blokhin** [lmcinnes/umap#56]
Are you aware of any JavaScript implementations?

Most probably, there are none, so please ping if you'd be interested as well. There's already _e.g._ a powerful ML JavaScript toolkit https://github.com/mljs/ml so I'd love to have UMAP there included.

**Comment by lmcinnes** [comment]
I certainly don't know of any javascript implementations. I believe there was some possibility of a typescript implementation in tensorboard at some point, but I don't know the status of that. I am not much of a javascript programmer, so taking on such a project would be a bit beyond me. I would be happy to provide advice and guidance to others interested in it however.

**Comment by cannoneyed** [comment]
Just wanted to link to a javascript implementation here: [umap-js](https://github.com/PAIR-code/umap-js). Keep in mind there's a few features missing from the python implementation, but the performance is reasonable all things considered.
