### ISSUE TITLE
braycurtis and sparse matrices

### ISSUE THREAD

**Issue by fabcabtab** [lmcinnes/umap#560]
First of all, thanks for the great library!

I was playing with its functionalities and noticed that the braycurtis metric was not available when using sparse matrices.
However, when looking in the code, a sparse implementation is available, but braycurtis is commented out in sparse_named_distances in the sparse module. 

Is this a bug or is there any particular reason for this?

Thanks a lot!

**Comment by lmcinnes** [comment]
I think there were some bugs in corner cases fro sparse Bray Curtis that made things go very badly sometimes. I haven't looked at it for a while though. It might be salvageable now.

**Comment by lmcinnes** [comment]
A similar change was made in pynndescent, so once these get released (or when you install from the main branches on github), you should be good to go. Thanks for bringing this to my attention. It seems it languished for a while.

**Comment by fabcabtab** [comment]
Great, thanks a lot for the quick response and fix!
