### ISSUE TITLE
Unnecessary `print` in `init_graph_transform`.

### ISSUE THREAD

**Issue by JoOkuma** [lmcinnes/umap#562]
The `init_graph_transform` function calls `print("inside function\n", graph)` without considering the `verbose` flag. I don't think this was intended, it was probably added on PR #524.

Best,

**Comment by lmcinnes** [comment]
Yeah; sorry about that. Looks like some of my print debugging got left in :-(

**Comment by nbeuchat** [comment]
@lmcinnes it is not on `pip` yet, correct? I have just re-installed `umap-learn==0.5.0` and I see the same debug statement.

**Comment by lmcinnes** [comment]
It's fixed in the repo, but won't be on pip until the next patch release (0.5.1). I can't say for sure when that will come out, but hopefully in the next week or so.

**Comment by nbeuchat** [comment]
Thanks for your answer @lmcinnes! Not a big deal anyway :-)
