### ISSUE TITLE
Normalizing UMAP with technical variable

### ISSUE THREAD

**Issue by obruck** [lmcinnes/umap#565]
**How to normalize UMAP with a technical variable causing bias?**

**Data**
I am analyzing ~2000 variables extracted with convolutional neural networks (=transfer learning).

**Workflow**
In order for this to work, the images of different size are inserted in the foreground of a larger black image. Hence, the original image ratio is kept unchanged. The data is then analyzed with UMAP for dimension reduction.

**Problem**
However, I notice that one major driver for the dimension reduction is the differences in original image size (likely the proportion of the image foreground to the black background). I wonder if I could somehow normalize or regress out the original image size (=area) but could not find anything in the package documentation.

**Nice to know**
For comparison, this is implemented in the [Seurat](https://satijalab.org/seurat/v3.2/cell_cycle_vignette.html) package used for analysis of single-cell RNAseq data as
`ScaleData(marrow, vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(marrow))`

Any suggestions?

Thanks in advance!

**Comment by obruck** [comment]
Here is an example of the UMAP, where dimension 1 seems to reflect the image size (= technical bias).
<img width="929" alt="UMAP_example" src="https://user-images.githubusercontent.com/25300573/106362887-fa5cdc80-632d-11eb-880a-26377a4535f1.png">

**Comment by lmcinnes** [comment]
You could try preprocessing the data by projecting away from a suitable vector (e.g, assuming the image size is the primary source of variation, project away from the first principal component), and hand the result to UMAP. I suspect that's what you'll have the most luck with -- of course working out exactly what to project away from is going to be the hard part here, but I think that's more a matter of domain knowledge and linear algebra.

**Comment by obruck** [comment]
Thanks @lmcinnes, I appreciate your feedback although this is not a software issue. Perhaps something to be implemented in future updates :)

If I understood you correctly, you suggest
1. PCA
2. Remove PCs correlating with image area
3. UMAP for the remaining PCs

As visual features are non-parametric data, shouldn't UMAP be preferred over PCA dimension reduction?

I also looked up the documentation for the Seurat package, and the `vars.to.regress` indicates which confounding variables should be tested for with regression analysis to reduce their effect on the primary features. In practice
`feature1 ~ confounding factor1 + confounding factor2 + etc`
The regression residuals are kept. I will implement a custom regression solution and compare that to the PCA step.

**Comment by obruck** [comment]
As a follow-up for anybody else facing this issue. Even though both solutions seemed promising, the results indicate that neither of them nor their combination (deleting confounding PCs + regressing out the effect of the confounding factor from PCs) can exclude the bias completely. Will update in case I find a working solution.

**Comment by lmcinnes** [comment]
I suspect it will be very hard to remove it entirely. I'm sorry I can't offer better solutions.
