### ISSUE TITLE
`UMAP.transform()` is printing "inside function" to stdout 

### ISSUE THREAD

**Issue by SultanOrazbayev** [lmcinnes/umap#574]
I'm using version `0.5.0`, after fitting `UMAP().fit()`, I am trying to run `.transform()` on new, unseen data, but receive verbose output that begins with "inside function". It's possible to use jupyter's `io.capture_output()` to suppress this output, but is there any way of suppressing it within UMAP?

**Comment by lmcinnes** [comment]
It should be fixed now, and a new release was just published that should contain the fix. Sorry about this, but hopefully it is resolved now.

**Comment by SultanOrazbayev** [comment]
Great, thank you!
