### ISSUE TITLE
Broken link at the documentation

### ISSUE THREAD

**Issue by hoppiece** [lmcinnes/umap#577]
Hello.
In [the official documentation of Parametric UMAP](https://umap-learn.readthedocs.io/en/latest/parametric_umap.html), the link to this GitHub repository is broken. 
The error is the last part of this paragraph in the document;
> In this implementation, we use Keras and Tensorflow as a backend to train that neural network. The added complexity of a learned embedding presents a number of configurable settings available in addition to those in non-parametric UMAP. A set of Jupyter notebooks walking you through these parameters are available on the GitHub repository

I think this link should be
 `https://github.com/lmcinnes/umap/tree/master/notebooks/Parametric_UMAP`
, not 
`https://github.com/lmcinnes/umap/notebooks/parametric_umap/`.

Thank you for your great works!

**Comment by lmcinnes** [comment]
Good catch; thank you.

**Comment by hoppiece** [comment]
Thank you!
