### ISSUE TITLE
ModuleNotFoundError: No module named 'umap.parametric_umap'

### ISSUE THREAD

**Issue by himaniyadav** [lmcinnes/umap#579]
Hello. This code:
    `from umap.parametric_umap import ParametricUMAP
`
Triggers this error
`ModuleNotFoundError: No module named 'umap.parametric_umap'
`
And I'm not sure why. I can import umap itself just fine.

**Comment by gregsskyles** [comment]
What version of UMAP are you using? I believe it needs to be >= 0.5 for 
that to work.

**Comment by himaniyadav** [comment]
That must be the error. It looks like I have 0.5.1 version installed with pip but my conda list shows 0.4.2. I'm not sure how to update the conda version. I tried `conda update umap-learn` but it stayed at version 0.4.2
