### ISSUE TITLE
[DEV] test on gradient metrics match fail on hellinger

### ISSUE THREAD

**Issue by leriomaggio** [lmcinnes/umap#590]
Reporting this bug found in development for log purposes - I am sure @lmcinnes you're already aware.

I tried a couple of things very quickly - so my goal here is to give you _clues_ and possible _directions_ in case you haven't the time to look into that yet 🙌 

It seems that there is a `failure` in the `test_grad_metrics_match_metrics` when testing the default `hellinger` metric [L529](https://github.com/lmcinnes/umap/blob/05840ef919f2367d77e3ba929de86ea31056e691/umap/tests/test_umap_metrics.py#L529)

In particular, it seems that 
```python 
dist_matrix = dist.pairwise_special_metric(
        np.abs(spatial_data), np.abs(spatial_data)
    )
``` 
returns an empty distance matrix:

```python
>       assert_array_almost_equal(
            test_matrix,
            dist_matrix,
            err_msg="Distances don't match " "for metric hellinger",
        )
E       AssertionError: 
E       Arrays are not almost equal to 6 decimals
E       Distances don't match for metric hellinger
E       (shapes (10, 10), (0, 0) mismatch)
E        x: array([[0.      , 0.418969, 0.354731, 0.453094, 0.408693, 0.325863,
E               0.423645, 0.347026, 0.410423, 0.312178],
E              [0.418969, 0.      , 0.397624, 0.414187, 0.447527, 0.377329,...
E        y: array([], shape=(0, 0), dtype=float32)
```

The failure **does not** occur when `Y=None` in `dist.pairwise_special_metric` invocation, namely:
```python
dist_matrix = dist.pairwise_special_metric(np.abs(spatial_data))
```

**Symptoms and Clues**:

The failures resolves when either (A) `Y=None` **OR** `parallelization` is removed from the `numba.njit` decorator
([`distances.py:L1252`](https://github.com/lmcinnes/umap/blob/05840ef919f2367d77e3ba929de86ea31056e691/umap/distances.py#L1252))

This led me thinking that the failure may be caused by a possible *race condition* happening during parallelization which results in wrong calculations at `numba` level - _but I may be wrong!_
See [Numba Parallel - Explicit Parallel Loops](https://numba.pydata.org/numba-doc/dev/user/parallel.html#explicit-parallel-loops)

**Comment by lmcinnes** [comment]
This was my fault; I added some new code for pairwise special distances that should be significantly faster. For some reason it fails on Python 3.8 (and works otherwise). Worst case I can fall back to the old version, but I admit that the failure is puzzling. I was going to look at it today, but various things have come up. I'll go with the fallback option and work out why this failure occurs later. Thanks for the triage work, it is certainly helpful for what is a strange error.

**Comment by leriomaggio** [comment]
@lmcinnes No problem, it is indeed puzzling. So I had an half an hour to spare and made a couple of tests. 
It seems that the issue here is related to the `result` array which is somewhat not handled properly during parallelization.
This issue in numba gave me a hint [2699](https://github.com/numba/numba/issues/2699)  

So I changed the flow in the function, and it seems to work: 

```python
@numba.njit(parallel=True, nogil=True)
def chunked_parallel_special_metric(X, Y=None, metric=hellinger, chunk_size=16):
    if Y is None:
        size = X.shape[0]
        result = np.zeros((size, size), dtype=np.float32)
        n_row_chunks = (size // chunk_size) + 1
        for chunk_idx in numba.prange(n_row_chunks):
            n = chunk_idx * chunk_size
            chunk_end_n = min(n + chunk_size, size)
            for m in range(n, size, chunk_size):
                chunk_end_m = min(m + chunk_size, size)
                if n == m:
                    for i in range(n, chunk_end_n):
                        for j in range(m, chunk_end_m):
                            if j > i:
                                d = metric(X[i], X[j])
                                result[i, j] = d
                                result[j, i] = d
                else:
                    for i in range(n, chunk_end_n):
                        for j in range(m, chunk_end_m):
                            d = metric(X[i], X[j])
                            result[i, j] = d
                            result[j, i] = d
        return result

    row_size = X.shape[0]
    col_size = Y.shape[0]
    result = np.zeros((row_size, col_size), dtype=np.float32)
    n_row_chunks = (row_size // chunk_size) + 1
    for chunk_idx in numba.prange(n_row_chunks):
        n = chunk_idx * chunk_size
        chunk_end_n = min(n + chunk_size, row_size)
        for m in range(0, col_size, chunk_size):
            chunk_end_m = min(m + chunk_size, col_size)
            for i in range(n, chunk_end_n):
                for j in range(m, chunk_end_m):
                    d = metric(X[i], Y[j])
                    result[i, j] = d

    return result
```

What do you think?

**Comment by lmcinnes** [comment]
It certainly isn't pretty, but if it works it is worth it. Good work figuring out something that does work. Feel free to submit this as a fixed version.
