### ISSUE TITLE
Does UMAP accept a distance matrix as custom metric?

### ISSUE THREAD

**Issue by VisuMap** [lmcinnes/umap#61]

**Comment by lmcinnes** [comment]
As of version 0.2 onward it does yes. @LGro provided the code to enable this. If you set ``metric='precomputed'`` then you can pass a distance matrix rather than a dataset to the fit or fit_transform method.

**Comment by VisuMap** [comment]
Thanks for the info and kind offer. I guess I can wait till version 0.2 is officially released.

**Comment by bccho** [comment]
@lmcinnes Will support for precomputed metrics soon make its way into `0.3dev`?

**Comment by lmcinnes** [comment]
@bccho It is already in 0.2, so yes it will continue to exist in 0.3dev.

**Comment by LGro** [comment]
@VisuMap, is this issue resolved or do you still have trouble accessing the feature?  
If it is resolved, please consider closing the issue - thanks :)

**Comment by dawe** [comment]
> As of version 0.2 onward it does yes. @LGro provided the code to enable this. If you set `metric='precomputed'` then you can pass a distance matrix rather than a dataset to the fit or fit_transform method.

And yet:

```
>>> U = umap.UMAP(metric='precomputed')
>>> XY = U.fit_transform(dm)
[…]
ValueError: Metric is neither callable, nor a recognised string
>>> umap.__version__
0.3.0
```

**Comment by LGro** [comment]
@dawe, it seems like the lines around L1457 in the current master branch might fix your issue. Could you please try to build from master?  
https://github.com/lmcinnes/umap/blob/ec860e9280dcd4a80c820c73c4cd5fb77cd59278/umap/umap_.py#L1453-L1462
