### ISSUE TITLE
Parametric UMAP fit_transform and _fit_embed_data

### ISSUE THREAD

**Issue by Andresd45** [lmcinnes/umap#619]
I have a little confusion trying to run ParametricUMAP,

Following the code in one of the notebooks: 

```
from tensorflow.keras.datasets import mnist
(train_images, Y_train), (test_images, Y_test) = mnist.load_data()
train_images = train_images.reshape((train_images.shape[0], -1))/255.
test_images = test_images.reshape((test_images.shape[0], -1))/255.

from parametric_umap import ParametricUMAP

embedder = ParametricUMAP(parametric_reconstruction=True,
        autoencoder_loss=True, verbose=True)

embedding = embedder.fit_transform(train_images)
```

After fitting the model I do not get back an encoder/ decoder. It seems that it does not use the _fit_embed_data method, am I doing something wrong? 

Thanks

**Comment by timsainb** [comment]
Hi Andres,

The encoder and decoder will be stored in the embedder (i.e.`embedder.encoder`)

**Comment by Andresd45** [comment]
Thanks for your answer! But that is the issue 
print(embedder.decoder) = None.

Now if I use fit_transform and then call the _fit_embed_data method
embedding = embedder._fit_embed_data(train_images[1:1000], 100, [], [])[0]
Now the embedder is equiped with a decoder/encoder keras model, but the fit_transform method is not giving me the network

**Comment by timsainb** [comment]
Are you using the implementation in this repo? If so could you try making a colab notebook to reproduce the issue?

**Comment by Andresd45** [comment]
It worked fine in colab, sorry about that. 

Thank you!

**Comment by timsainb** [comment]
Good to hear!
