### ISSUE TITLE
Parametric UMAP on sparse data

### ISSUE THREAD

**Issue by altrabio** [lmcinnes/umap#625]
First of all thanks for your excellent work and providing it to the community.

I am wondering if parametric UMAP can be used with data provided in the form of a sparse Matrix. I  have been encountering issues notably with the tensorflow based part of the process (Note, I might be doing something wrong and furthermore I am using UMAP in R thanks to reticulate package)

**Example of error encountered:**

Fri Mar 19 15:51:16 2021 Finding Nearest Neighbors
Fri Mar 19 15:51:16 2021 Building RP forest with 15 trees
Fri Mar 19 15:51:24 2021 metric NN descent for 15 iterations
         1  /  15
         2  /  15
         3  /  15
         4  /  15
         5  /  15
         6  /  15
         7  /  15
         8  /  15
         9  /  15
         10  /  15
        Stopping threshold met -- exiting after 10 iterations
Fri Mar 19 15:52:05 2021 Finished Nearest Neighbor Search
Fri Mar 19 15:52:06 2021 Construct embedding
Error in py_call_impl(callable, dots$args, dots$keywords) :
  TypeError: in user code:

    /home/pierre/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/umap/parametric_umap.py:785 gather_X  *
        edge_to_batch = tf.gather(X, edge_to)
    /home/pierre/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:180 wrapper  **
        return target(*args, **kwargs)
    /home/pierre/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:4541 gather_v2
        batch_dims=batch_dims)
    /home/pierre/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:180 wrapper
        return target(*args, **kwargs)
    /home/pierre/.local/share/r-miniconda/envs/r-reticulate/lib/python3.6/site-packages/tensorflow/python/ops/array_ops.py:4524 gather
        return gen_array_ops.gather_v2(params, indices, axis, name=name)
    /home/pierre/.local/share/r-miniconda/envs/r-reticulat

**Comment by lmcinnes** [comment]
I believe the short answer is that this is not going to work. While the standard UMAP can handle sparse data ParametricUMAP needs to be able to pass the data through tensorflow and I don't believe tensorflow has sparse support (or, if it does, it would require special handling which is not currently available in ParametricUMAP). Sorry.

**Comment by altrabio** [comment]
Thank you for answering so promptly
