### ISSUE TITLE
When does UMAP not set _knn_indices?

### ISSUE THREAD

**Issue by DeNeutoy** [lmcinnes/umap#632]
I've been building a visualisation tool for UMAP which relies on some private attributes (I know, I shouldn't have done that 😅  ), particularly `_knn_indices` for recommendation based on a set of already selected points. I browsed the code, but it wasn't 100% obvious to me when this is not set - I think maybe when the data is sparse/when the distance matrix is pre-computed? Is this correct? Any pointers would be very helpful!

**Comment by lmcinnes** [comment]
If you are using 0.5 or newer then it should only really happen if you have a small enough dataset that it just brute-forces the neighbor computations (currently a slightly arbitrary threshold of 4096 samples). If you want consistency you can use ``force_approximation_algorithm=True`` which is mostly just a parameter for testing purposes, but it will force the code to always take the path where ``_knn_indices`` gets set.

**Comment by DeNeutoy** [comment]
Perfect, thanks a lot!
