### ISSUE TITLE
Is there any practical advantage to do PCA before UMAP?

### ISSUE THREAD

**Issue by mayankgoyal1993** [lmcinnes/umap#642]
I know it is for computation efficiency, is there any other practical reason?

Also, I am planning to use Parametric UMAP, shall we use PCA+UMAP during training and inference time?

**Comment by lmcinnes** [comment]
Arguably it can have some beneficial effects by removing some noise in the data. You should always check the percentage of variance explained, however, to be sure you aren't throwing away a lot of information with PCA.

**Comment by mayankgoyal1993** [comment]
Thanks for it, I understand that it will remove noise that UMAP might not remove due to its some inherent assumption of uniform manifold.
