### ISSUE TITLE
ParametricUMAP seems to sample wrt inverse weights

### ISSUE THREAD

**Issue by sdamrich** [lmcinnes/umap#648]
In non-parametric UMAP edges are sampled proportional to their high-dimensional similarity weights w<sub>ij</sub>. But in ParametricUMAP edges are sampled proportional to `epochs_per_sample`, which is proportional to 1 / w<sub>ij</sub>, see lines 930-933 in `parametric_umap.py`:
```
    edges_to_exp, edges_from_exp = (
        np.repeat(head, epochs_per_sample.astype("int")), 
        np.repeat(tail, epochs_per_sample.astype("int")),
    )
```
Is this intentional? I propose a possible explanation as to why this does not change the visualization quality of ParametricUMAP in [https://arxiv.org/abs/2103.14608](https://arxiv.org/abs/2103.14608).

**Comment by timsainb** [comment]
It looks like this is a bug in this implementation. The implementation we used for the Parametric UMAP paper samples proportionally to the weights.

https://github.com/timsainb/ParametricUMAP_paper/blob/00b4d676647e45619552aec8f2663c0903a83e3f/tfumap/umap.py#L411:

```
epochs_per_sample = np.clip(
    (weight / np.max(weight)) * self.max_sample_repeats_per_epoch,
    1,
    self.max_sample_repeats_per_epoch,
).astype("int")

edges_to_exp, edges_from_exp = (
    np.array([np.repeat(head, epochs_per_sample.astype("int"))]),
    np.array([np.repeat(tail, epochs_per_sample.astype("int"))]),
)
```

**Comment by timsainb** [comment]
Interesting paper though, I need to read it in detail.

**Comment by sdamrich** [comment]
Thanks for the prompt response! This solves my issue. 
I hope you enjoy the paper.
