### ISSUE TITLE
Documentation does not say how to save plot image

### ISSUE THREAD

**Issue by pd3** [lmcinnes/umap#662]
The documentation does not say how to save plots as an image (https://umap-learn.readthedocs.io/en/latest/plotting.html).
How do I do this? 

This is the toy example I've been experimenting with:
```
>>> import umap
>>> import umap.plot
>>> from sklearn.datasets import load_digits
>>> digits = load_digits()
>>> 
>>> mapper = umap.UMAP().fit(digits.data)
>>> umap.plot.points(mapper, labels=digits.target)
<AxesSubplot:>
```

**Comment by lmcinnes** [comment]
If you are in a notbook it should just display inline. From a raw ptyhon shell or script you will need to call "show". For points it is a matplotlib plot so:

```
>>> import umap
>>> import umap.plot
>>> import matplotlib.pyplot as plt
>>> from sklearn.datasets import load_digits
>>> digits = load_digits()
>>> 
>>> mapper = umap.UMAP().fit(digits.data)
>>> umap.plot.points(mapper, labels=digits.target)
>>> plt.show()
```

I have tried to supply an overloaded show that can handle all of the different plot types, so this *should* work, but it has proved tricky to get this right for all cases, so I can't promise 100% success rates.

```
>>> import umap
>>> import umap.plot
>>> from sklearn.datasets import load_digits
>>> digits = load_digits()
>>> 
>>> mapper = umap.UMAP().fit(digits.data)
>>> p = umap.plot.points(mapper, labels=digits.target)
>>> umap.plot.show(p)
```

**Comment by pd3** [comment]
I am not in a notebook and I need to run this from a script on a remote computer from an ssh terminal without X forwarding. In the meantime I found out one can save the image as follows:
```
import matplotlib.pyplot as plt
...
plt.savefig('test.png')
```
