### ISSUE TITLE
Supervised dimesion reduction overfitting

### ISSUE THREAD

**Issue by AntonS-bio** [lmcinnes/umap#663]
Apologies if this is a dumb question, but what's the best way to understand level of overfitting when using supervised approach?

In example below, the separation of points is very clear despite random input. I understand the reason for it, but don't know how to asses the extent to which separation is driven by overfitting vs by "real" differences in data generating process. Any suggestions? Masking some samples works somewhat, but only if there are enough left for fitting after mask which there aren't in my data.

```
import umap
import numpy as np
from matplotlib import pyplot as plt

testSamples=400
randomrows=np.random.randint(0,2,size=(testSamples,50))
testMetadata=np.random.randint(0,2,size=testSamples)
fitter = umap.UMAP(n_neighbors=25, min_dist=0.1, metric='hamming').fit(randomrows, y=testMetadata)

#uncomment these to run semi-supervised
#testMetadata_masked=testMetadata
#testMetadata_masked[np.random.choice(len(testMetadata_masked), size=50, replace=False)] = -1
#fitter = umap.UMAP(n_neighbors=25, min_dist=0.1, metric='hamming').fit(randomrows, y=testMetadata_masked)

embedding  = fitter.embedding_

plt.scatter(embedding[:,0],embedding[:,1],  s=5, c=testMetadata)
plt.show()

```

**Comment by jc-healy** [comment]
This is indeed entirely expected.  You handed UMAP a cloud of random points.  If you use unsupervised UMAP you'll see this cloud as an amorphous blob with no real structure (which is good).  You then grabbed half of the points and told UMAP that they should be grouped together and the other half should be grouped together.  There was essentially no structure in your unsupervised embedding so the supervised aspect of your embedding was dominated by your embedding.  

As you pointed out subsampling can be used to weaken this signal if that's what you want.  A quick and dirty fix might be to do a stratified subsampling approach where you subsampled a fixed number of labels from each of your classes.  That would allow you to weaken the signal from your labels while guaranteeing that they were all present and equally represented.

**Comment by dosssman** [comment]
Thank you very much for sparing some of your valuable time to provide such intuitive explanation.
Indeed, `n_neighbors` would reduce the quality of the clustering itself, thereby impact the supervised clustering.

Overall, the `target_weight` parameter is easier to understand and experiment with.
