### ISSUE TITLE
Enhancement request, add fractional distance

### ISSUE THREAD

**Issue by ivan-marroquin** [lmcinnes/umap#671]
Hi,

Thanks for such great package!

I bumped into this research work https://bib.dbvis.de/uploadedFiles/155.pdf, in which the authors propose a fractional distance to deal better with the notion of near/far neighbors in high dimensional data sets. According to their results, the fractional distance can provide better outcomes compared to Euclidean (or Manhattan) distance.

So, I would like to submit this enhancement request: include fractional distance in UMAP package.

Kind regards,

Ivan

**Comment by ivan-marroquin** [comment]
Hi,

I notice that it is possible to define our own metric in UMAP. So, I decided to give a try and programmed fractional distance metric.

I am using Python 3.6.5 with UMAP 0.5.1 , numba 0.53.1 and numpy 1.19.0. When I run the script (see attachement), I get the following error message:

#---------------->
Traceback (most recent call last):
  File "umap_dim_reduction.py", line 56, in <module>
    clusterable_embedding= embedding.fit_transform(input_data)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\umap\umap_.py", line 2634, in fit_transform
    self.fit(X, y)
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\umap\umap_.py", line 2554, in fit
    self._raw_data[index], n_epochs, init, random_state,  # JH why raw data?
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\umap\umap_.py", line 2601, in _fit_embed_data
    self.verbose,
  File "C:\Temp\Python\Python3.6.5\lib\site-packages\umap\umap_.py", line 1168, in simplicial_set_embedding
    verbose=verbose,
ZeroDivisionError: division by zero
#---------------->

Any suggestions?

Ivan

[umap_dim_reduction.zip](https://github.com/lmcinnes/umap/files/6504160/umap_dim_reduction.zip)

**Comment by ivan-marroquin** [comment]
I reviewed my previous code, and I think that I found a much better to compute fractional distance:

@numba.njit(fastmath= True)
def fractional_dist(p_vec, q_vec, fraction= 0.3):
        """
        this function implements the fractional distance metric, where fraction
        is in the form of 1/l and l is some integer.
        
        based on research work by:
        Aggarwal, C. C., A. Hinneburg, and D. A. Keim, 2001, On the surprising
        behavior of distance metrics in high dimensional space: International
        Conference on Database Theory, 420 - 434
        """

        result= 0.0
        
        result_grad= 0.0
        
        for isamp in range(0, p_vec.shape[0]):
            if (p_vec[isamp] > q_vec[isamp]):
                result += (p_vec[isamp] - q_vec[isamp]) ** fraction
                
                result_grad += (p_vec[isamp] - q_vec[isamp]) ** (fraction - 1)
                
            else:
                result += (q_vec[isamp] - p_vec[isamp]) ** fraction
                
                result_grad += (q_vec[isamp] - p_vec[isamp]) ** (fraction - 1)
            
        dist= result ** (1 / fraction)
                
       grad= p_vec - q_vec) ** (fraction - 1) / (1e-6 + result_grad)
        
       return dist, grad

Unfortunately, I still get the same error message. I believe that this is caused by the way the gradient is computed. When, I replace the above command line by " grad= (p_vec - q_vec) / (1e-6 + dist) " works fine.

Any suggestions on how to improve the gradient computation?

Thanks,

Ivan

**Comment by lmcinnes** [comment]
Thanks; this looks like a useful idea! In practice if you want to use the metric as a distance for the high dimensional data it would be best to submit it upstream to pynndescent. If you want to use it as an embedding metric in the output space then I would welcome a PR if you would like to submit one.

**Comment by ivan-marroquin** [comment]
Hi @lmcinnes 

Thanks for your reply. I checked other publications, and the solution is already in pyNNDescent/UMAP: make use of minkowski with 0 < p < 1.

I would like to draw your attention to other type of measurements that can be useful for dimensionality reduction tasks: https://core.ac.uk/download/pdf/38677976.pdf

Ivan
