### ISSUE TITLE
Errors with the precomputed metric

### ISSUE THREAD

**Issue by renxwise** [lmcinnes/umap#68]
Hi lmcinnes,

I tried umap on a few datasets. It works very well with metrics "euclidean", "correlation" and "cosine". But when I tested "precomputed", errors were reported as follows. Can you give any suggestions?

Best,
renxwise

ERROR messages: 
Traceback (most recent call last): 
  File "D:\ProgramsInstalled\umap-master\umap.py", line 39, in <module> 
    metric=d).fit_transform(data) 
  File "D:\ProgramsInstalled\umap-master\umap\umap_.py", line 1480, in fit_transform 
    self.fit(X) 
  File "D:\ProgramsInstalled\umap-master\umap\umap_.py", line 1413, in fit 
    dmat = pairwise_distances(X, metric=self.metric, **self.metric_kwds) 
  File "D:\Python27\lib\site-packages\sklearn\metrics\pairwise.py", line 1227, in pairwise_distances 
    X, _ = check_pairwise_arrays(X, Y, precomputed=True) 
  File "D:\Python27\lib\site-packages\sklearn\metrics\pairwise.py", line 119, in check_pairwise_arrays 
    (X.shape[0], X.shape[1], Y.shape[0])) 
ValueError: Precomputed metric requires shape (n_queries, n_indexed). Got (312, 311) for 312 indexed.

**Comment by lmcinnes** [comment]
The ``'precomputed'`` metric assumes that the ``X`` array being handed to fit is a *square* distance matrix such that the (i,j) entry is the distance between the ith sample and the jth sample. It seems that the sklearn function that handles this has found an issue with the array passed and is complaining that it does not seem to be a square distance matrix.

**Comment by renxwise** [comment]
How can I pass the distance matrix to umap? I used the following grammar. Is it correct? The distance matrix is a square matrix.

embedding = umap.UMAP(n_neighbors=30,
                     min_dist=0.1,
                     metric='precomputed').fit_transform(distance)

**Comment by lmcinnes** [comment]
That should be working then. The error your provided is from the sklearn package. Scikit-learn provides a function ``pairwise distances`` which calculates pairwise distance, or, if the metric is ``'precomputed'`` does validation checks (checks it is square, of the right dtype, etc.), and that's where things have gone astray. The relevant lines from sklearn [are here](https://github.com/scikit-learn/scikit-learn/blob/13c235359a87d0fa31a37007624add9b631c2d8b/sklearn/metrics/pairwise.py#L58-L125). Based on the error message you received in the first message it looks as if the matrix dimensions were off by one -- it was 312 by 311. I would double check your distance matrix, and if it is validly 312x312 (or 311x311) let me know and we can try to figure out what is going astray.

**Comment by renxwise** [comment]
I have found the error in my coding. I really changed the distance matrix from 312x312 to 312x311. Umap successfully produces the right output now with "precomputed".  Thanks a lot!

**Comment by lmcinnes** [comment]
Glad I could help.

**Comment by suriyaPrakashJambunathan** [comment]
from sklearn.decomposition import KernelPCA
kpca=KernelPCA(n_components=2,kernel='precomputed')
X_train=kpca.fit_transform(X_train)
X_test=kpca.transform(X_test)

I am getting an error while executing this code with KDD CUP dataset.
I got following Error


  File "<ipython-input-28-b70f0dccfa5e>", line 3, in <module>
    X_train=kpca.fit_transform(X_train)

  File "C:\Users\HP\Anaconda3\lib\site-packages\sklearn\decomposition\kernel_pca.py", line 262, in fit_transform
    self.fit(X, **params)

  File "C:\Users\HP\Anaconda3\lib\site-packages\sklearn\decomposition\kernel_pca.py", line 238, in fit
    K = self._get_kernel(X)

  File "C:\Users\HP\Anaconda3\lib\site-packages\sklearn\decomposition\kernel_pca.py", line 166, in _get_kernel
    **params)

  File "C:\Users\HP\Anaconda3\lib\site-packages\sklearn\metrics\pairwise.py", line 1390, in pairwise_kernels
    X, _ = check_pairwise_arrays(X, Y, precomputed=True)

  File "C:\Users\HP\Anaconda3\lib\site-packages\sklearn\metrics\pairwise.py", line 118, in check_pairwise_arrays
    "for %d indexed." % (X.shape[0], X.shape[1], Y.shape[0]))

ValueError: Precomputed metric requires shape (n_queries, n_indexed). Got (124411, 50) for 124411 indexed.

kindly give the solution to correct this error.

**Comment by suriyaPrakashJambunathan** [comment]
from sklearn.decomposition import KernelPCA
kpca=KernelPCA(n_components=2,kernel='precomputed')
X_train=kpca.fit_transform(X_train)
X_test=kpca.transform(X_test)

I got the following error while executing with KDD CUP Dataset 

ValueError: Precomputed metric requires shape (n_queries, n_indexed).
