### ISSUE TITLE
ImportError: cannot import name 'extend_notes_in_docstring'

### ISSUE THREAD

**Issue by PabloMessina** [lmcinnes/umap#69]
I just installed umap on Windows 10 with the command
`conda install -c conda-forge umap-learn`

Then I tried to import umap in a Jupyter Notebook
`import umap`

but the following error is raised:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-25-2f6f017ae156> in <module>()
      2 import matplotlib.pyplot as plt
      3 import glob
----> 4 import umap
      5 get_ipython().magic('aimport ExperimentUtils')

C:\Users\Pablo Messina\Anaconda3\lib\site-packages\umap\__init__.py in <module>()
----> 1 from .umap_ import UMAP
      2 
      3 import pkg_resources
      4 __version__ = pkg_resources.get_distribution('umap-learn').version

C:\Users\Pablo Messina\Anaconda3\lib\site-packages\umap\umap_.py in <module>()
      9 from sklearn.base import BaseEstimator
     10 from sklearn.utils import check_random_state, check_array
---> 11 from sklearn.metrics import pairwise_distances
     12 
     13 import numpy as np

C:\Users\Pablo Messina\Anaconda3\lib\site-packages\sklearn\metrics\__init__.py in <module>()
      5 
      6 
----> 7 from .ranking import auc
      8 from .ranking import average_precision_score
      9 from .ranking import coverage_error

C:\Users\Pablo Messina\Anaconda3\lib\site-packages\sklearn\metrics\ranking.py in <module>()
     23 import numpy as np
     24 from scipy.sparse import csr_matrix
---> 25 from scipy.stats import rankdata
     26 
     27 from ..utils import assert_all_finite

C:\Users\Pablo Messina\Anaconda3\lib\site-packages\scipy\stats\__init__.py in <module>()
    343 from __future__ import division, print_function, absolute_import
    344 
--> 345 from .stats import *
    346 from .distributions import *
    347 from .morestats import *

C:\Users\Pablo Messina\Anaconda3\lib\site-packages\scipy\stats\stats.py in <module>()
    169 import scipy.special as special
    170 import scipy.linalg as linalg
--> 171 from . import distributions
    172 from . import mstats_basic
    173 from ._distn_infrastructure import _lazywhere

C:\Users\Pablo Messina\Anaconda3\lib\site-packages\scipy\stats\distributions.py in <module>()
     11                                     rv_frozen)
     12 
---> 13 from . import _continuous_distns
     14 from . import _discrete_distns
     15 

C:\Users\Pablo Messina\Anaconda3\lib\site-packages\scipy\stats\_continuous_distns.py in <module>()
      9 import numpy as np
     10 
---> 11 from scipy.misc.doccer import (extend_notes_in_docstring,
     12                                replace_notes_in_docstring)
     13 from scipy import optimize

ImportError: cannot import name 'extend_notes_in_docstring'

**Comment by PabloMessina** [comment]
Yes, you are right. The problem must be in sklearn/scipy. The weird thing is that I've never had problems importing stuff from sklearn before. However, it seems that when I installed umap, many dependencies were installed / updated, inclusing scikit-learn and scipy, as shown in the screenshot below:

![imagen](https://user-images.githubusercontent.com/6187545/39961743-3d18daae-5613-11e8-9c7a-bf1740abd274.png)

Maybe something got broken with the dependencies updates?

**Comment by PabloMessina** [comment]
Sorry, I figured out the problem. I forgot to restart the Jupyter Notebook's kernel. That was it. Now it works like a charm. Sorry again for such a rookie mistake (and for unnecessarily worrying you). Feel free to close this issue haha

**Comment by lmcinnes** [comment]
Not to worry, I'm just glad the problem got resolved!
