### ISSUE TITLE
umap from within docker

### ISSUE THREAD

**Issue by chasemc** [lmcinnes/umap#715]
I think this is a numba issue and not a umap issue but wanted to document this here in case someone else runs into this. 
I spent some hours today dealing with an error after updating a docker image that contains a python package that has umap as a dependency. 

I don't have a small example because this is being called from a python package, from nextflow, within a docker container. 

Removing '-u $(id -u):$(id -g)' from the docker command fixed the issue.

```
Command error:
  Traceback (most recent call last):
    File "/opt/conda/bin/autometa-kmers", line 33, in <module>
      sys.exit(load_entry_point('Autometa==2.0.0a0', 'console_scripts', 'autometa-kmers')())
    File "/opt/conda/bin/autometa-kmers", line 25, in importlib_load_entry_point
      return next(matches).load()
    File "/opt/conda/lib/python3.8/importlib/metadata.py", line 77, in load
      module = import_module(match.group('module'))
    File "/opt/conda/lib/python3.8/importlib/__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "/opt/conda/lib/python3.8/site-packages/Autometa-2.0.0a0-py3.8.egg/autometa/common/kmers.py", line 44, in <module>
      from umap import UMAP
    File "/opt/conda/lib/python3.8/site-packages/umap/__init__.py", line 1, in <module>
      from .umap_ import UMAP
    File "/opt/conda/lib/python3.8/site-packages/umap/umap_.py", line 53, in <module>
      from umap.layouts import (
    File "/opt/conda/lib/python3.8/site-packages/umap/layouts.py", line 39, in <module>
      def rdist(x, y):
    File "/opt/conda/lib/python3.8/site-packages/numba/decorators.py", line 193, in wrapper
      disp.enable_caching()
    File "/opt/conda/lib/python3.8/site-packages/numba/dispatcher.py", line 679, in enable_caching
      self._cache = FunctionCache(self.py_func)
    File "/opt/conda/lib/python3.8/site-packages/numba/caching.py", line 614, in __init__
      self._impl = self._impl_class(py_func)
    File "/opt/conda/lib/python3.8/site-packages/numba/caching.py", line 348, in __init__
      raise RuntimeError("cannot cache function %r: no locator available "
  RuntimeError: cannot cache function 'rdist': no locator available for file '/opt/conda/lib/python3.8/site-packages/umap/layouts.py'
  ```

May be related to https://github.com/numba/numba/issues/5566

**Comment by shashankgaur3** [comment]
I am running into a similar issue, not able to resolve it. Can you paste the updated docker command here. I am using rapids ai container docker image rapidsai/rapidsai-core:22.08-cuda11.5-runtime-centos7-py3.9

`---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-1c405e3e7412> in <cell line: 3>()
      1 from cuml.cluster import HDBSCAN
      2 from cuml.manifold import UMAP
----> 3 from bertopic import BERTopic
      4 from sklearn.datasets import fetch_20newsgroups
      5 #from sklearn.datasets import get_data_home

/opt/dataiku/code-env/lib/python3.9/site-packages/bertopic/__init__.py in <module>
----> 1 from bertopic._bertopic import BERTopic
      2 
      3 __version__ = "0.12.0"
      4 
      5 __all__ = [

/opt/dataiku/code-env/lib/python3.9/site-packages/bertopic/_bertopic.py in <module>
     22 # Models
     23 import hdbscan
---> 24 from umap import UMAP
     25 from sklearn.preprocessing import normalize
     26 from sklearn import __version__ as sklearn_version

/opt/dataiku/code-env/lib/python3.9/site-packages/umap/__init__.py in <module>
      1 from warnings import warn, catch_warnings, simplefilter
----> 2 from .umap_ import UMAP
      3 
      4 try:
      5     with catch_warnings():

/opt/dataiku/code-env/lib/python3.9/site-packages/umap/umap_.py in <module>
     40 )
     41 from umap.spectral import spectral_layout
---> 42 from umap.layouts import (
     43     optimize_layout_euclidean,
     44     optimize_layout_generic,

/opt/dataiku/code-env/lib/python3.9/site-packages/umap/layouts.py in <module>
     38     },
     39 )
---> 40 def rdist(x, y):
     41     """Reduced Euclidean distance.
     42 

/opt/dataiku/code-env/lib/python3.9/site-packages/numba/core/decorators.py in wrapper(func)
    210                           **dispatcher_args)
    211         if cache:
--> 212             disp.enable_caching()
    213         if sigs is not None:
    214             # Register the Dispatcher to the type inference mechanism,

/opt/dataiku/code-env/lib/python3.9/site-packages/numba/core/dispatcher.py in enable_caching(self)
    861 
    862     def enable_caching(self):
--> 863         self._cache = FunctionCache(self.py_func)
    864 
    865     def __get__(self, obj, objtype=None):

/opt/dataiku/code-env/lib/python3.9/site-packages/numba/core/caching.py in __init__(self, py_func)
    599         self._name = repr(py_func)
    600         self._py_func = py_func
--> 601         self._impl = self._impl_class(py_func)
    602         self._cache_path = self._impl.locator.get_cache_path()
    603         # This may be a bit strict but avoids us maintaining a magic number

/opt/dataiku/code-env/lib/python3.9/site-packages/numba/core/caching.py in __init__(self, py_func)
    335                 break
    336         else:
--> 337             raise RuntimeError("cannot cache function %r: no locator available "
    338                                "for file %r" % (qualname, source_path))
    339         self._locator = locator

RuntimeError: cannot cache function 'rdist': no locator available for file '/opt/dataiku/code-env/lib/python3.9/site-packages/umap/layouts.py'`

**Comment by zhimin-z** [comment]
I have exactly the same issue, unable to resolve it....

**Comment by zhimin-z** [comment]
Does https://github.com/numba/numba/issues/4908 work as a patch?

**Comment by shashankgaur3** [comment]
@zhimin-z I was able to resolve it by setting the NUMBA cache dir at a location with write access in the container:

`dir = os.path.join(pwd.getpwuid(os.getuid()).pw_dir, ".cache", "numba")
os.environ["NUMBA_CACHE_DIR"] = dir
os.makedirs(dir, exist_ok=True)`
