### ISSUE TITLE
Get X and Y coordinates from a UMAP

### ISSUE THREAD

**Issue by keshav-b** [lmcinnes/umap#716]
```
np.random.seed(42)
data = np.random.rand(800, 4)
fit = umap.UMAP().fit(data)
umap.plot.points(fit)
plt.show()
```

This is reduces the dimension of the input data and plot it on a 2D surface, but how can I get the X, Y coordinates of the plot?

**Comment by lmcinnes** [comment]
the attribute ``fit.embedding_`` contains the coordinates of the result.
