### ISSUE TITLE
UMAP reduces 10 PCs into 2 dimensional summary data?

### ISSUE THREAD

**Issue by jielab** [lmcinnes/umap#732]
Hi, guys:

Previously I have been using PCA software to derive 10 PCs from a genotype dataset (usually with tens of thousands of independent SNPs). Some other people derive more PCS. For example, the UK Biobank genotype data comes with 40 PCs.

I am now puzzled with a basic (and probably naive) question: does UMAP work like PCA software that begin with a genotype data with tens of thousands of indepdentent SNPs, or UMAP begin with a numeric dataset such as the 40 PCs coming with the UK Biobank data. The PENGUIN example dataset have 4 columns of numerical values. I don't see much value to reduce the dimension from 4 to 2.

Since the plots in the UMAP online documentation are all shown in 2-D scatter-plot, does this mean that UMAP only output 2-D data? For PCA, we can ask the software to output any number of dimensions, such as 10 PCs or 40 PCs.

Thank you very much & best regards,
Jie

**Comment by jlmelville** [comment]
Hi Jie:

* Reducing the dimensionality before applying UMAP is unnecessary and not recommended. Avoid doing PCA to reduce the dimensionality if you can.
* The value of reducing the penguin dataset to two dimensions is so you can visualize it simply (which is, I suspect, the use case for the vast majority of users of UMAP).
* If you want to reduce the dimensionality to a different output dimensionality, set the `n_components` parameter to a value other than `2` (e.g. `10` or `40`).

**Comment by jielab** [comment]
Thanks, James! 

![pgen 1008432 g001](https://user-images.githubusercontent.com/26947455/126728724-3b16ee59-2bc4-4e96-8f4f-f93b75b4386c.png)

The above is an **Figure 1** from this paper https://journals.plos.org/plosgenetics/article?id=10.1371/journal.pgen.1008432.  The **plot D** of this Figure has the best stratification capacity, and it is "**on the first 15 principal components**." The **Figure 2** and **Figure 3** of this paper are also based on the **top N PCs**, not based on raw genotype data. So, it seems a reasonble approach that people run PCA first and then run UMAP on top of top PCs.

I understand that PCA and UMAP have differences in terms of methods and computational requirements. But simply **from the perspective of analysis output**, they are basically the same, correct? That is, both can reduce a high dimensional data (such as tens of thousands of SNPs) into very low dimension (10 PCs or 2 UMAPs). For example, we could either run a second PCA or a new UMAP, after we first used PCA to generate 10-PCs, correct?

Finally, I am trying to follow the documentation at https://umap-learn.readthedocs.io/en/latest/basic_usage.html, I use Ubuntu Linux coming with Windows 10.  But I encoutered two errors:

- 1. "%matplotlib inline" gives an error message of "SyntaxError: invalid syntax". 
- 2. "sns.pairplot(penguins, hue='species_short')" only gave an text output of "<seaborn.axisgrid.PairGrid object at 0x7f4bbfe30a00>", instead of displaying a Figure.

Can you please kindly let me know how to resolve this?

Thank you & best regadrs,
jie

**Comment by jlmelville** [comment]
> So, it seems a reasonble approach that people run PCA first and then run UMAP on top of top PCs.

Sorry for causing confusion. Let's distinguish between two cases:

1. Do you *have* to use principal component data as input to UMAP? No.
2. *Can* you use principal component data as input to UMAP? Yes.

I'm *not* saying "don't run PCA on your RNA sequencing data": there are all sorts of reasons why you might want to and one of the results may be that if you choose to visualize that data, the resulting UMAP will look better. 

I *am* saying "you are not obliged to run PCA on your RNA sequencing data before attempting to visualize it with UMAP".

> For example, we could either run a second PCA or a new UMAP, after we first used PCA to generate 10-PCs, correct?

You could. I don't know if PCA followed by PCA is a great idea though.

> Finally, I am trying to follow the documentation at https://umap-learn.readthedocs.io/en/latest/basic_usage.html, I use Ubuntu Linux coming with Windows 10. But I encoutered two errors:
> 
> * 1. "%matplotlib inline" gives an error message of "SyntaxError: invalid syntax".
> * 1. "sns.pairplot(penguins, hue='species_short')" only gave an text output of "<seaborn.axisgrid.PairGrid object at 0x7f4bbfe30a00>", instead of displaying a Figure.
> 
> Can you please kindly let me know how to resolve this?

Probably, you aren't running that in a Python notebook. Visit <https://jupyter.org/> to learn more.

**Comment by jielab** [comment]
Dear James:

Thank you very much!  

For your last comment "P_robably, you aren't running that in a Python notebook. Visit https://jupyter.org/ to learn more", do you mean that I should install **Jupyter notebook** (https://jupyter.org/install.html)? 

Can I install this to Windows 10 directly, or I have to install it into the Windows 10 Ubuntu Linux sub-system? 

Sorry, if this is a naive question and is wasting your time. I tried to only ask intelligent and necessary questions, after I did my due diligence first but still could not find the answer.

Best regards,
Jie

**Comment by jlmelville** [comment]
> do you mean that I should install **Jupyter notebook** (https://jupyter.org/install.html)?

yes.

> Can I install this to Windows 10 directly, or I have to install it into the Windows 10 Ubuntu Linux sub-system?

if you installed UMAP and its dependencies on the Windows 10 Linux sub-system, then also install Jupyter lab/notebook there (e.g. using `pip`).

**Comment by jielab** [comment]
Dear James:

Thanks! Previously, I usually user Windows 10 only for Office type of software, while Linux for data processing type of computational tasks.

If I install Jupyter lab and UMAP and python dependencies on Linux sub-system, I am afraid that I still won't be able to generate a plot from the Linux system, even when I run Jupyter on top of Linux.  Take R for example, in Windows version R, I type "plot(cars$speed)" and I will get a plot. However, in Linux, after I type "R" to run R on top of Linux and then type "plot(cars$speed)", it will generate nothing. I have to use "png()" to save that to a plot and then open it in Windows.

So, LInux does not output a plot directly from a command line. That is my question. I shall do more research into this myself, since this is not really a UMAP question :- )

Best regards,
Jie

**Comment by jlmelville** [comment]
> If I install Jupyter lab and UMAP and python dependencies on Linux sub-system, I am afraid that I still won't be able to generate a plot from the Linux system, even when I run Jupyter on top of Linux.

I wouldn't worry: Jupyter runs in a web browser window. When I run it from the Windows subsystem for Linux command line, it opens a new tab in my browser running on Windows itself.

**Comment by jielab** [comment]
Great. Try it out now :- )

**Comment by jielab** [comment]
Dear James:

Please see my screenshot below. After I typed the command for installing and running jupyter, somehow I got an powershell.exe window, where I could not type anything.

![1](https://user-images.githubusercontent.com/26947455/126861250-e8c9bf3a-1104-409c-82e9-974c964f47c9.PNG)

![2](https://user-images.githubusercontent.com/26947455/126861252-bc33938f-8df4-4541-b4a4-a5f6dca073ba.PNG)

When I open up a new Linux shell and type the same python commands for UMAP, I got the same two errors as mentioned previously.

Best regards,
Jie

**Comment by jlmelville** [comment]
It works for me on the latest version of Windows 10/WSL. Maybe you don't have a default Windows browser defined? Anyway, I would experiment with getting things working with `pip` rather than `conda` (e.g. do `pip install jupyterlab`). Then when you run `jupyter-lab`, you should eventually get a message in your Linux terminal which tells you to paste a URL that looks like: `http://localhost:8888/lab?token=<some-long-token-here>`. 

Anyway, at this point your problem is with getting your notebook environments running, and I don't know much about that.

**Comment by janxkoci** [comment]
> Anyway, at this point your problem is with getting your notebook environments running, and I don't know much about that.

In that case, @jlmelville, maybe it was more helpful to show how a regular seaborn plot can be made in regular python environment, rather than telling the user to install something you're not comfortable helping with 😉

I'm not a Python user (I use Jupyter with R), so I cannot help with that specific plot issue, but making such plots should be easy without Jupyter notebooks...
