### ISSUE TITLE
UMAP to analyze ~2 million SARS-COV-2 genomes

### ISSUE THREAD

**Issue by jielab** [lmcinnes/umap#740]
Dear James:

Previously I learned to use “jupyter lab –no-browser” and then manually open up a  web browser to get Jupyter lab up running. I could type python commands on the web interface and display plots immediately. That’s nice! However, I suspect that running big amount of data on a web interface might be VERY slow, and it can’t be integrated into my other Linux Bash pipeline scripts. So, can I still put all UMAP commands in a single python file and then run that python file on terminal? I don’t need to display the images in real time. It is OK to put them into PDF or JPEG files, just like how we could do it in R. If this is doable, can you please let me know what is the UMAP command to save output images to files?

The UMA documentation used the penguin dataset and the digit dataset as example. However, UMAP might be especially powerful to analyze the dataset of SARS-COV-2, which is affecting all of us, for so long. I read a Lancet Digital Health paper on how UMAP could be used to study SARS-COV-2 (https://github.com/hsmaan/CovidGenotyper). Unfortunately, the tool of that paper (https://covidgenotyper.app)  is “under maintenance”. So, I am trying to pick this up myself. I am keen to make UMAP work for analysis of SARS-COV-2. I now put an example GISAID dataset (the first 20 virus genome) on this link 
https://drive.google.com/file/d/1RlaPDbvwiYTJ5-gr0z7ZM3dh2ASyQEy7/view?usp=sharing. Can you please kindly let me know what UMAP command I should use to read such a FASTA file? 

If you are aware of an existing tutorial on using UMAP for SARS-COV-2 data, please kindly let me know.  I hope that UMAP is computationally efficient enough to analyze the ~2 million virus genomes currently in GISAID?

Thank you & Best regards,
Jie

**Comment by jlmelville** [comment]
Saving images is nothing to do with UMAP. The function name depends on what package you decide to use to display those images. You'll need to research that yourself.

Reading different file formats is also nothing to do with UMAP. If you can create a Pandas dataframe from the input data you will be in good shape. But again you will need to research that yourself in the case of FASTA files.

> I hope that UMAP is computationally efficient enough to analyze the ~2 million virus genomes currently in GISAID?

I assume that it is feasible with a sufficiently powerful computer. But it will depend on both the number of rows and the number of columns in your dataset. Try it and find out. But I suggest starting with a dataset in the range of 10,000 rows or so before attempting anything larger.
