### ISSUE TITLE
UMAP in R package

### ISSUE THREAD

**Issue by jielab** [lmcinnes/umap#744]
Dear James:

Sorry to bother again. I try to be brief.

Since I don't know python programming, I could not really take advantage of the UMAP tutorial on this site.

Instead, I am quite experienced with R. I searched Google and found that R package for UMAP ( 
https://cran.r-project.org/web/packages/umap/umap.pdf). However, this R documention is really short, only described umap(), predict.umap(), and umap.knn() in limited details. This made me wonder that R is not ideal for runnning UMAP. Am I right?

I also noticed there is a umpr R package, https://www.rdocumentation.org/packages/umapr/versions/0.0.0.9001. But this time, the example even did not work. So, I guess it is something not well adopted.

So, can you please help with my question: can I use R to run UMAP? Specifically, I want to use UMAP to analyze the SARS-COVS-2 virus data.

Thank you very much & best regards,
Jie

**Comment by jlmelville** [comment]
Hi Jie, [umapr](https://github.com/ropensci-archive/umapr) is no longer maintained so don't use that. But the [umap](https://cran.r-project.org/package=umap) package CRAN page shows it has several `Reverse imports` and `Reverse suggests` entries, which means there are lots of other packages making use of it.

**Comment by jielab** [comment]
Dear James:

Thank you very much! I will not use umapr then.

So, you think that I could just use UMAP R package to do pretty much what can be done with the native UMAP python package?

Best regards,
Jie

**Comment by jlmelville** [comment]
> So, you think that I could just use UMAP R package to do pretty much what can be done with the native UMAP python package?

The `umap` package provides an R interface to this Python package (as well as a native R implementation), so the answer is "probably" but I haven't used it a lot. This is the sort of question that is best answered by working out what you want to do with UMAP and then trying it.

**Comment by jielab** [comment]
OK, I see. i wish there is a comprehensive tutorial for the R version of UMAP. But I will try things out.

Best regadrs,
Jie

**Comment by jielab** [comment]
Dear James:

it seems that the UWOT R package is quite similar to UMAP. I think this UWOT R package is also created by you https://github.com/jlmelville/uwot, correct?

Best regards,
Jie

**Comment by jlmelville** [comment]
> I think this UWOT R package is also created by you https://github.com/jlmelville/uwot, correct?

Yes. It does not have all the features of this UMAP Python package so I would never recommend uwot in favor of the official Python version, but if you are more comfortable working with R it might do what you want. If you have problems with installing or running it, please open an issue at <https://github.com/jlmelville/uwot/issues>.

**Comment by jielab** [comment]
thanks! will do.
