### ISSUE TITLE
Doesn't install on Mac M1

### ISSUE THREAD

**Issue by smortezah** [lmcinnes/umap#745]
Trying to install the package on Mac M1, I receive the following error:

"PackagesNotFoundError: The following packages are not available from current channels:

  - umap-learn

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch"

**Comment by lmcinnes** [comment]
I have added the relevant pckages to a list for conda-forge to eventually update. I'm not sure when that will happen, but hopefully in the not too distant future.

**Comment by lmcinnes** [comment]
That I may not be able to help with. I am relying on the work of the conda-forge team to do all the packaging, and if the processing they have doesn't package for M! with python <= 3.9 then there isn't a lot I can do about that. You can always try installing directly from source.

**Comment by gregsskyles** [comment]
FWIW, this guy says you can install Python 3.9 and TensorFlow on the Mac M1-

https://www.youtube.com/watch?v=_CO-ND1FTOU

**Comment by smortezah** [comment]
@gregsskyles Watching the video, I was able to install Python 3.9, Tensorflow and finally umap on my Mac M1. 🙏

**Comment by gregsskyles** [comment]
Great, I'm glad it worked! Thanks for letting us know.
