### ISSUE TITLE
Is there a way to know to which component each point was clustered?

### ISSUE THREAD

**Issue by loySoGxj** [lmcinnes/umap#756]
I may not be familiar with the algorithm, but
Is there any way to know to which components each point was clustered?
Maybe I've heard the obvious, but I'd appreciate it if you could answer.

**Comment by Hackathorn** [comment]
From [link](https://umap-learn.readthedocs.io/en/latest/parameters.html#n-components), "UMAP provides a n_components parameter option that allows the user to determine the dimensionality of the reduced dimension space we will be embedding the data into." IOW each point is embedded in a latent space of 'n_components' dimensions, which is usually 2 or 3 for visualization. To cluster points which may be 'close' together in this latent space is a different analysis.
