### ISSUE TITLE
Aligned UMAP is not reproducible

### ISSUE THREAD

**Issue by martyn1fyles** [lmcinnes/umap#757]
Hi,

It looks like setting random state does not produce reproducible outputs when using AlignedUMAP. Different outputs of the algorithm are produced upon consecutive runs of the algorithm.

Code example:

```
import numpy as np
import sklearn.datasets
import umap
import umap.plot
import umap.utils as utils
import umap.aligned_umap
import matplotlib.pyplot as plt
digits = sklearn.datasets.load_digits()
from copy import copy

ordered_digits = digits.data[np.argsort(digits.data.sum(axis=1))]
ordered_target = digits.target[np.argsort(digits.data.sum(axis=1))]

slices = [ordered_digits[150 * i:min(ordered_digits.shape[0], 150 * i + 400)] for i in range(10)]

relation_dict = {i+150:i for i in range(400-150)}
relation_dicts = [relation_dict.copy() for i in range(len(slices) - 1)]

aligned_mapper = umap.AlignedUMAP(random_state=42).fit(slices, relations=relation_dicts)
embedding_1 = copy(aligned_mapper.embeddings_)

aligned_mapper = umap.AlignedUMAP(random_state=42).fit(slices, relations=relation_dicts)
embedding_2 = copy(aligned_mapper.embeddings_)

np.all(np.equal(embedding_1, embedding_2))
```

The intended behavior is that the outputted embedding's should be the same, since they were both produce by an AlignedUMAP object with defined random state. However, the outputted embeddings are different every time - as a result we cannot reproduce the results of AlignedUMAP.

Example code from https://umap-learn.readthedocs.io/en/latest/aligned_umap_basic_usage.html

**Comment by jh83775** [comment]
Can you try installing from github to see if that resolves the issue?
```pip install --upgrade --no-deps --force-reinstall  git+https://github.com/lmcinnes/umap```

**Comment by martyn1fyles** [comment]
That seemed to fix it for me. Thanks!
