### ISSUE TITLE
Font size in Popup on iOS

### ISSUE THREAD

**Issue by rikutaromanabe** [lmcinnes/umap#762]
When content is displayed in a popup, if there are images, the font size will be larger. This happens only on iOS and does not happen when there are very few text. Also, if I change the height and width once, it goes away.
Is it possible to fix it?

**Comment by lmcinnes** [comment]
Are you talking about ``umap.plot.interactive``? Sorry, but it isn't quite clear which component you are talking about.

**Comment by rikutaromanabe** [comment]
Sorry, I posted in the wrong thread.
