### ISSUE TITLE
omp_set_nested routine deprecated

### ISSUE THREAD

**Issue by robinvndaele** [lmcinnes/umap#764]
For an experiment I need to track the computation time of a modified version of UMAP.
For this I mainly need the **_fuzzy_simplicial_set_** function from **_umap.umap__**.

However, the first time this function runs takes some time, and I get the following message:

**_OMP: Info #276: omp_set_nested routine deprecated, please use omp_set_max_active_levels instead._**

Running the same function a second time is much faster and gets rid of the warning.

Thus, my question is: how can I get rid or hide the warning, and ensure the correct initialization has been done before I start tracking time, so that I always get similar running times? I tried looking into the source code thoroughly and searching online, from which I suspect this issue is related to **_numba_**, but I cannot seem to find a solution...

Example (at least for me):  

```
import time
import numpy as np
from umap.umap_ import fuzzy_simplicial_set

X = np.array(np.random.rand(100, 5))

start_time = time.time()
fuzzy_simplicial_set(X, n_neighbors=15, random_state=None, metric="euclidean")
print("Time: " + time.strftime("%H:%M:%S", time.gmtime(time.time() - start_time)))
```

First time: warning & ~10 seconds
Second time: no warning & ~0 seconds.

**Comment by robinvndaele** [comment]
Update:

Setting parallel=false in @numba.njit before the called helper functions seems to get rid of the warning for me.

Now I only need to find how I can subtract the numba compilation times from my execution times...

(Not a big numba expert.)

**Comment by lmcinnes** [comment]
The easiest way to check timing not involving compilation is to run the function once (which induces the compile) and then time a second run of the function.

**Comment by robinvndaele** [comment]
Indeed, that's what I currently do: just do a first call on some random data after my import. Good enough for now. 

Thanks!
