### ISSUE TITLE
Feature request - inverse_transform function from umap-learn lib

### ISSUE THREAD

**Issue by ktatar** [lmcinnes/umap#769]
Hello, 

It would be super useful for some implementations if this library would have the inverse_transform function. Here is the function in umap-learn cpu lib:

https://umap-learn.readthedocs.io/en/latest/api.html?highlight=inverse_transform#umap.umap_.UMAP.inverse_transform

Thank you,

**Comment by lmcinnes** [comment]
This is the implementation that those docs are referring to. Perhaps you wanted the GPU implementation in RAPIDs, or one of the implementations in a different language (R or Julia)?

**Comment by ktatar** [comment]
ahhh, my apologies. Too many tabs get confusing sometimes. I added this feature request to the cuml repo. Thanks for the heads-up.
