### ISSUE TITLE
umap vs google maps - misplaced vertices of 'circle'

### ISSUE THREAD

**Issue by aillusions** [lmcinnes/umap#77]
Same coordinates are rendered differently in the two systems:

![image](https://user-images.githubusercontent.com/273321/42246691-33a9d0f4-7f26-11e8-85fc-ab4c65822010.png)

![image](https://user-images.githubusercontent.com/273321/42246699-39a02dd2-7f26-11e8-9ed6-e8c1204a2af9.png)

[
	[
		8.5151,
		47.16530837158007
	],
	[
		8.515275261046382,
		47.16529091747498
	],
	[
		8.515443786909037,
		47.165239225910796
	],
	[
		8.515599101233576,
		47.16515528336549
	],
	[
		8.51573523537761,
		47.16504231570411
	],
	[
		8.515846957782324,
		47.16490466421044
	],
	[
		8.515929975018363,
		47.16474761875418
	],
	[
		8.515981096779901,
		47.16457721450411
	],
	[
		8.515998358486314,
		47.1644
	],
	[
		8.515981096779901,
		47.164222785495895
	],
	[
		8.515929975018363,
		47.164052381245824
	],
	[
		8.515846957782324,
		47.16389533578956
	],
	[
		8.51573523537761,
		47.16375768429589
	],
	[
		8.515599101233576,
		47.16364471663451
	],
	[
		8.515443786909037,
		47.163560774089206
	],
	[
		8.515275261046382,
		47.163509082525024
	],
	[
		8.5151,
		47.16349162841993
	],
	[
		8.514924738953619,
		47.163509082525024
	],
	[
		8.514756213090964,
		47.163560774089206
	],
	[
		8.514600898766425,
		47.16364471663451
	],
	[
		8.51446476462239,
		47.16375768429589
	],
	[
		8.514353042217676,
		47.16389533578956
	],
	[
		8.514270024981638,
		47.164052381245824
	],
	[
		8.5142189032201,
		47.164222785495895
	],
	[
		8.514201641513687,
		47.1644
	],
	[
		8.5142189032201,
		47.16457721450411
	],
	[
		8.514270024981638,
		47.16474761875418
	],
	[
		8.514353042217676,
		47.16490466421044
	],
	[
		8.51446476462239,
		47.16504231570411
	],
	[
		8.514600898766425,
		47.16515528336549
	],
	[
		8.514756213090964,
		47.165239225910796
	],
	[
		8.514924738953619,
		47.16529091747498
	],
	[
		8.5151,
		47.16530837158007
	]
]

Is this map configuration issue?

thanks

**Comment by lmcinnes** [comment]
I think perhaps you are looking for the uMap project (
https://github.com/umap-project/umap); if that's not the case it would be
helpful if you could clarify the issue -- what was the original data you
were applying dimension reduction to? What was the expected result?

**Comment by aillusions** [comment]
Oh, I see
thank you for quick response

[https://github.com/umap-project/umap/issues/597](https://github.com/umap-project/umap/issues/597)
