### ISSUE TITLE
Are umap-learn compatible with python 3.4.8 version?

### ISSUE THREAD

**Issue by shemlim** [lmcinnes/umap#78]
I have problem with pip install, not on my local but in a server...
I have tried to install but failed, is my python version is not supported with needed package of installation like numba,scipy,and other?

**Comment by lmcinnes** [comment]
It should work fine with python 3.4.8. It may be an incompatibility among
some of the other installed libraries? Or the architecture? I know numba
doesn't work so well on 32bit windows machines (although I thought it does
at least install). I think I would need more detail about what the failure
actually is.

**Comment by sleighsoft** [comment]
Seems to be a stale issue. If you have any more problems please open a new issue @shemlim.
