### ISSUE TITLE
unexpected UMAP embeddings with 0.5.2 release using single-cell gene expression data via Scanpy

### ISSUE THREAD

**Issue by cornhundred** [lmcinnes/umap#798]
Hi, we are seeing unexpected UMAP embeddings using the 0.5.2 umap-learn version, run via Scanpy, with our single cell gene expression data ([publicly available MERFISH data from Vizgen](https://vizgen.com/support/data-release-program/)). 

Our original embedding using version 0.5.1 looks like 

![Screen Shot 2021-10-29 at 3 46 04 PM](https://user-images.githubusercontent.com/8352840/139493436-078559d2-13bc-4b79-a28a-d471065eb463.png)

and the embedding with 0.5.2 looks like 

![Screen Shot 2021-10-29 at 3 46 24 PM](https://user-images.githubusercontent.com/8352840/139493454-3b379c05-0813-4b14-8189-ba5d40b4993e.png)

Zooming into the 0.5.2 embedding reveals that cells appear to be embedded into a lattice like structure

![Screen Shot 2021-10-29 at 3 46 57 PM](https://user-images.githubusercontent.com/8352840/139493581-632b5e81-2069-4127-a7a6-4c7525ee2be5.png)

We're wondering if this is being caused in part by some sort of a rounding error in the embedding.

We have included Colab notebooks demonstrating the normal behavior using version 0.5.1 and the new unexpected behavior using version 0.5.2. Please let us know if you have any issues running the notebooks - they require authentication via Google to load the publicly available data and there are static and interactive versions of the UMAP embeddings.

* [Colab UMAP-Learn_0.5.1.ipynb](https://colab.research.google.com/drive/1HLn30iJCVFHe3D5fJfOuso7fJN3Qw1bh?usp=sharing) 

* [Colab UMAP-Learn_0.5.2.ipynb](https://colab.research.google.com/drive/10SL3bLyl70IenrcSQr6c3Ba0Cjbm__Kv?usp=sharing)

The only differences between the notebooks are where we use pip to install a specific version of umap-learn or use Scanpy's version. 

```
# pinning to previous 0.5.1 version
# otherwise scanpy grabs umap-learn==0.5.2 (see below)
###########################################
!pip install -q umap-learn==0.5.1
```

We also tested using the [basic usage](https://umap-learn.readthedocs.io/en/latest/basic_usage.html) examples from the documentation and these examples appear to be working with the new 0.5.2 version - see colab notebook [Basic_Usage_Test-UMAP_0.5.2.ipynb](https://colab.research.google.com/drive/1zSkGLbFUSGA3I5Q9mIGBFEBHUSGH-GQ4?usp=sharing)

**Comment by cornhundred** [comment]
We can also reproduce this issue using the Scanpy [pbmc3k tutorial example](https://scanpy-tutorials.readthedocs.io/en/latest/pbmc3k.html) 

* colab notebook [scanpy_pbmc3k_umap-learn_0.5.1.ipynb](https://colab.research.google.com/drive/1kAPRClaUWoZdao458Q_6fwnxQaQ4xwsP?usp=sharing)


![Screen Shot 2021-10-29 at 4 25 46 PM](https://user-images.githubusercontent.com/8352840/139497658-454d28e8-1988-4e1e-8014-2d234348d271.png)

* colab notebook [scanpy_pbmc3k_umap-learn_0.5.2.ipynb](https://colab.research.google.com/drive/1_J5Kzx-Qja_rIvCW3ziAamgdagq2x0op?usp=sharing)
![Screen Shot 2021-10-29 at 4 25 52 PM](https://user-images.githubusercontent.com/8352840/139497674-93d80465-5c2c-4865-a0d3-04dde2a76b17.png)

**Comment by lmcinnes** [comment]
That is definitely disconcerting. I'll try to look into what the issue may be. It looks rather like you are just getting the spectral initialization instead of the UMAP embedding out.

**Comment by lmcinnes** [comment]
So first of all basic UMAP seems to be working and doesn't produce results like this (as you note that the basic usage tutorial seems to work). That's a good start, as at least the package itself isn't broken. That means it is most likely in the interaction of scanpy and UMAP.

My best guess, on first glance, is that some parameter options may have shuffled around. Ideally everything should be keyword only (I haven't followed scikit-learn in enforcing that and making that standard yet, but this is a good reason why I should), but if it is positionally called in scanpy that *might* be the problem.

**Comment by lmcinnes** [comment]
Alright, I think I see the problem. Included in 0.5.2 is commit e442bcd9323fd218fc4a3a6287baa1067512dfe1 which allows ``n_epochs`` to be zero to get the initial embedding out, which several people wanted. Unfortunately internally to scanpy they set ``n_epochs = 0`` which *used to be* a way to get an automatically set value. That now needs to be ``n_epochs=None``. You can work around this right now by setting ``maxiter`` in the scanpy call. A value of 200 is probably good.

**Comment by cornhundred** [comment]
Thanks @lmcinnes for the quick response. Would you all want to roll back that change since it effectively changed the API, but the version name would be interpreted as only a bug fix. Otherwise Scanpy will have to roll out some sort of update.

**Comment by lmcinnes** [comment]
It was an update to a function that isn't part of the public facing API, so I was not anticipating issues. I've submitted a change to scanpy that should resolve the issue. I would be happy to discuss options, but would rather not make a roll-back release if I don't have to.

**Comment by cornhundred** [comment]
Ok that makes sense. Thanks again for the quick response

**Comment by cornhundred** [comment]
Closing since this is something that Scanpy will resolve.
