### ISSUE TITLE
Invalid escape sequence spam...

### ISSUE THREAD

**Issue by brilee** [lmcinnes/umap#805]
I'm seeing lots of warnings of the following kind when I import the umap library:

umap/distances.py:102: DeprecationWarning: invalid escape sequence \s
umap/distances.py:117: DeprecationWarning: invalid escape sequence \m
umap/distances.py:131: DeprecationWarning: invalid escape sequence \m

I believe this can be fixed with an `r` prefix on all the triple-quoted docstrings that have inline LaTeX containing backslashes.

**Comment by lmcinnes** [comment]
Yes, thanks. If you want to make a PR I would gladly merge it; otherwise I will hopefully get to this at some point soon,

**Comment by brilee** [comment]
for future reference, to reproduce the escape sequences, run the following under python<=3.8: `rm -r umap/__pycache__/ && python -Wd -c "import umap"`
