### ISSUE TITLE
Error while trying to import umap.plot: __init__() got multiple values for keyword argument 'allow_None'

### ISSUE THREAD

**Issue by AlArths** [lmcinnes/umap#855]
UMAP works well when I plot the results with matplotlib but I have tried to use  umap.plot as mentioned in the documentation but I face this issue:

" TypeError                                 Traceback (most recent call last)
<ipython-input-11-d5cd787c20a7> in <module>
----> 1 import umap.plot

~/.local/lib/python3.8/site-packages/umap/plot.py in <module>
     16     import bokeh.transform as btr
     17     import holoviews as hv
---> 18     import holoviews.operation.datashader as hd
     19 except ImportError:
     20     warn(

~/.local/lib/python3.8/site-packages/holoviews/operation/datashader.py in <module>
   1806 
   1807 
-> 1808 class inspect(Operation):
   1809     """
   1810     Generalized inspect operation that detects the appropriate indicator

~/.local/lib/python3.8/site-packages/holoviews/operation/datashader.py in inspect()
   1829        samples will be searched.""")
   1830 
-> 1831     hits = param.DataFrame(default=pd.DataFrame(), allow_None=True)
   1832 
   1833     max_indicators = param.Integer(default=1, doc="""

~/.local/lib/python3.8/site-packages/param/__init__.py in __init__(self, default, rows, columns, ordered, **params)
   1458         self.columns = columns
   1459         self.ordered = ordered
-> 1460         super(DataFrame,self).__init__(pdDFrame, default=default, allow_None=True, **params)
   1461         self._validate(self.default)
   1462 

TypeError: __init__() got multiple values for keyword argument 'allow_None' "

I have installed  umap.plot with this command 'pip install umap-learn[plot]'

Does someone have a solution ?
Thanks

**Comment by lmcinnes** [comment]
This looks to be an upstream issue with [holoviews](https://github.com/holoviz/holoviews); I can't help too much, but hopefully you can have better luck asking there.
