### ISSUE TITLE
Capability to combine cuml.UMAP objects

### ISSUE THREAD

**Issue by ronmoore3** [lmcinnes/umap#857]
Hi there, 

Unlike the UMAP library, it seems that there is currently no way in the RAPIDS cuML library to combine UMAP objects using the __mul__, __sub__, or __add__ operators (*,-,+). I was wondering if there was some workaround solution to this problem. I understand that this is not really a UMAP issue, but just wondering if someone could help here.

**Comment by lmcinnes** [comment]
I think this is best put as a feature request to cuML. They have great developers working on their UMAP for GPU implementation, and I think that if you can show demand for the feature then there is a good chance it could get implemented.
