### ISSUE TITLE
Best practice on large dataset

### ISSUE THREAD

**Issue by SoulEvill** [lmcinnes/umap#866]
First of all, let me express my gratitude for the existence of the UMAP library, I was able to apply it to some datasets and got valuable insight, thanks for making it possible! 

Now, I am trying to apply UAMP to a much larger data set (not textual data) which has 80 Million rows with 1000 columns (mostly continuous) and I have an instance with 768 memory and 96 cores. I tried to run vanilla UMAP against the whole dataset and obvious it cannot fit into the memory I tried subsample to 10 Million still no success. so I am wondering if there are any tips on how to run UMAP on a large dataset.

I also did a bit of research and found one issue suggesting first taking a sample of the data then performing Parametric (neural network) UMAP, and lastly using fitted UAMP to run the update function for the rest of the data. I am wondering if that's the best practice for a large dataset. one of the concerns that I have is that finding the right nn architecture could be whole another beast so still, a bit hesitant to do so. 

I do realize this is a very broad question and I am also not looking for a specific answer, any tip/suggestion is highly appreciated!/

Thanks a lot!

**Comment by SoulEvill** [comment]
@timsainb That's helpful! Curious to know how do I leverage these smaller UMAP graphs? is there a way to combine them? I am assuming UMAP is not a deterministic algorithm, especially with different initialization. so different subset runs might end up with very different embedding spaces.

The end goal here is to be able to run the clustering on these embeddings.

**Comment by lmcinnes** [comment]
There is good evidence that subset embeddings (presuming a reasonable subset sample) are reasonable proxies for the full data result (up to scaling, rotations and reflections), so I wouldn't expect the subsets to be wildly different from each other; especially not in terms of broad qualitative cluster structure. You can certainly compare the consistency by doing procustes alignment of overlapping subset samples.

**Comment by SoulEvill** [comment]
thank you all! I am going to try on the sample and will report back later! thank you!
