### ISSUE TITLE
Images look flipped - reproducibility

### ISSUE THREAD

**Issue by khushpatelmd** [lmcinnes/umap#868]
I am using a dataset of size 37376 samples with 128 dimensions. I am reducing it to 2 components with umap.UMAP(random_state=42,n_components=2). When the dataset is shuffled, the plot of the 2 components looks rotated. 

![umap1](https://user-images.githubusercontent.com/61388622/170356467-d95e8697-a1a8-4ed7-8fef-68c1e74cbd9c.png)

![umap2](https://user-images.githubusercontent.com/61388622/170356484-481b2d66-bf27-4202-823e-0fbc4c88bec6.png)

**Comment by jc-healy** [comment]
UMAP uses a stochastic algorithm to lay out its points in the lower
dimensional space.  As such there is no guaranteed consistency between the
two embeddings.  The fixed random state should result in the same embedding
for exactly the same inputs but it seems that your shuffling the data is
altering that fixed state.  Is that problematic for some reason?

**Comment by khushpatelmd** [comment]
Thank you for your prompt response. Its not problematic but just wanted to be sure I am not making mistake in using the package.
