### ISSUE TITLE
metric="precomputed" for more than 4096 entries

### ISSUE THREAD

**Issue by kwonoh** [lmcinnes/umap#88]
Hi Leland,

First of all, I like to thank you for this awesome library.

I am trying to compute the embedding of 64K entries based on a distance matrix.
When I passed a distance matrix (computed by Laplacian kernel) to UMAP, I got an exception from `fit` function at [the line 1419](https://github.com/lmcinnes/umap/blob/b241e3e580c37ff58165918774c61091631b280c/umap/umap_.py#L1419)

Based on the `if` clause at [the line 1360](https://github.com/lmcinnes/umap/blob/b241e3e580c37ff58165918774c61091631b280c/umap/umap_.py#L1360), it seems the if clause only checks the size but not the `self.metric`.

Could you please check on this issue?

Thank you,
Oh-Hyun

**Comment by lmcinnes** [comment]
Good catch! Thank you. This was the new transform functionality getting
caught up (transforming new data does not work for precomputed metrics).
Should be fixed in master now and will be available n packages with the
next bug fix release.

**Comment by kwonoh** [comment]
Thank you for the fix. I tested with my dataset and it is working now.
