### ISSUE TITLE
Memory handling with UMAP.fit

### ISSUE THREAD

**Issue by MichaelMMeskhi** [lmcinnes/umap#890]
I have approx. 100k vectors with 512 dims. Doing the following:

```python
reducer = umap.UMAP(**umap_args).fit(vectors) # low_memory=True
```

Causes my Colab notebook to crash. I have 27Gb of available RAM. Logs leave no traceable error to better understand what or why its crashing. Any suggestions?

**Comment by NamLQ** [comment]
Two options for you:
- Buy more RAM
- Using PCA to reduce the number of features

**Comment by MichaelMMeskhi** [comment]
@lmcinnes I managed to get some exact info from Colab and after getting 30Gb of RAM it finally fit and ran fine. Thank you for the advice on RAPIDs, interesting for future work.
