### ISSUE TITLE
UMAP based on correlation matrix

### ISSUE THREAD

**Issue by bigsuicideparty** [lmcinnes/umap#926]
I would like to use UMAP as a preprocessing step for density based clustering (DBScan) of a multidimensional data set. Is it possible to utilize a correlation matrix that I have generated for my data in this approach? According to the [[manual](https://umap-learn.readthedocs.io)][1] it should be possible to provide a precomputed k-nn. I was thinking of converting my correlation matrix to a distance matrix and use this as an input for the nearest neighbor algorithm. Do you think this is a sensible approach? If so, has anyone of you suggestions on how to properly implement this in python? My thoughts were something along the line of:

starting with a correlation matrix (*correlation_matrix*) of my actual data matrix (*df_data*)

   ```
 import umap.umap_ as umap
    from umap.umap_ import nearest_neighbors

    dist_matrix = 1 - correlation_matrix
    knn_correlation = nearest_neighbors(dist_matrix,
                              n_neighbors=15,
                              metric="precomputed",
                              metric_kwds=None,
                              angular=False,
                              random_state=None,
                             )

    knn_embeddings = umap.UMAP(n_neighbors=15,min_dist=0.1,
                        precomputed_knn=knn_correlation,
                        ).fit_transform(df_data)
```

 
Has any come across a similar situation or has any suggestions? Thank you!

  [1]: https://umap-learn.readthedocs.io

**Comment by jlmelville** [comment]
What you have is essentially correct. There is one (maybe two) issues:

1. you need to persuade UMAP to accept pre-computed nearest neighbors, which you can do by replacing the third element of the tuple returned by `nearest_neighbors` with a dummy class.
2. if your dataset is small, you need to set `force_approximation_algorithm=True` when you create the `umap.UMAP` object. 

To remedy this, insert something like this after creating `knn_correlation` and before calling the `umap.UMAP` constructor:

```python
import pynndescent 


class DummyNNDescent(pynndescent.NNDescent):
    def __init__(self):
        return

knn_correlation = (knn_correlation[0], knn_correlation[1], DummyNNDescent())
```

Then where you are calling `umap.UMAP(n_neighbors=15, min_dist=0.1, precomputed_knn=knn_correlation)` also add `force_approximation_algorithm=True` as an argument.

Hopefully #909 means that the dummy class step won't be necessary in the next release of UMAP and your code would basically work as-is. The `force_approximation_algorithm` bit remains an issue, but from #848 it seems like that is just an oversight, and as I usually use precomputed knns with UMAP, I really should work on a PR to remove this requirement.

As this is a bit confusing in its current state, here's a full example using the `iris` dataset and creating a Euclidean distance matrix directly. Hopefully this helps show what changes are required:

```python
import matplotlib.pyplot as plt
import pynndescent
import sklearn.metrics
import umap.umap_ as umap
from sklearn.datasets import load_iris
from umap.umap_ import nearest_neighbors

iris = load_iris()

# make a dense distance matrix from the data
iris_dm = sklearn.metrics.pairwise_distances(iris.data)

knn_correlation = nearest_neighbors(
    iris_dm,
    n_neighbors=15,
    metric="precomputed",
    metric_kwds=None,
    angular=False,
    random_state=None,
)


# At this point we need to fool UMAP into accepting our pre-computed neighbors
class DummyNNDescent(pynndescent.NNDescent):
    def __init__(self):
        return

# Add this dummy class to the pre-computed knn tuple
knn_correlation = (knn_correlation[0], knn_correlation[1], DummyNNDescent())

# To use pre-computed neighbors with small data, you must pass force_approximation_algorithm=True 
# just always set it to be on the safe side
knn_embeddings = umap.UMAP(
    n_neighbors=15,
    min_dist=0.1,
    precomputed_knn=knn_correlation,
    force_approximation_algorithm=True,
).fit_transform(iris.data)

plt.scatter(knn_embeddings[:, 0], knn_embeddings[:, 1], c=iris.target, alpha=0.5)

# should look at lot like:
#iris_umap = umap.UMAP(
#    n_neighbors=15,
#    min_dist=0.1,
#).fit_transform(iris.data)
#
# plt.scatter(iris_umap[:, 0], iris_umap[:, 1], c=iris.target, alpha=0.5)
```

**Comment by bigsuicideparty** [comment]
Thank you so much for that fast and detailed response including the example.

**Comment by jlmelville** [comment]
#927 has been merged so with the next release of UMAP you will not have to set `force_approximation_algorithm=True` if you have < 4096 items in your dataset.
