### ISSUE TITLE
Questions about layouts.py

### ISSUE THREAD

**Issue by Fzx-oss** [lmcinnes/umap#930]
### Question:
I have a question about UMAP's `layouts.py`. Specifically, it is at line `136` of the `layouts.py` code (the positive sampling calculation step of the function `_optimize_layout_euclidean_single_epoch`). 

My understanding is that lines `135` and `136` of `layouts.py` correspond to the equation $$\frac{-2ab||\mathbf{y}_i - \mathbf{y}_j||_2^{2(b-1)}}{1+||\mathbf{y}_i - \mathbf{y}_j||_2^2} w((x_i, x_j)) (\mathbf{y}_i - \mathbf{y}_j)$$ in section **3.2 Graph Layout** of the paper.

However, I found that the denominator of the above formula calculated in line `135` of the code is $$a + ||\mathbf{y}_i - \mathbf{y}_j||_2^{2b}$$, not $1+||\mathbf{y}_i - \mathbf{y}_j||_2^2$.

I am not sure if my understanding is correct, and I hope to get an explanation from the author.
Thanks a lot!

### About code:
https://github.com/lmcinnes/umap/blob/a7118a004b403b8cc9d9876854fd9d7f95f7ea94/umap/layouts.py#L134-L136
```
136: grad_coeff /= a * pow(dist_squared, b) + 1.0 # -> grad_coeff /= 1.0 + dist_squared
```

**Comment by jlmelville** [comment]
This is an error in the equation in the paper (see also #460 which covers similar ground). I made a mess of several of the equations and I hope one day there will be a further revision to the UMAP paper which will wash away my sins.

The alternative expression you are suggesting for the denominator is also wrong, though (happens to the best of us!). For the avoidance of doubt, the expression for the quoted part of the gradient should be:

$$\frac{-2ab\left|| \mathbf{y}_i - \mathbf{y}_j \right||_2^{2\left(b-1\right)}}{1 + a\left|| \mathbf{y}_i - \mathbf{y}_j \right||_2^{2b}}
$$

(and yes it took me several attempts to get this correctly formatted just trying to write this out here)

**Comment by Fzx-oss** [comment]
Thank you for the quick response and clear explanation!
