### ISSUE TITLE
Understanding n_neighbours 

### ISSUE THREAD

**Issue by Neoanarika** [lmcinnes/umap#94]
Inspired by https://distill.pub/2016/misread-tsne/, i have been testing different values of n_neighbours for umap on the Gaussian distribution. 

![download](https://user-images.githubusercontent.com/5188337/43323110-4a85c1c8-91e3-11e8-9c4c-6fab3e6f7b11.png)
Figure 1: The first image has a value of 5 n_neighbours and every image after the first image has an increment of 5 n_neighbours 

As you can see from figure 1, after n_neighbours > 20 there doesn't seem to be much change in the shape of the embedding. Is there an intuitive reason for this cos from the description of n_neighbours I am expecting umap to look more Gaussian with higher values of n_neighbours ?

**Comment by lmcinnes** [comment]
UMAP is pretty data hungry -- if there isn't enough data it tends to find
patterns in the data that is there; in this case the random noise within
the Gaussian. If you add more data it will look more ball like. In general
UMAP will contract a Gaussian to a tight ball with the crisp border. It
sees the fading edge of the Gaussian as simply a sparser region of the
manifold, so the whole Gaussian is effecively a single connected component
of the manifold, and is thus represented by a ball with a crisp border.
Once you hit a large enough ``n_neighbors`` for UMAP to recover that
structure there isn't too much more to be found without more data to
clarify the structure.

I hope that helps somewhat as an explanation.

**Comment by sleighsoft** [comment]
Closed but looks relevant. Marked as Good Reads!
