### ISSUE TITLE
Error in distfun(dT, i, seq(i + 1, V)) :  Not compatible with requested type: [type=character; target=double

### ISSUE THREAD

**Issue by Su870** [lmcinnes/umap#955]
I am getting this error while trying to run UMAP on my dataset. Below is the code that I used:

library(umap)
head(scenic_umap,3)
scenic.data <- scenic_umap[, grep("X|Y", colnames(scenic_umap))]
scenic.labels <- scenic_umap[, "X.1"]
scenic.umap <- umap(scenic.data)
Error in distfun(dT, i, seq(i + 1, V)) : 
  Not compatible with requested type: [type=character; target=double].
In addition: Warning message:
In umap.prep.input(d, config) : NAs introduced by coercion

Here is the data set:

<img width="1069" alt="Screenshot 2023-01-23 at 9 41 31 PM" src="https://user-images.githubusercontent.com/114273669/214207812-df57071e-fe20-40a1-9499-7a242353a4ac.png">

Thank you !

**Comment by tkonopka** [comment]
Hi @Su870. It seems you are using R and this issue actually pertains to a different package [here](https://github.com/tkonopka/umap). 

In any case, the dataset contains column 'X.1' with character values, and that is not supported. Try to remove that column and run only on numeric data. 

Also, there is a warning message that suggests your dataset may have NA values. You will likely need to handle that somehow. Two common strategies are to remove rows with missing values or to impute the missing information in some way that suits your application.

**Comment by Su870** [comment]
Yes! @tkonopka it worked but then when I finish my run the umap is empty. 

I renamed some of my variables from the code above, here is the updated one:
data <- Finalpyscenic_ucec_umap_edited
datapoint <- data[, -1]
labels <- data[, "Patient"]
ucec.umap <- umap(datapoint)
plot.scenic(ucec.umap, labels)

The reference code for plot.scenic is below:
plot.scenic <- function(x, labels,
         main="A UMAP visualization of FH_UCEC",
         colors=c("#ff7f00", "#e377c2", "#17becf"),
         pad=0.1, cex=0.6, pch=19, add=FALSE, legend.suffix="",
         cex.main=1, cex.legend=0.85) {

layout <- x
if (is(x, "umap")) {
layout <- x$layout
} 

xylim <- range(layout)
xylim <- xylim + ((xylim[2]-xylim[1])*pad)*c(-0.5, 0.5)
if (!add) {
  par(mar=c(0.2,0.7,1.2,0.7), ps=10)
  plot(xylim, xylim, type="n", axes=F, frame=F)
  rect(xylim[1], xylim[1], xylim[2], xylim[2], border="#aaaaaa", lwd=0.25)  
}
points(layout[,1], layout[,2], col=colors[as.integer(labels)],
       cex=cex, pch=pch)
mtext(side=3, main, cex=cex.main)

labels.u <- unique(labels)
legend.pos <- "topleft"
legend.text <- as.character(labels.u)
if (add) {
  legend.pos <- "bottomleft"
  legend.text <- paste(as.character(labels.u), legend.suffix)
}

legend(legend.pos, legend=legend.text, inset=0.03,
       col=colors[as.integer(labels.u)],
       bty="n", pch=pch, cex=cex.legend)
}

plot.scenic(scenic.umap, scenic.labels)

![FailedUMAP](https://user-images.githubusercontent.com/114273669/214473858-6e86a693-c516-4266-883b-023363950b6d.png)

**Comment by tkonopka** [comment]
Glad the embedding worked. For the visualization, it is hard to see/guess what is happening. In such cases, start with previewing the matrix of coordinates, then make a basic plot with default settings, and add the visualization extras gradually.
