### ISSUE TITLE
install fails with recent numpy and numba versions (requires numpy<1.24)

### ISSUE THREAD

**Issue by vdet** [lmcinnes/umap#970]
Hello,

`pip3 install umap-learn` returns this message on my system:

```
[...]
Building wheels for collected packages: umap-learn, pynndescent
  Building wheel for umap-learn (setup.py) ... done
  Created wheel for umap-learn: filename=umap_learn-0.5.3-py3-none-any.whl size=82819 sha256=f5198b87071085fe9297974454cbcfb17dffab3527313989634c81f6d88ba0ae
  Stored in directory: /root/.cache/pip/wheels/a9/3a/67/06a8950e053725912e6a8c42c4a3a241410f6487b8402542ea
  Building wheel for pynndescent (setup.py) ... done
  Created wheel for pynndescent: filename=pynndescent-0.5.8-py3-none-any.whl size=55497 sha256=b501aa7d23beb8da548b722b0554c35fa9d8abaa88f2c932ed5852230218e9cc
  Stored in directory: /root/.cache/pip/wheels/1c/63/3a/29954bca1a27ba100ed8c27973a78cb71b43dc67aed62e80c3
Successfully built umap-learn pynndescent
ERROR: numba 0.56.4 has requirement numpy<1.24,>=1.18, but you'll have numpy 1.24.2 which is incompatible.
[...]
```

The issue is that other packages on my system won't work with `numpy<1.24` and recent numba versions. Any work around?

All the best

**Comment by lmcinnes** [comment]
Unfortunately this one is upstream of what I can manage. umap relies on numba for performance, and while they are pretty swift at updating it for new numpy releases it seems they haven't gotten there yet. You could see if you can get a dev version of numba that does support the latest numpy from their conda channels or their github.

**Comment by rokity** [comment]
This issue it's still active when you install umap. Maybe there are other solution to avoid this issue @lmcinnes ?

**Comment by rokity** [comment]
If I use umap and seaborn in the same project there is a conflict.
