### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by mjmucha** [lmcinnes/umap#978]
The latest release is almost a year old now (https://github.com/lmcinnes/umap/releases/tag/0.5.3) and there are over 90 commits in the master branch with various fixes and small additions. 

A new release would be therefore much appreciated.

Thanks!

**Comment by mjmucha** [comment]
bump @lmcinnes

**Comment by lmcinnes** [comment]
I hoping for a release soon; I'm waiting on a small set of fixes to get wrapped up. Hopefully this month or early next month?

**Comment by mjmucha** [comment]
That would be great! I'm waiting for a UMAP release to publish a project of mine :)

**Comment by mjmucha** [comment]
fixed with [the newest release](https://github.com/lmcinnes/umap/tree/0.5.4).

Thanks!
