### ISSUE TITLE
Return intermediate embeddings

### ISSUE THREAD

**Issue by PierreGtch** [lmcinnes/umap#987]
Hello,

Would it be possible to return the embeddings every (n) iterations?

This feature would allow displaying, during UMAP's training, the evolution of the embedding space, the same way it is done for t-SNE in TensorFlow's [embedding projector](https://projector.tensorflow.org).

![t-SNE example](https://www.kaggle.com/code/frankmollard/dimensionality-reduction-3d-interactive?scriptVersionId=45684929&cellId=5)

**Proposed solution:**
We could allow the user to pass a function that would be called every n iteration with the current embedding vectors as parameter. This would be relatively flexible and allow parallelising the plotting part.

**Comment by lmcinnes** [comment]
There is the PR #696 which allows you to pass a list to n_epochs and it will return the embeddings at every epoch in the list. That may be sufficient. If you want a "real time" version that emits the embeddings as they happen you could potentially create that by altering the code to have a ``yield`` at the end of each iteration (or every nth iteration). That's a small code change that you could likely make yourself. On the other hand providing a good API for that, consistent with everything else that is already there, is a little harder. If you have thought on how you would like that to work I would welcome suggestions.

**Comment by PierreGtch** [comment]
Thanks, I was not aware of PR #696. This should be enough for now. I might come back to this later
